# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: EuSoft.Eudic
PackageVersion: 26.9.1.0
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silentWithProgress
InstallerSwitches:
  Silent: /s
  SilentWithProgress: /s
UpgradeBehavior: install
FileExtensions:
- bgl
- eudic
- ld2
- mdx
ProductCode: eudic
ReleaseDate: 2026-09-18
Installers:
- Architecture: x64
  InstallerUrl: https://static.frdic.com/pkg/eudic_win.exe?t=20260929
  InstallerSha256: A4A13B82FE282552417A97D8A9A15E17AE8E5CB8A9AC10AE2814A0EDAD3489BE
ManifestType: installer
ManifestVersion: 1.12.0
