# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Azeus.Convene
PackageVersion: 10.1.215157
InstallerType: inno
Scope: machine
UpgradeBehavior: install
ProductCode: '{B5E3F4E3-C2F6-460D-8280-9A830C5E0B81}_is1'
ReleaseDate: 2026-09-29
AppsAndFeaturesEntries:
- ProductCode: '{B5E3F4E3-C2F6-460D-8280-9A830C5E0B81}_is1'
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Convene'
Installers:
- Architecture: x64
  InstallerUrl: https://www.azeusconvene.com/installers/winos/standard/convene_setup.10.1.215157-64bit.exe
  InstallerSha256: DFD14CC7DD5B712FDBD93734AB02DF58F0ACFBF7642FAFB0B6245EA966E6C452
ManifestType: installer
ManifestVersion: 1.28.0
