# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: KoalaFacts.HeroParser
PackageVersion: 2.8.0
InstallerLocale: en-US
MinimumOSVersion: 10.0.17763.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: heroparser.exe
  PortableCommandAlias: heroparser
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/KoalaFacts/HeroParser/releases/download/v2.8.0/heroparser-v2.8.0-win-x64.zip
  InstallerSha256: 908CC6CC7092B7E71FB3FB3D188ED1B773F14F3D78779CC56C883B74B4FA083A
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-29
