# Created with WinGet Updater using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: pbek.QOwnNotes
PackageVersion: 26.9.13
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: QOwnNotes.exe
  PortableCommandAlias: qownnotes.exe
ReleaseDate: 2026-09-27
Installers:
- Architecture: neutral
  InstallerUrl: https://github.com/pbek/QOwnNotes/releases/download/v26.9.13/QOwnNotes.zip
  InstallerSha256: 4A45559EDEDF8A61CDE349A6692801794E6F2F0BCBC9EBABB9BDECC10B3061B9
ManifestType: installer
ManifestVersion: 1.12.0
