# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: JDE-Projects.SimpleSFTPClient
PackageVersion: 1.9.2
InstallerLocale: en-US
InstallerType: inno
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/JDE-Projects/Simple-SFTP-Client/releases/download/v1.9.2/SimpleSFTPClient-v1.9.2-setup.exe
  InstallerSha256: 1F50658644D572AA2CBDB65CC02F45E62A015CBEED61AB42A53E4811C8BEF53D
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-29
