# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: GitHub.cli
PackageVersion: 2.102.0
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- gh
ReleaseDate: 2026-09-30
Installers:
- Architecture: x86
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/cli/cli/releases/download/v2.102.0/gh_2.102.0_windows_386.msi
  InstallerSha256: 9D7CD7F991622FDF98401E2BF41D3449E9471E8E75FA70812CA814174A852D07
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  ProductCode: '{AF76F256-849B-41A9-AFED-22791CC1F282}'
  AppsAndFeaturesEntries:
  - ProductCode: '{AF76F256-849B-41A9-AFED-22791CC1F282}'
    UpgradeCode: '{767EC5D2-C8F0-4912-9901-45E21F59A284}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles(x86)%/GitHub CLI'
- Architecture: x86
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: bin/gh.exe
    PortableCommandAlias: gh
  InstallerUrl: https://github.com/cli/cli/releases/download/v2.102.0/gh_2.102.0_windows_386.zip
  InstallerSha256: 6BB9A59F4DC0DE75286E066FD875652958096EC58903A2947A3BA03F9C7DB12E
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/cli/cli/releases/download/v2.102.0/gh_2.102.0_windows_amd64.msi
  InstallerSha256: 7944B579D76359E5B859A263BF63583E271AE3FBD427AE46E133C1F348B46371
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  ProductCode: '{4EF7967E-A6AE-4EA6-80F8-448F03B4C0B4}'
  AppsAndFeaturesEntries:
  - ProductCode: '{4EF7967E-A6AE-4EA6-80F8-448F03B4C0B4}'
    UpgradeCode: '{8CFB9531-B959-4E1B-AA2E-4AF0FFCC4AF4}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/GitHub CLI'
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: bin/gh.exe
    PortableCommandAlias: gh
  InstallerUrl: https://github.com/cli/cli/releases/download/v2.102.0/gh_2.102.0_windows_amd64.zip
  InstallerSha256: AE64E556ECC240B200F7EBA60D550E4BB60D78E860E69DD88C449405B86067F4
- Architecture: arm64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/cli/cli/releases/download/v2.102.0/gh_2.102.0_windows_arm64.msi
  InstallerSha256: 08E9CBB5647373A186E010817866778CE212F28C20AFEC307726D5797B17343D
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  ProductCode: '{9705BE81-AE7F-4A8D-B94B-2F4735D5FF6A}'
  AppsAndFeaturesEntries:
  - ProductCode: '{9705BE81-AE7F-4A8D-B94B-2F4735D5FF6A}'
    UpgradeCode: '{5D15E95C-F979-41B0-826C-C33C8CB5A7EB}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/GitHub CLI'
- Architecture: arm64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: bin/gh.exe
    PortableCommandAlias: gh
  InstallerUrl: https://github.com/cli/cli/releases/download/v2.102.0/gh_2.102.0_windows_arm64.zip
  InstallerSha256: 5DCF12AA8525EABD0C46EC414F323AB6CF65229FC2CD46543CC705001BBAF223
ManifestType: installer
ManifestVersion: 1.28.0
