# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: sysmanage.sysmanage
PackageVersion: 3.9.0.17
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/bceverly/sysmanage/releases/download/v3.9.0.17/sysmanage-3.9.0.17-windows-x64.msi
  InstallerSha256: 438C5F545683BAA9195968897A3A7B54151D80ACE6BD1C051A7099697F2D3855
  ProductCode: '{B53357E8-2B4A-455E-910E-27E1801722BE}'
  AppsAndFeaturesEntries:
  - ProductCode: '{B53357E8-2B4A-455E-910E-27E1801722BE}'
    UpgradeCode: '{F1E2D3C4-B5A6-4D7C-9E8F-1A2B3C4D5E6F}'
- Architecture: arm64
  InstallerUrl: https://github.com/bceverly/sysmanage/releases/download/v3.9.0.17/sysmanage-3.9.0.17-windows-arm64.msi
  InstallerSha256: E967505F2933A934ACFF101BD797C135C7B1C7BA93F205EBEF1CE16B614B8B58
  ProductCode: '{2635AA8D-4618-45C6-8228-43F84F735A72}'
  AppsAndFeaturesEntries:
  - ProductCode: '{2635AA8D-4618-45C6-8228-43F84F735A72}'
    UpgradeCode: '{F1E2D3C4-B5A6-4D7C-9E8F-1A2B3C4D5E6F}'
ManifestType: installer
ManifestVersion: 1.12.0
