# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Zen-Team.Zen-Browser.Twilight
PackageVersion: 1.23t
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
  Custom: /DesktopShortcut=false
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Zen Twilight
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/zen-browser/desktop/releases/download/twilight-1/zen.installer.exe
  InstallerSha256: B4F83DABB989A8C99924D6EBFC931874E2D350C339A5EA9C28A9D60D1645FE5F
  AppsAndFeaturesEntries:
  - DisplayName: Zen Twilight (x64 en-US)
- Architecture: arm64
  InstallerUrl: https://github.com/zen-browser/desktop/releases/download/twilight-1/zen.installer-arm64.exe
  InstallerSha256: F9A5AA86744935ED714CE0F740B4361EB5EE71CFBEF482ED146FA5A2913083E3
  AppsAndFeaturesEntries:
  - DisplayName: Zen Twilight (AArch64 en-US)
ManifestType: installer
ManifestVersion: 1.12.0
