# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: o-murphy.ebalistyka
PackageVersion: 0.1.20.208
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: ebalistyka.exe
  PortableCommandAlias: ebalistyka
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/o-murphy/ebalistyka/releases/download/v0.1.20/ebalistyka_windows_x86_64.zip
  InstallerSha256: F5DB09CE0B5BF2655AEBCA78E81D482009B165811BE8A7853AA2D39B50D4C224
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-29
