# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: 0-don.clippy
PackageVersion: 1.7.7
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
UpgradeBehavior: uninstallPrevious
ProductCode: clippy
ReleaseDate: 2026-09-28
AppsAndFeaturesEntries:
- DisplayName: clippy
  ProductCode: clippy
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\clippy'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/0-don/clippy/releases/download/v1.7.7/clippy_1.7.7_x64-setup.exe
  InstallerSha256: D3955092F250B51C53595220903092757162CFE3A0CBEDB6346FF677627CFDCF
ManifestType: installer
ManifestVersion: 1.12.0
