# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.hi-IN
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox ESR
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win32/hi-IN/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 959BD36D82B4F4DFF2051308EF2CB2A613BDC4FFCD7373A1C932A1B98AF935BE
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64/hi-IN/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 6559A1ADDE8F03C24CC325C4243A59D7735F0CD3B745ADCA4D2C04FEC1182F25
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64-aarch64/hi-IN/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: B9E1EEE60CBE17BB8A69EE3C2DE645BDFA41FC25EFD974AED908EF04D97F9099
ManifestType: installer
ManifestVersion: 1.12.0
