# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: ciromattia.KCC
PackageVersion: 12.0.0
InstallerType: portable
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- KCC
ReleaseDate: 2026-09-26
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ciromattia/kcc/releases/download/v12.0.0/KCC_12.0.0.exe
  InstallerSha256: 493E6F5B0DFE6A2D4415583CF1A1D1159D98BCE1495DF1A4D446AD7916966B5A
ManifestType: installer
ManifestVersion: 1.12.0
