# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: msitarzewski.AgencyAgents
PackageVersion: 0.3.0
ReleaseDate: 2026-07-05
InstallerType: nullsoft
ProductCode: Agency Agents
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/msitarzewski/agency-agents-app/releases/download/v0.3.0/Agency_Agents_0.3.0_x64-setup.exe
  InstallerSha256: 4792AC9B998F3C2D89276AD437A57938A283C29D182A4BFFF9C6C33F74CAF3F2
- Architecture: arm64
  InstallerUrl: https://github.com/msitarzewski/agency-agents-app/releases/download/v0.3.0/Agency_Agents_0.3.0_arm64-setup.exe
  InstallerSha256: f5927b1668e7ff66f28374975ed0b60dabfd4f29bfac4ba57fc8a09a1207682e
ManifestType: installer
ManifestVersion: 1.12.0
