# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: misxzaiz.Polaris
PackageVersion: 10.5.9
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
UpgradeBehavior: install
ProductCode: '{232F4044-E82E-421A-987F-B41459778794}'
ReleaseDate: 2026-09-29
AppsAndFeaturesEntries:
- UpgradeCode: '{B90F6FC4-DDEE-59A6-9DE8-49A41A495360}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/misxzaiz/Polaris/releases/download/v10.5.9/polaris_10.5.9_x64_en-US.msi
  InstallerSha256: 16634C7420BE326F0B07C321E0EDFB31B29E0E9B476090E0997D9B357AF94B98
ManifestType: installer
ManifestVersion: 1.12.0
