# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: LIXianSenQwQ.Nomo
PackageVersion: 0.5.3
InstallerType: nullsoft
Scope: user
FileExtensions:
- json
- markdown
- md
- txt
ProductCode: Nomo
ReleaseDate: 2026-09-29
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Nomo'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/nomo-md/nomo/releases/download/v0.5.3/Nomo_0.5.3_x64-setup.exe
  InstallerSha256: 0F8E52DCB7FAA7E01A4E82F8A4FF7668ADE8D2C27E727A310A7F55BBD6743FE4
ManifestType: installer
ManifestVersion: 1.12.0
