# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: 1History.1History
PackageVersion: 0.4.1
PackageLocale: zh-CN
PublisherUrl: https://liujiacai.net/
ShortDescription: 您所有的历史记录都在一个文件中。
Description: 1History 是一个命令行工具，可以将不同浏览器的历史记录备份至一个文件中，甚至更多！
Tags:
- 历史记录
- 备份
- 浏览记录
ManifestType: locale
ManifestVersion: 1.12.0
