# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.br
PackageVersion: "157.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win32/br/Firefox%20Setup%20157.0.exe
  InstallerSha256: D6232359DBAF8C208EA9B301E9E12A095142167AEE83ABD4568A5C3341405302
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64/br/Firefox%20Setup%20157.0.exe
  InstallerSha256: 88D8960B8BEFBC4D313A68F28E40AA705ED0FE4E672ADBAB8BB0A763AF0C6731
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64-aarch64/br/Firefox%20Setup%20157.0.exe
  InstallerSha256: 7868522A60C75B905791C12133433664682113F96E462F45A5201E2C270AF21C
ManifestType: installer
ManifestVersion: 1.12.0
