# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Coooolfan.UniRhy
PackageVersion: 0.1.1
PackageLocale: en-US
Publisher: unirhy
PublisherUrl: https://github.com/Coooolfan
PublisherSupportUrl: https://github.com/Coooolfan/UniRhy/issues
Author: Coooolfan
PackageName: UniRhy
PackageUrl: https://unirhy.app/
License: AGPL-3.0
LicenseUrl: https://github.com/Coooolfan/UniRhy/blob/HEAD/LICENSE
ShortDescription: Self-hosted and scalable music streaming, designed for humans.
Description: UniRhy is a self-hosted music streaming platform organized as a monorepo with separated backend, frontend, and website projects. It aims to provide deployable and extensible music library management, playback, and synchronization capabilities, with cross-platform clients for the web, macOS, Windows, Android and iOS.
Tags:
- album
- artist
- audio
- music
- player
- playlist
- song
- sound
ReleaseNotesUrl: https://github.com/Coooolfan/UniRhy/releases/tag/0.1.0
ManifestType: defaultLocale
ManifestVersion: 1.12.0
