# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ErkanOzgurYilmaz.DisplayCAL
PackageVersion: 3.9.19
ReleaseDate: 2026-07-13
InstallerType: inno
Scope: machine
ElevationRequirement: elevatesSelf
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/eoyilmaz/displaycal-py3/releases/download/3.9.19/DisplayCAL-3.9.19-Windows-x64.exe
  InstallerSha256: 098A1EB6C775A8FE17BC720D2E703ADCE5D310CAA18AC1B717CE0DFDC6943DE3
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: GraemeGill.ArgyllCMS
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  InstallerUrl: https://github.com/eoyilmaz/displaycal-py3/releases/download/3.9.19/DisplayCAL-3.9.19-Windows-arm64.exe
  InstallerSha256: 1203cca3cf0c2546a826406d375d34933d453e4f25d10d2df3e8962532aff164
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: GraemeGill.ArgyllCMS
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ProductCode: '{4714199A-0D66-4E69-97FF-7B54BFF80B88}_is1'
AppsAndFeaturesEntries:
- ProductCode: '{4714199A-0D66-4E69-97FF-7B54BFF80B88}_is1'
ManifestType: installer
ManifestVersion: 1.12.0
