# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ca
PackageVersion: "157.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win32/ca/Firefox%20Setup%20157.0.exe
  InstallerSha256: 580EDBAEBF70EF3885EC95B5E2A4CC98BA0E8AB8B1D003A4EA2E5E0C3BE3A079
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64/ca/Firefox%20Setup%20157.0.exe
  InstallerSha256: 8E0AFA9A6A596EFB7FEC1A82BDD91DE8666496964886FF7E13A9DD5B5E00EC6E
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64-aarch64/ca/Firefox%20Setup%20157.0.exe
  InstallerSha256: D8BE3C9C7A7F85C80093D7BA6781F645CBD23001A490ABF558099F0FAB5EA6AE
ManifestType: installer
ManifestVersion: 1.12.0
