# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: osyka-yuri.RenderPilot
PackageVersion: 1.14.1
InstallerType: nullsoft
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/osyka-yuri/renderpilot/releases/download/v1.14.1/RenderPilot_1.14.1_x64-setup.exe
  InstallerSha256: 35A01D497446B080B117BD6CCD386DFD6FEC1FD2C1A87944210C10C84D21ECC2
  InstallerSwitches:
    Custom: /CurrentUser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/osyka-yuri/renderpilot/releases/download/v1.14.1/RenderPilot_1.14.1_x64-setup.exe
  InstallerSha256: 35A01D497446B080B117BD6CCD386DFD6FEC1FD2C1A87944210C10C84D21ECC2
  InstallerSwitches:
    Custom: /AllUsers
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-27
