# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: NewLooper.VirtualSpace
PackageVersion: 1.1.1760.0
Installers:
  - Architecture: x64
    InstallerType: msi
    InstallerUrl: https://github.com/newlooper/VirtualSpace/releases/download/Build-1.1.1760/VirtualSpace-1.1.1760.0-Full.msi
    InstallerSha256: D85FCBBF1E4EE60DD2A0D09B8B5E7C8C6916EAA8046F2D3293D5441CE7991C64
    ProductCode: '{8FFCEA2E-8F74-4786-8BFE-6156259AEE45}'
AppsAndFeaturesEntries:
  - DisplayName: VirtualSpace
    Publisher: newlooper.com
    ProductCode: '{8FFCEA2E-8F74-4786-8BFE-6156259AEE45}'
    UpgradeCode: '{4D2AFEC9-F961-40A5-9E88-2A0FBAFDF5EF}'
ManifestType: installer
ManifestVersion: 1.12.0
