# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Modrinth.ModrinthApp
PackageVersion: 0.21.6
InstallerType: nullsoft
Scope: user
ProductCode: Modrinth App
ReleaseDate: 2026-09-27
AppsAndFeaturesEntries:
- Publisher: ModrinthApp
  ProductCode: Modrinth App
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Modrinth App'
Installers:
- Architecture: x64
  InstallerUrl: https://launcher-files.modrinth.com/versions/0.21.6/windows/Modrinth%20App_0.21.6_x64-setup.exe
  InstallerSha256: 5A555F48C357EECED711EF4728585D2C33E25C265167ECA8D56398BC76BD01A5
ManifestType: installer
ManifestVersion: 1.12.0
