# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Modrinth.ModrinthApp
PackageVersion: 0.21.6
PackageLocale: en-US
Publisher: Modrinth
PublisherUrl: https://modrinth.com/
PublisherSupportUrl: https://support.modrinth.com/en/
PrivacyUrl: https://modrinth.com/legal/privacy
Author: Modrinth
PackageName: Modrinth App
PackageUrl: https://modrinth.com/app
License: GPL-3.0
LicenseUrl: https://github.com/modrinth/code/blob/main/apps/app/LICENSE
ShortDescription: The Modrinth App is a unique, open source Minecraft launcher that allows you to play your favorite mods, and keep them up to date, all in one neat little package.
Tags:
- minecraft
- minecraft-launcher
- modrinth
ReleaseNotes: |-
  Added
  - Added a new modal for Update all in the Content tab of your instance. You can now select each version for each project that needs an update, and view the changelogs, all in one place.
  - Modrinth Hosting: Added a new modal for Update all in the Content tab of the server panel. You can now select each version for each project that needs an update, and view the changelogs, all in one place.

  Changed
  - Bulk update operations now go through the download manager, rather than preventing you from leaving the content tab while it installs the updates.

  Fixed
  - Fixed relying on external metadata for already-installed loader verisons.
  - Fixed close button icon in the window controls not turning red on hover.
  - Fixed text overlapping into `` in markdown descriptions.
ReleaseNotesUrl: https://github.com/modrinth/code/releases/tag/v0.21.6
Documentations:
- DocumentLabel: Docs
  DocumentUrl: https://support.modrinth.com/en/collections/7804910-modrinth-app
ManifestType: defaultLocale
ManifestVersion: 1.12.0
