# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: OliverFida.FSimMan
PackageVersion: 0.4.1
InstallerType: inno
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.8
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/OliverFida/FSimMan/releases/download/v0.4.1/FSimMan-v0.4.1.exe
  InstallerSha256: 2B7D91F46BCB1652F1386BAADB58C19CE6BE82FE069DF3789370FAEAD098B806
ManifestType: installer
ManifestVersion: 1.10.0
