# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ransh2014.TRACE
PackageVersion: 0.5.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: TRACE.exe
  PortableCommandAlias: TRACE
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ransh2014/gt7telemtrace/releases/download/v0.5.0/gt7telem-windows.zip
  InstallerSha256: A9D392FD2BE604B4C733B2954EA382AD5FB75BDC391D35545EB7A8FF3EA062FD
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-27
