# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: ScryerMedia.Weaver
PackageVersion: 0.14.2
InstallerType: msi
InstallModes:
- silent
UpgradeBehavior: install
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/scryer-media/weaver/releases/download/weaver-v0.14.2/weaver-windows-x86_64.msi
  InstallerSha256: 63553C1814AC88E4C09DF78826A659FCB2827FF95FC280ECB9BD613ACA15AFCC
  ProductCode: '{E04ECA22-E9FD-4694-AC6D-BE76805DBCDC}'
- Architecture: arm64
  InstallerUrl: https://github.com/scryer-media/weaver/releases/download/weaver-v0.14.2/weaver-windows-arm64.msi
  InstallerSha256: 07CF8B25FCDF14C375D869BD929000FCDFBA69073351DB261576615505F94386
  ProductCode: '{989792C8-CD5C-4BB6-862B-5D9E45D94BBA}'
ManifestType: installer
ManifestVersion: 1.10.0
