# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Summa.ColigoDesktop
PackageVersion: 1.40.2
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://desktop.coligo.com/binaries/cdc/1.40.2/ColigoSetup.exe
  InstallerSha256: 1FD7E8BFB463E0BDDB1CCDC2C36D2BE28E3E1E37A2B59091BCEB196B9417A854
  ProductCode: ColigoDesktop
- Architecture: x64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://desktop.coligo.com/binaries/cdc/1.40.2/Coligo.msi
  InstallerSha256: 44B86C49DD8DBB1CD51D69F0692048D44DE7DDD5C3CEC558C1948E180DEDB3F3
  ProductCode: '{8B282FD1-3F49-4B6B-B7D2-2CFE7D83B57F}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{1DEFB56C-43D7-4517-BB73-777903479110}'
ManifestType: installer
ManifestVersion: 1.12.0
