# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json
PackageIdentifier: Stellar.StellarCLI
PackageVersion: 28.1.0
InstallerLocale: en-US
InstallerType: inno
Scope: machine
Dependencies:
  PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ProductCode: Stellar CLI_is1
ReleaseDate: "2026-09-28"
AppsAndFeaturesEntries:
  - ProductCode: Stellar CLI_is1
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Stellar CLI'
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/stellar/stellar-cli/releases/download/v28.1.0/stellar-cli-installer-28.1.0-x86_64-pc-windows-msvc.exe
    InstallerSha256: 2954EFA9FC21CA725491D71070D4D4EBAD460D2DDAB2B87D9ABB2F2E336CA6CD
ManifestType: installer
ManifestVersion: 1.9.0
