# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Microsoft.SafetyScanner
PackageVersion: 1.459.465.0
InstallerType: portable
Commands:
- safetyscanner
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://definitionupdates.microsoft.com/packages/content/msert.exe?packageType=Scanner&packageVersion=1.459.465.0&arch=x86
  InstallerSha256: C5DDD85D73AC23FE41673CEA5D2238D5D89A679828D8299FE57C49C53DD2E752
- Architecture: x64
  InstallerUrl: https://definitionupdates.microsoft.com/packages/content/msert.exe?packageType=Scanner&packageVersion=1.459.465.0&arch=amd64
  InstallerSha256: 5054906502AAFBBC1E352949E06B10B0C20A4CFE0AFC597DDAAF6C440A256AF5
ManifestType: installer
ManifestVersion: 1.28.0
