# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Sourcegraph.Amp
PackageVersion: 0.0.1790613389-g144226
InstallerType: portable
Commands:
- amp
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://static.ampcode.com/cli/0.0.1790613389-g144226/amp-windows-x64-baseline.exe
  InstallerSha256: 8F97323DAF0E8813D141589DF64C155FD1B92316DBAF1A9E184E15C069AC1AD4
ManifestType: installer
ManifestVersion: 1.12.0
