# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: co2lab.Anchors
PackageVersion: 0.1.216
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: anchors.exe
  PortableCommandAlias: anchors
Commands:
- anchors
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/co2-lab/anchors/releases/download/v0.1.216/anchors_0.1.216_windows_amd64.zip
  InstallerSha256: A29FEF98D8C98A8E97C75E943EFC3D9245FBB58B8C9F6A498771A476B59B8C98
- Architecture: arm64
  InstallerUrl: https://github.com/co2-lab/anchors/releases/download/v0.1.216/anchors_0.1.216_windows_arm64.zip
  InstallerSha256: 36B8A7FDE13013F24015A918B4CA40B6DBD31DF85561D3793FF1D0CD4B4A7A86
ManifestType: installer
ManifestVersion: 1.12.0
