# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ar
PackageVersion: "157.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win32/ar/Firefox%20Setup%20157.0.exe
  InstallerSha256: F88B495873FCD619A88F810D3881B98BEB069AA00CC088AC1CCEFC4EE558BE43
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64/ar/Firefox%20Setup%20157.0.exe
  InstallerSha256: 839B34192539CD6CA562FB7EC0154B8D5BB3DC6CE26FC0A2C303D6939E6393F8
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64-aarch64/ar/Firefox%20Setup%20157.0.exe
  InstallerSha256: 8C716AB9392DF1922E9492F11293E898CC7FC8CD8AC628E54CAA047E0EEE6C34
ManifestType: installer
ManifestVersion: 1.12.0
