# Automatically updated by the winget bot at 2026/Sep/27
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: 0-don.clippy
PackageVersion: 1.7.3
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
UpgradeBehavior: uninstallPrevious
ProductCode: clippy
ReleaseDate: 2026-08-11
AppsAndFeaturesEntries:
- DisplayName: clippy
  ProductCode: clippy
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\clippy'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/0-don/clippy/releases/download/v1.7.3/clippy_1.7.3_x64-setup.exe
  InstallerSha256: FD395769F5F304EEEEE565A8A0DAC86D3235A806F79FF2F48A3635D4DF8F020D
ManifestType: installer
ManifestVersion: 1.28.0
