# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: MartinDvorak.MindForger
PackageVersion: 2.5.0
InstallerLocale: en-US
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
FileExtensions:
- md
ProductCode: '{A1A3DAE4-FD5C-4600-B75D-D8895AA99693}_is1'
ReleaseDate: 2026-09-26
AppsAndFeaturesEntries:
- ProductCode: '{A1A3DAE4-FD5C-4600-B75D-D8895AA99693}_is1'
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\MindForger'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/dvorka/mindforger/releases/download/2.5.0/windows-installer-mindforger-2.5.0.exe
  InstallerSha256: 3CB3FC8C441578D59CAFEA43F51FAA654E40D565F137F5B5FDCC959D21568315
ManifestType: installer
ManifestVersion: 1.12.0
