# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: CCGnomes.VaultFlasher
PackageVersion: 1.0.0
InstallerLocale: en-US
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Protocols:
- vaultflasher
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/markCCGnomes/vault-flasher-releases/releases/download/v1.0.0/VaultFlasher-x64-setup.exe
  InstallerSha256: 0844DC2E7D5BEE544D8DA6098234878885D1FAAB1F393EC6334C15B74ABE9FB9
ManifestType: installer
ManifestVersion: 1.12.0
