# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: RiverScript.RiverScript
PackageVersion: 1.2.6
Platform:
- Windows.Desktop
InstallerType: nullsoft
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x64
  InstallerUrl: https://downloads.riverscript.com/releases/v1.2.6/riverscript_1.2.6_x64-setup.exe
  InstallerSha256: 865FDCE2B1BB784D1DDAC85278B02200541F80B3821C1DAEBFE8C0B26D92161E
ManifestType: installer
ManifestVersion: 1.12.0
