# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ja7ad.Hydra
PackageVersion: 1.0.1
InstallerType: nullsoft
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/ja7ad/hydra/releases/download/v1.0.1/hydra-1.0.1-windows-x64-setup.exe
    InstallerSha256: 167EC4E3C786843CD83B70E536881BC55B25F0CA12417592FAC886BB17A66712
  - Architecture: arm64
    InstallerUrl: https://github.com/ja7ad/hydra/releases/download/v1.0.1/hydra-1.0.1-windows-arm64-setup.exe
    InstallerSha256: 31DC28A89DB5CD54405DEF9C7D89BA5C73BC69C5037CF1EEE396A58988BB3B3C
ManifestType: installer
ManifestVersion: 1.12.0
