# Created with WinGet Updater using komac v2.15.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Instruqt.CLI
PackageVersion: 2427-422d0f4
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: instruqt.exe
InstallModes:
- silent
UpgradeBehavior: install
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/instruqt/cli/releases/download/2427-422d0f4/instruqt-windows.zip
  InstallerSha256: 1F0992F7D64A2065E0AE9F5575C594A3EAA5F1E6814B3B113AEF1464BE936F02
ManifestType: installer
ManifestVersion: 1.12.0
