# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: JetBrains.DataGrip
PackageVersion: 2026.2.6
InstallerType: nullsoft
InstallerSwitches:
  Log: /LOG="<LOGPATH>"
UpgradeBehavior: uninstallPrevious
FileExtensions:
- ipr
- sql
ProductCode: DataGrip 2026.2.6
ReleaseDate: 2026-09-29
AppsAndFeaturesEntries:
- DisplayVersion: 262.10968.148
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://download.jetbrains.com/datagrip/datagrip-2026.2.6.exe
  InstallerSha256: E8D7DC9CFEF5B7794575824BA063CA6F6DA45844087B3F799A3BB82D61F6957A
- Architecture: x64
  Scope: machine
  InstallerUrl: https://download.jetbrains.com/datagrip/datagrip-2026.2.6.exe
  InstallerSha256: E8D7DC9CFEF5B7794575824BA063CA6F6DA45844087B3F799A3BB82D61F6957A
  ElevationRequirement: elevationRequired
- Architecture: arm64
  Scope: user
  InstallerUrl: https://download.jetbrains.com/datagrip/datagrip-2026.2.6-aarch64.exe
  InstallerSha256: CA300D258DDD8686BEA9292DE6F51B7910E6073EA3841C30F3488FE7C9AF9E50
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://download.jetbrains.com/datagrip/datagrip-2026.2.6-aarch64.exe
  InstallerSha256: CA300D258DDD8686BEA9292DE6F51B7910E6073EA3841C30F3488FE7C9AF9E50
  ElevationRequirement: elevationRequired
ManifestType: installer
ManifestVersion: 1.12.0
