# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Ryko.GodotHub
PackageVersion: 1.4.5
InstallerLocale: en-US
InstallerType: wix
Scope: machine
ProductCode: '{FF215E09-4B07-4A4C-B015-E21AEE2C0A8C}'
ReleaseDate: 2026-09-28
AppsAndFeaturesEntries:
- Publisher: GodotHub
  ProductCode: '{FF215E09-4B07-4A4C-B015-E21AEE2C0A8C}'
  UpgradeCode: '{72724A70-2A9C-59CB-9DD8-EC8EB8DE6CC5}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%/GodotHub'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/RykoTheDev/GodotHub/releases/download/v1.4.5/GodotHub-1.4.5-windows-x64.msi
  InstallerSha256: F71A2849358E11600E979B7C9DBF2C0EB2DCC88AEC61CCFE5B5192964665ADED
ManifestType: installer
ManifestVersion: 1.12.0
