# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Sourcegraph.Amp
PackageVersion: 0.0.1790692375-ga7bdff
InstallerType: portable
Commands:
- amp
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  InstallerUrl: https://static.ampcode.com/cli/0.0.1790692375-ga7bdff/amp-windows-x64-baseline.exe
  InstallerSha256: AB5E20168F06EA2C1B593C646A0763D10614F483010374DB16726A1CDC0CAD94
ManifestType: installer
ManifestVersion: 1.12.0
