# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: Dystroy.broot
PackageVersion: 1.60.2
PackageLocale: en-US
Publisher: Dystroy
PublisherUrl: https://dystroy.org/broot/
PublisherSupportUrl: https://github.com/Canop/broot/issues
PackageName: Broot
PackageUrl: https://github.com/Canop/broot
License: MIT
LicenseUrl: https://github.com/Canop/broot/blob/HEAD/LICENSE
ShortDescription: A new way to see and navigate directory trees.
Tags:
- cli
- command-line
- rust
ReleaseNotes: "• fix some combinations being wrongly interpreted for input on some terminals (eg shift-r with kitty keyboard protocol enabled on ghostty/mac was interpreted as just a 'r')\r\n• preview of CRLF (Windows style) text files no longer shows a replacement char at the end of every line - Fix #1216\r\n• `:copy_line` no longer copies the end of line characters\r\n• PSD images are no longer previewed\r\n• content search no longer reports false matches in .bz2, .xz, .zst and .br files\r\n• nerdfont icons for TOML and YAML files - Thanks @noahkawaguchi"
ReleaseNotesUrl: https://github.com/Canop/broot/releases/tag/v1.60.2
ManifestType: defaultLocale
ManifestVersion: 1.12.0
