# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.ar
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox ESR
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win32/ar/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 46D3DA03864EED6E6D39657F02F22077B213EE8214B83EE10C037FEC582087A4
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64/ar/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 228CD0591C01C265ADB34A8AF12FE8AAF28D92580A3D77149900925A2774C419
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64-aarch64/ar/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 19551849862D5D89E542B66FDCECE8EFBEC98E4AAB2D459CC0AE2BD379ED758D
ManifestType: installer
ManifestVersion: 1.12.0
