# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.son
PackageVersion: "157.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win32/son/Firefox%20Setup%20157.0.exe
  InstallerSha256: 0241AFA09D777D5864F291FE5471EF68945F7C7861475A4969DBBC835DF6C5FB
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64/son/Firefox%20Setup%20157.0.exe
  InstallerSha256: 2F6C1AAD711AB11CCF772E6E7A5514D14F1D8E31E87156DC93AFD19481AD1D82
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64-aarch64/son/Firefox%20Setup%20157.0.exe
  InstallerSha256: FE44672D70A3A3C42FC5C2841B354E96A5C4DD3D4BB353FA2D5E86737059A13D
ManifestType: installer
ManifestVersion: 1.12.0
