# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: Socoliuc.FollowFrame
PackageVersion: 0.3.11
InstallerType: portable
UpgradeBehavior: install
Commands:
- followframe
Installers:
- Architecture: x64
  InstallerUrl: https://followframe.com/downloads/FollowFrame-Single-Exe-0.3.11-win32-x64.exe
  InstallerSha256: FF2F69466EEADE3B0041208EAE05C60F1FAAB2945E451A135AF1B08488CB14F1
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-29
