# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: MayDay.SnowApp
PackageVersion: 0.4.10
InstallerType: nullsoft
ProductCode: 93d8ffac-9b72-5a71-bb24-eb58c0fee1af
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/MayDay-wpf/snow-app/releases/download/v0.4.10/Snow-App-Setup-0.4.10.exe
  InstallerSha256: 7FE94592C39A418B0C4FB8D2DE0B51F3F4C4B52D8496122E742DA1D0952EAF18
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/MayDay-wpf/snow-app/releases/download/v0.4.10/Snow-App-Setup-0.4.10.exe
  InstallerSha256: 7FE94592C39A418B0C4FB8D2DE0B51F3F4C4B52D8496122E742DA1D0952EAF18
  InstallerSwitches:
    Custom: /allusers
ManifestType: installer
ManifestVersion: 1.12.0
