# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: mikf.gallery-dl
PackageVersion: 1.32.14
InstallerType: portable
Commands:
- gallery-dl
ReleaseDate: 2026-09-27
Installers:
- Architecture: x86
  InstallerUrl: https://codeberg.org/mikf/gallery-dl/releases/download/v1.32.14/gallery-dl_x86.exe
  InstallerSha256: 32E6A8533757F92414070573B327F9506DC3F6F8FB1541A604073FE05CC661EA
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x86
- Architecture: x64
  InstallerUrl: https://codeberg.org/mikf/gallery-dl/releases/download/v1.32.14/gallery-dl.exe
  InstallerSha256: 30E3830CB877F127323253C7F07F354E155D3766158969853141ACFF5AA82B36
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ManifestType: installer
ManifestVersion: 1.12.0
