# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.dsb
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox ESR
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win32/dsb/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 790C15C828199680E32C8B10F2AC446F903F13831492D7C86123741212F6F818
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64/dsb/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: D72E4D63AB08C3A2856F5508DEAE7AF6D62E50B996EBBEE2DB9FC2A71EDD9712
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64-aarch64/dsb/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: E825DC1BB1102ECBCF508117342C351D3C7367511BFDD45AE120744519161C3E
ManifestType: installer
ManifestVersion: 1.12.0
