# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Bambulab.CyberBrick
PackageVersion: 0.6.2
InstallerType: nullsoft
InstallModes:
- interactive
- silent
UpgradeBehavior: install
ProductCode: CyberBrickHangar
ReleaseDate: 2026-09-26
AppsAndFeaturesEntries:
- ProductCode: CyberBrickHangar
Installers:
- Architecture: x64
  InstallerUrl: https://public-cdn.bblmw.com/upgrade/cyber-brick/updates/Release_win32_x64/versions/0.6.2/cyber-brick-v0.6.2-win32-x64.exe
  InstallerSha256: E90800CEC4607F3BB6DCDBDE48B7943309773BE051EAF85E73367317D587E2EE
ManifestType: installer
ManifestVersion: 1.12.0
