# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Cindy.Cindy
PackageVersion: 0.1.94
InstallerType: nullsoft
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
ProductCode: 5a59f1e9-8f21-5646-8eed-e6da4126bb5c
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/makecindy/cindy/releases/download/v0.1.94/cindy-0.1.94-win32-x64-global.exe
  InstallerSha256: F9E79BD72750BDB4E8780A07EA86AF3180E4E859FC7ABB2EC3DB41F69EBEADD6
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/makecindy/cindy/releases/download/v0.1.94/cindy-0.1.94-win32-x64-global.exe
  InstallerSha256: F9E79BD72750BDB4E8780A07EA86AF3180E4E859FC7ABB2EC3DB41F69EBEADD6
  InstallerSwitches:
    Custom: /allusers
ManifestType: installer
ManifestVersion: 1.12.0
