# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: RebonAI.RebonDesktop
PackageVersion: 1.7.3
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
ProductCode: Rebon
ReleaseDate: 2026-09-27
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/RebonAI/Rebon-Code/releases/download/app-v1.7.3/Rebon_1.7.3_x64-setup.exe
  InstallerSha256: 4885A8EE1C2991F8D2C7562C1EA3FFD7B96B5738888AA7EE2C2AE3C253769299
ManifestType: installer
ManifestVersion: 1.12.0
