# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: afonsojramos.discrakt
PackageVersion: 4.1.2
InstallerLocale: und
InstallerType: wix
Scope: user
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{65138B84-102B-459C-A2AB-40F2F8A5A4B1}'
ReleaseDate: 2026-09-28
AppsAndFeaturesEntries:
- ProductCode: '{65138B84-102B-459C-A2AB-40F2F8A5A4B1}'
  UpgradeCode: '{8B55A0B3-6E9D-4A7C-B1F2-3C8E5D6F7A9B}'
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%/Discrakt'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/afonsojramos/discrakt/releases/download/v4.1.2/Discrakt_4.1.2_win64.msi
  InstallerSha256: 7AFF8860E222CC9AA3C99DD411CB81F29364E0526F9FEB2210C6CCED58AED854
ManifestType: installer
ManifestVersion: 1.12.0
