# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: DFNetResearch.DFexplore
PackageVersion: 5.11.2
InstallerType: msi
UpgradeBehavior: install
ProductCode: '{6E14A4A3-2811-40A6-AFEA-B7C6BDDDDD8A}'
ReleaseDate: 2026-09-28
AppsAndFeaturesEntries:
- UpgradeCode: '{DAAC27F5-CF25-4F9C-BA1F-998B916E1625}'
Installers:
- Architecture: x64
  InstallerUrl: https://www.dfnetresearch.com/wp-content/uploads/dfdiscover/5.11.2apps/DFexplore_5_11_2.msi
  InstallerSha256: 542E804AB4646F4C6E0F20B1AE42F88967CA4C3C8FA06A6EC535A2D56D01A9D2
ManifestType: installer
ManifestVersion: 1.12.0
