# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Datronicsoft.SpacedeskDriver.Server
PackageVersion: 2.2.33.0
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Custom: REBOOT=ReallySuppress
UpgradeBehavior: install
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://downloads.spacedesk.net/downloads/spacedesk_driver_Win_10_32_v2233.msi
  InstallerSha256: 1D8C1570E7AA1BF21AC43C5FCDE1BED767DECAC2B4BD2C63794860B2EF08D0A6
  ProductCode: '{38564602-F27E-4DA1-B1C3-C28D778A381A}'
  AppsAndFeaturesEntries:
  - ProductCode: '{38564602-F27E-4DA1-B1C3-C28D778A381A}'
    UpgradeCode: '{960B967D-8BE1-46CF-9BCB-1C57E489E1A9}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles(x86)%\datronicsoft'
- Architecture: x64
  InstallerUrl: https://downloads.spacedesk.net/downloads/spacedesk_driver_Win_11_64_v2233.msi
  InstallerSha256: B43025D0E53777DD67D1D2C4B5AB470EF5BCDC9B757FE753B97D55A7A315886B
  ProductCode: '{9FF2302B-077C-4E55-82C6-0B40250A5684}'
  AppsAndFeaturesEntries:
  - ProductCode: '{9FF2302B-077C-4E55-82C6-0B40250A5684}'
    UpgradeCode: '{3CBC4D7B-B6A4-4107-BB9E-66EDFF3909B0}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\datronicsoft'
- Architecture: arm64
  InstallerUrl: https://downloads.spacedesk.net/downloads/spacedesk_driver_Win_11_ARM64_v2233.msi
  InstallerSha256: 5D11387D3227D5D15B836ED232CB2F09C5FEF7B937C29F8A87B2AB7B2A6E41B6
  ProductCode: '{9FF2302B-077C-4E55-82C6-0B40250A5684}'
  AppsAndFeaturesEntries:
  - ProductCode: '{9FF2302B-077C-4E55-82C6-0B40250A5684}'
    UpgradeCode: '{3CBC4D7B-B6A4-4107-BB9E-66EDFF3909B0}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\datronicsoft'
ManifestType: installer
ManifestVersion: 1.12.0
