# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: OlegShparber.Zeal
PackageVersion: 0.9.1
ReleaseDate: 2026-07-28
InstallerType: wix
Scope: machine
ElevationRequirement: elevatesSelf
InstallerSwitches:
  InstallLocation: INSTALL_ROOT="<INSTALLPATH>"
UpgradeBehavior: install
AppsAndFeaturesEntries:
- UpgradeCode: '{5C4B6030-A1B4-4EFE-A5AF-28F6FA2E7978}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Zeal'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/zealdocs/zeal/releases/download/v0.9.1/zeal-0.9.1-windows-x64.msi
  InstallerSha256: CC6108100167637E60595C8C7372E2406FF5CB5D3954B40F130121E6D0FD20C9
  ProductCode: '{D54C031B-7EFF-4304-9EA7-A26B5D246EB2}'
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
      MinimumVersion: 14.51.36247.0
- Architecture: arm64
  InstallerUrl: https://github.com/zealdocs/zeal/releases/download/v0.9.1/zeal-0.9.1-windows-arm64.msi
  InstallerSha256: E7FD85F3E0606D2F4DCB671B559691DB13BE6B50CA40606EE815FF6A350A9202
  ProductCode: '{88E08848-70E3-448E-9C58-0057E75D7F5E}'
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
      MinimumVersion: 14.51.36247.0
Protocols:
- dash
- dash-plugin
ManifestType: installer
ManifestVersion: 1.12.0
