# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: AnywhereLabs.DSHDesktop
PackageVersion: 2.0.16
InstallerType: nullsoft
UpgradeBehavior: install
ProductCode: 85820364-4c28-594e-b046-8896b3669248
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/anywhere-labs/dsh-desktop/releases/download/v2.0.16/DSH-Desktop-2.0.16-x64-Setup.exe
  InstallerSha256: 0D330450CBAA9E1B5AC0420E35FF4DB6AFD82D73F4BCC3A9C3E421EF4FE6FA2C
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/anywhere-labs/dsh-desktop/releases/download/v2.0.16/DSH-Desktop-2.0.16-x64-Setup.exe
  InstallerSha256: 0D330450CBAA9E1B5AC0420E35FF4DB6AFD82D73F4BCC3A9C3E421EF4FE6FA2C
  InstallerSwitches:
    Custom: /allusers
ManifestType: installer
ManifestVersion: 1.12.0
