# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: co2lab.Anchors
PackageVersion: 0.1.240
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: anchors.exe
  PortableCommandAlias: anchors
Commands:
- anchors
ReleaseDate: 2026-09-30
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/co2-lab/anchors/releases/download/v0.1.240/anchors_0.1.240_windows_amd64.zip
  InstallerSha256: 37536603E29E7289F252612890B20D91686E67F9F281C7AA71F43A938A9675B6
- Architecture: arm64
  InstallerUrl: https://github.com/co2-lab/anchors/releases/download/v0.1.240/anchors_0.1.240_windows_arm64.zip
  InstallerSha256: 193EC4FFEB2549177EDB1DA675386AF00D58BAD2D1D6AE0971510C6A53F2159B
ManifestType: installer
ManifestVersion: 1.12.0
