# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ptweezy.cronstable
PackageVersion: 1.2.59
InstallerType: burn
Scope: machine
UpgradeBehavior: install
Commands:
- cronstable
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ptweezy/cronstable/releases/download/1.2.59/cronstable-windows-amd64-setup.exe
  InstallerSha256: 3B56B6F7BF5FE7176444BD57C626FE17925DBF7704EF2735D08B5B8B1065E1C3
  ProductCode: '{218F9248-BD55-4BD1-B30C-6FCFB5FBD3ED}'
  AppsAndFeaturesEntries:
  - DisplayName: cronstable
    Publisher: cronstable
    DisplayVersion: 1.2.59
    ProductCode: '{218F9248-BD55-4BD1-B30C-6FCFB5FBD3ED}'
    UpgradeCode: '{E8D4C05B-5ED5-4850-826D-8BA6163E4F8A}'
    InstallerType: burn
  - DisplayName: cronstable
    Publisher: cronstable
    DisplayVersion: 1.2.59
    ProductCode: '{F3613EFB-FE6C-4957-8858-1C715A808267}'
    UpgradeCode: '{B995CBA8-16CD-48F1-A13B-C4C4B927E7BE}'
    InstallerType: msi
- Architecture: arm64
  InstallerUrl: https://github.com/ptweezy/cronstable/releases/download/1.2.59/cronstable-windows-arm64-setup.exe
  InstallerSha256: D5E31211231341A906366027D07C8AC7D57B3027AA4ADCC716E500AC4C5714BE
  ProductCode: '{10AB5D0B-43A3-43F0-B741-4CE80301B6E6}'
  AppsAndFeaturesEntries:
  - DisplayName: cronstable
    Publisher: cronstable
    DisplayVersion: 1.2.59
    ProductCode: '{10AB5D0B-43A3-43F0-B741-4CE80301B6E6}'
    UpgradeCode: '{E8D4C05B-5ED5-4850-826D-8BA6163E4F8A}'
    InstallerType: burn
  - DisplayName: cronstable
    Publisher: cronstable
    DisplayVersion: 1.2.59
    ProductCode: '{C5474AA8-7CC6-4C4B-A673-75E69C045B6F}'
    UpgradeCode: '{B995CBA8-16CD-48F1-A13B-C4C4B927E7BE}'
    InstallerType: msi
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-29
