# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Sourcegraph.Amp
PackageVersion: 0.0.1790625640-gdbe3f3
InstallerType: portable
Commands:
- amp
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://static.ampcode.com/cli/0.0.1790625640-gdbe3f3/amp-windows-x64-baseline.exe
  InstallerSha256: B19710EF37B5BDEBA401178B72D6AFAB10198F95BF48DE773A4453B9A50BC244
ManifestType: installer
ManifestVersion: 1.12.0
