# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Ollama.Ollama.Portable
PackageVersion: 0.35.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: ollama.exe
Commands:
- ollama
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ollama/ollama/releases/download/v0.35.0/ollama-windows-amd64.zip
  InstallerSha256: D6F7D3DD4F5D013553A78C1E78B2521FCF41D43DD2863E4596CDC046FE6036DB
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  InstallerUrl: https://github.com/ollama/ollama/releases/download/v0.35.0/ollama-windows-arm64.zip
  InstallerSha256: 99D061915A68FB563DA0FB9316FD112CFC6FCE0C9478601B2765B1F973CB715E
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.12.0
