# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.te
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox ESR
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win32/te/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: E601F2AA5B55A2994A4FBEDF6CCF9801C192CCA25A15BB7497D749A68853CE15
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64/te/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: A68222B3E78D63BF515A58EFACE54320B72CBC5D7ECD5F70DB5A980DC8991492
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64-aarch64/te/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: D88AFFB5FA2B5D5D9C63714874062C980F4BFBFBD293F94827395FF921CE917F
ManifestType: installer
ManifestVersion: 1.12.0
