# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: CoralCreek.SQLiteExpert.Personal
PackageVersion: 6.2.3.737
InstallerType: inno
Scope: machine
ReleaseDate: 2026-09-26
Installers:
- Architecture: x86
  InstallerUrl: https://www.sqliteexpert.com/v6/SQLiteExpertPersSetup32.exe
  InstallerSha256: AE1DAD077389B5B6554B4492CCAC7C6018C0307034EE0B9CA573D9F719426F8B
  ProductCode: SQLite Expert Personal 6 - 32bit_is1
- Architecture: x64
  InstallerUrl: https://www.sqliteexpert.com/v6/SQLiteExpertPersSetup64.exe
  InstallerSha256: 0A4CCEA8C6824B670949393221E2ADAD026442ABA8C1E00A2196CD8599D049CF
  ProductCode: SQLite Expert Personal 6 - 64bit_is1
ManifestType: installer
ManifestVersion: 1.12.0
