# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Brave.Brave.Nightly
PackageVersion: 155.1.98.40
InstallerType: exe
ExpectedReturnCodes:
- InstallerReturnCode: -2147219440
  ReturnResponse: cancelledByUser
- InstallerReturnCode: -2147219416
  ReturnResponse: alreadyInstalled
- InstallerReturnCode: -2147218431
  ReturnResponse: invalidParameter
- InstallerReturnCode: -2147024809
  ReturnResponse: invalidParameter
UpgradeBehavior: install
Protocols:
- ftp
- http
- https
- mailto
- tel
FileExtensions:
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: BraveSoftware Brave-Browser
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.98.40/BraveBrowserStandaloneSilentNightlySetup32.exe
  InstallerSha256: 27C35D73C397B954C7B6CFF31EBEBBDF93B2B3BFC6C47EA9E4429021078F0BA6
  InstallModes:
  - silent
- Architecture: x86
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.98.40/BraveBrowserStandaloneNightlySetup32.exe
  InstallerSha256: EF86193ADD7121AAC2BBD8583C4554D20630C21ECBD9B3470DDB9C016B3C626E
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.98.40/BraveBrowserStandaloneSilentNightlySetup.exe
  InstallerSha256: 3A70D63118E003659936C9349B2A8F9CEA08483230B2A26BECD6D5E9F826C972
  InstallModes:
  - silent
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.98.40/BraveBrowserStandaloneNightlySetup.exe
  InstallerSha256: DEEF5CD14DB04E5AE3FB5AEC83110AFE4AF676FECA55320209D894B557438C7A
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.98.40/BraveBrowserStandaloneSilentNightlySetupArm64.exe
  InstallerSha256: 68B3202E5E17947A1B5627F4642B11B89952D79B4C29FBE833371CA754FD74D2
  InstallModes:
  - silent
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.98.40/BraveBrowserStandaloneNightlySetupArm64.exe
  InstallerSha256: DA94D96C575AA238342186AC62E20DE8D7183F2D014FCEEF7E29FB5F616E82E7
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
ManifestType: installer
ManifestVersion: 1.12.0
