# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Loko.OnyxCode
PackageVersion: 2.3.0
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
AppsAndFeaturesEntries:
- ProductCode: '{CC6B787D-37A0-49E8-AE24-8559A032BE0C}_is1'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/onyxcode-app/onyxcode-releases/releases/download/v2.3.0/OnyxCode-win32-x64-winget.exe
  InstallerSha256: 7FA1A02002E4AB2EC033D0123F66A045A6203710BB1B4B3413D91E4B0338EE5E
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-27
