# Automatically updated by the winget bot at 2026/Sep/30
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: ComfortSoftwareGroup.ComfortOSK
PackageVersion: 10.0.0.0
InstallerLocale: en-US
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{6EB17721-6249-417B-99B9-DAF3FD532955}_is1'
ReleaseDate: 2022-05-17
AppsAndFeaturesEntries:
- ProductCode: '{6EB17721-6249-417B-99B9-DAF3FD532955}_is1'
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\ComfortKeyboard'
Installers:
- Architecture: x86
  InstallerUrl: https://www.comfortsoftware.com/download/ComfortOSKSetup.exe
  InstallerSha256: 2CD96F9105ED46C42222BE3D32F037BD6E3D49EBC7AD88A1670929B4878E6DD5
ManifestType: installer
ManifestVersion: 1.28.0
