# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.kk
PackageVersion: "157.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win32/kk/Firefox%20Setup%20157.0.exe
  InstallerSha256: 30E92EAFF3A85A6BEBC02B450114244BDE591E38C1DA632B73B98CD3956F1D1D
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64/kk/Firefox%20Setup%20157.0.exe
  InstallerSha256: B8D3050C678369660659BD8A4E2A7F4C0663D1D468CDA694591442D388757A67
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64-aarch64/kk/Firefox%20Setup%20157.0.exe
  InstallerSha256: 2020DB6F3812B3E893BD18AF736DBF51522D4EF4D95C9F798DD73F17C4916039
ManifestType: installer
ManifestVersion: 1.12.0
