# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Google.Chrome.Canary
PackageVersion: 156.0.8077.0
InstallerType: exe
Scope: user
InstallModes:
- silent
InstallerSwitches:
  Log: --verbose-logging --log-file="<LOGPATH>"
  Custom: --chrome-sxs --do-not-launch-chrome
ExpectedReturnCodes:
- InstallerReturnCode: 60
  ReturnResponse: installInProgress
- InstallerReturnCode: 22
  ReturnResponse: cancelledByUser
- InstallerReturnCode: 4
  ReturnResponse: downgrade
- InstallerReturnCode: 3
  ReturnResponse: alreadyInstalled
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
- tel
FileExtensions:
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Google Chrome
ReleaseDate: 2026-09-28
Installers:
- Architecture: x86
  InstallerUrl: https://dl.google.com/release2/chrome/bap2drtvy7uiuxei3f6plb662m_156.0.8077.0/156.0.8077.0_chrome_installer_uncompressed.exe
  InstallerSha256: 232B2B6599B913A847E49B23E94045F2D53A26C67005ED8487ADFAE5F47D3776
- Architecture: x64
  InstallerUrl: https://dl.google.com/release2/chrome/hprknmrmr4ctqdr7eqe25vrd6y_156.0.8077.0/156.0.8077.0_chrome_installer_uncompressed.exe
  InstallerSha256: B7978EEE45F110C9342FDCB75CD7C33E60B5C73556104D53B742FD5964FAB9B7
- Architecture: arm64
  InstallerUrl: https://dl.google.com/release2/chrome/acszdkob4ctlpucfqbme2irvyqsq_156.0.8077.0/156.0.8077.0_chrome_installer_uncompressed.exe
  InstallerSha256: DFF75CE34538DC04D011F5A0D6E7653C720694FA8C1C9F85B6BA6CB6E006F95E
ManifestType: installer
ManifestVersion: 1.12.0
