# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Microsoft.SafetyScanner
PackageVersion: 1.459.426.0
InstallerType: portable
Commands:
- safetyscanner
ReleaseDate: 2026-09-27
Installers:
- Architecture: x86
  InstallerUrl: https://definitionupdates.microsoft.com/packages/content/msert.exe?packageType=Scanner&packageVersion=1.459.426.0&arch=x86
  InstallerSha256: 46B4F4E8104E2C1E1E013A0FA7173FC6CA0DA9099F5BAB7B5EE7EE89571C44EE
- Architecture: x64
  InstallerUrl: https://definitionupdates.microsoft.com/packages/content/msert.exe?packageType=Scanner&packageVersion=1.459.426.0&arch=amd64
  InstallerSha256: 4370DCFE579838206D43AF2DC2480E46EC7E6A3841E8522B73F9D2C1FEA3410E
ManifestType: installer
ManifestVersion: 1.12.0
