# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Ethereum.geth
PackageVersion: 1.17.7
InstallerType: nullsoft
Scope: machine
ProductCode: Ethereum Geth
ReleaseDate: 2026-09-30
AppsAndFeaturesEntries:
- DisplayName: Ethereum - Geth - Official Go implementation of the Ethereum protocol
  DisplayVersion: 1.17.7-3d858f85
  ProductCode: Ethereum Geth
Installers:
- Architecture: x64
  InstallerUrl: https://gethstore.blob.core.windows.net/builds/geth-windows-amd64-1.17.7-3d858f85.exe
  InstallerSha256: F05578E03BE28768F37D07819D648A952BAD1FD47B0D24E3FAD813D4578AF80F
ManifestType: installer
ManifestVersion: 1.28.0
