# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: openwong2kim.wmux
PackageVersion: 3.62.1
Platform:
- Windows.Desktop
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
ProductCode: wmux
ReleaseDate: 2026-09-27
AppsAndFeaturesEntries:
- ProductCode: wmux
InstallationMetadata:
  DefaultInstallLocation: "%LocalAppData%\\wmux"
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/openwong2kim/wmux/releases/download/v3.62.1/wmux-3.62.1.Setup.exe
  InstallerSha256: CDC7088FB7ABDABCDD968761968E3B8890C08E95C168029D7D60F641D8EBBAF9
ManifestType: installer
ManifestVersion: 1.12.0
