# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.hu
PackageVersion: "157.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win32/hu/Firefox%20Setup%20157.0.exe
  InstallerSha256: D0A617A600E44E330475E832541F8648906471BA3283009B80AAA631BB284D6A
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64/hu/Firefox%20Setup%20157.0.exe
  InstallerSha256: ACDE340D8885A3FDBF9AB28CFE62C91880AFD38B2576E9AE3B7F34FEE5AAAC6B
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64-aarch64/hu/Firefox%20Setup%20157.0.exe
  InstallerSha256: AEAE7064285046933B6D2325902F2DC02E93764979369FF03BE1AABA82E592B0
ManifestType: installer
ManifestVersion: 1.12.0
