# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: NewRelic.InfrastructureAgent
PackageVersion: 1.80.5
InstallerType: wix
Scope: machine
ProductCode: '{4FDC7898-E2E5-4A8B-89D4-7F9E3B4432E4}'
ReleaseDate: 2026-09-24
AppsAndFeaturesEntries:
- UpgradeCode: '{527B3F06-B23D-426A-9999-C77506EE6B28}'
Installers:
- Architecture: x64
  InstallerUrl: https://download.newrelic.com/infrastructure_agent/windows/newrelic-infra.1.80.5.msi
  InstallerSha256: 199498DB94779B4273663BC1A3FD32BFD859859A9A672490CD9AA7A738B9D12C
ManifestType: installer
ManifestVersion: 1.12.0
