# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.es-MX
PackageVersion: "157.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win32/es-MX/Firefox%20Setup%20157.0.exe
  InstallerSha256: 37AB8271B2845A7999E757E3633C9563BE9AF4F0A87393DD141172F2B4119CED
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64/es-MX/Firefox%20Setup%20157.0.exe
  InstallerSha256: 460586EE5D2B29C20813E301BEF94C87847092C56BEF9A65AFF19E76C0C2350F
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64-aarch64/es-MX/Firefox%20Setup%20157.0.exe
  InstallerSha256: 1828DCAA399D41AB0B5C69ED255F3DF0937C397C51C244CA770B322A3FD8E43B
ManifestType: installer
ManifestVersion: 1.12.0
