# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: NirSoft.GUIPropView
PackageVersion: "1.34"
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: GUIPropView.exe
  PortableCommandAlias: GUIPropView
Installers:
- Architecture: x86
  InstallerUrl: https://www.nirsoft.net/utils/guipropview.zip
  InstallerSha256: 51CC61BD2955A4AE19FEFF6F7E42F9885096046F1BAF238BF3E6C35F2A32A826
- Architecture: x64
  InstallerUrl: https://www.nirsoft.net/utils/guipropview-x64.zip
  InstallerSha256: F0D395DB719DD56EE519AA51BA99EF501A7BB847510ABAB9BEA12D67180D48EF
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-29
