# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.el
PackageVersion: "157.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win32/el/Firefox%20Setup%20157.0.exe
  InstallerSha256: 95191891131A9D5DBC8CECE9A32A475769F585C84D35DAD8AA8BB7B9F6077329
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64/el/Firefox%20Setup%20157.0.exe
  InstallerSha256: 55B042C4D770265B309DE25C7FDA95476B9DE650D98EBEB6C8AE31AD422EC5C9
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64-aarch64/el/Firefox%20Setup%20157.0.exe
  InstallerSha256: 35D28A66C31657AB7B466E82A16015A61834D57AC847A6FD66C78875158958C5
ManifestType: installer
ManifestVersion: 1.12.0
