# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ach
PackageVersion: "157.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win32/ach/Firefox%20Setup%20157.0.exe
  InstallerSha256: 1FA5F1F466D36ACF984859B0F7CEEFEBA8CC59201ED1116662E99E920F94F195
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64/ach/Firefox%20Setup%20157.0.exe
  InstallerSha256: 3B4BD5D578FDBBFD2A0BF29579580FC8B2A16F4786A5129A49BFB575BF9F878C
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64-aarch64/ach/Firefox%20Setup%20157.0.exe
  InstallerSha256: F0DACA6D978DC6CBA297533F1AE8DFC19B16634BA24112518F0374CA3C4AEA2C
ManifestType: installer
ManifestVersion: 1.12.0
