# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.be
PackageVersion: "157.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win32/be/Firefox%20Setup%20157.0.exe
  InstallerSha256: 1FDFC2076B7D6F10EB835F0AD56E7DA7CD8001A5F99D7B044829C7C3F14F6570
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64/be/Firefox%20Setup%20157.0.exe
  InstallerSha256: 08AA9AD9C3F4FFBF140F5BCD2A9A2E06EBF6159B02A2D505836EF6F788B3EF54
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64-aarch64/be/Firefox%20Setup%20157.0.exe
  InstallerSha256: D10A369D01BE33D582C69C39DB78543C6863C51A79E816F926B9F5681B81152E
ManifestType: installer
ManifestVersion: 1.12.0
