# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: WXRIW.Lyricify
PackageVersion: 4.4.0
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /exenoui /quiet /norestart
  SilentWithProgress: /exenoui /passive /norestart
  InstallLocation: APPDIR="<INSTALLPATH>"
  Log: /log "<LOGPATH>"
ExpectedReturnCodes:
- InstallerReturnCode: 3010
  ReturnResponse: rebootRequiredToFinish
- InstallerReturnCode: 1654
  ReturnResponse: systemNotSupported
- InstallerReturnCode: 1650
  ReturnResponse: invalidParameter
- InstallerReturnCode: 1649
  ReturnResponse: blockedByPolicy
- InstallerReturnCode: 1644
  ReturnResponse: blockedByPolicy
- InstallerReturnCode: 1643
  ReturnResponse: blockedByPolicy
- InstallerReturnCode: 1640
  ReturnResponse: blockedByPolicy
- InstallerReturnCode: 1641
  ReturnResponse: rebootInitiated
- InstallerReturnCode: 1639
  ReturnResponse: invalidParameter
- InstallerReturnCode: 1638
  ReturnResponse: alreadyInstalled
- InstallerReturnCode: 1633
  ReturnResponse: systemNotSupported
- InstallerReturnCode: 1628
  ReturnResponse: invalidParameter
- InstallerReturnCode: 1625
  ReturnResponse: blockedByPolicy
- InstallerReturnCode: 1623
  ReturnResponse: systemNotSupported
- InstallerReturnCode: 1618
  ReturnResponse: installInProgress
- InstallerReturnCode: 1602
  ReturnResponse: cancelledByUser
- InstallerReturnCode: 1601
  ReturnResponse: contactSupport
- InstallerReturnCode: 87
  ReturnResponse: invalidParameter
- InstallerReturnCode: 1
  ReturnResponse: invalidParameter
- InstallerReturnCode: -1
  ReturnResponse: cancelledByUser
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.6
ReleaseDate: 2026-09-29
AppsAndFeaturesEntries:
- UpgradeCode: '{CA8FC4DE-6BEC-4C25-BD21-AD316980A6EF}'
  InstallerType: msi
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/WXRIW/Lyricify-App/releases/download/v4.4.0/Lyricify.Setup.Ver.4.4.0.260928-release.x86.exe
  InstallerSha256: 0128E740B150224BDEB74BD05ACB10788728E0E506B67D971DC5F0830D33AE13
  ProductCode: '{57D6663D-3BEF-45BE-BD4F-8980C647B6A8}'
- Architecture: x64
  InstallerUrl: https://github.com/WXRIW/Lyricify-App/releases/download/v4.4.0/Lyricify.Setup.Ver.4.4.0.260928-release.x64.exe
  InstallerSha256: 616E3FA9CB781254081C2B4558CD3270130E6425EA92E6DA6E18A79CCB2A40AB
  ProductCode: '{17BC9A9C-EC64-481F-9692-DF7DE64EAE64}'
- Architecture: arm64
  InstallerUrl: https://github.com/WXRIW/Lyricify-App/releases/download/v4.4.0/Lyricify.Setup.Ver.4.4.0.260928-release.Arm64.exe
  InstallerSha256: 3AC7E911BFB8AE051C1A1C5515985BA8E71ECFAADA3D487AB908C98EF393D544
  ProductCode: '{4FC7AA6B-16C1-4721-9339-99020AFCFD82}'
ManifestType: installer
ManifestVersion: 1.12.0
