# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.fa
PackageVersion: "157.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win32/fa/Firefox%20Setup%20157.0.exe
  InstallerSha256: BCE05165ED26968FC62C0A03713D88D1DFBDC991639752A1519B6E2AAF3625E4
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64/fa/Firefox%20Setup%20157.0.exe
  InstallerSha256: E88C6E81C74CD89FEBB8B778CAE097639A27DF44D2748BFD169CF6F0AFBA7ABB
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64-aarch64/fa/Firefox%20Setup%20157.0.exe
  InstallerSha256: 8E860A9C938025E7130F03B193F8D648D3CA6AF53D409814F24E3BC91D987EA7
ManifestType: installer
ManifestVersion: 1.12.0
