# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: co2lab.Anchors
PackageVersion: 0.1.200
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: anchors.exe
  PortableCommandAlias: anchors
Commands:
- anchors
ReleaseDate: 2026-09-26
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/co2-lab/anchors/releases/download/v0.1.200/anchors_0.1.200_windows_amd64.zip
  InstallerSha256: 83995C746F2F6A9BB1F5F1F2191EFBC12C22A617294A2854D325638A2F76078C
- Architecture: arm64
  InstallerUrl: https://github.com/co2-lab/anchors/releases/download/v0.1.200/anchors_0.1.200_windows_arm64.zip
  InstallerSha256: 51A17FF0D8E29FE9ECDB277A6BC32B6D8E530953BD2B7A2AB10AF7C18DBFEC0F
ManifestType: installer
ManifestVersion: 1.12.0
