# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.da
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox ESR
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win32/da/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 616E7D8DDCE944B7280140BAA67735882D0495C0123FDDAC9DBBFFCD61663C9D
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64/da/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: DD3BF473DF19A83D0E2FF7A3D2FEAC3F488604322A78FEB533AE64752810A16C
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64-aarch64/da/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 1CA4F3E94EFDB96571A3F702B3B1AF3009780617A1C2A14F3A8B59B800673E35
ManifestType: installer
ManifestVersion: 1.12.0
