# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ByteDance.Doubao
PackageVersion: 2.31.4
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: --command=quiet_install
  SilentWithProgress: --command=quiet_install
  InstallLocation: --target_dir="<INSTALLPATH>"
  Log: --log_dir="<LOGPATH>"
UpgradeBehavior: install
ProductCode: Doubao
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  InstallerUrl: https://lf-flow-web-cdn.doubao.com/obj/flow-doubao/doubao_pc/2.31.4/Doubao_installer_2.31.4.exe
  InstallerSha256: C76408E2AD92DC451D11200D6684209D831E2CAD01D15F3F5747925CA223963A
- Architecture: arm64
  InstallerUrl: https://lf-flow-web-cdn.doubao.com/obj/flow-doubao/doubao_pc/2.31.4/Doubao_Arm64_installer_2.31.4.exe
  InstallerSha256: 44270A6267CD06B36FB923977E97AEF5D452CFB5F72962740AA314F44C3C6916
ManifestType: installer
ManifestVersion: 1.12.0
