# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: seerge.g-helper
PackageVersion: "0.285"
InstallerLocale: en-US
InstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: GHelper.exe
  PortableCommandAlias: GHelper
Commands:
- ghelper
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.10
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/seerge/g-helper/releases/download/v0.285/GHelper.exe
  InstallerSha256: AB114A45D2F96C10596628133A16EB04293145C6C5E8BAF387021283A075C595
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-26
