# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: FlowDevs.PrimeDictate
PackageVersion: 6.0.0
InstallerType: wix
Scope: machine
InstallerSwitches:
  Custom: LAUNCHATLOGIN=0
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/flowdevs-io/PrimeDictate/releases/download/v6.0.0/PrimeDictate-Setup-v6.0.0-x64.msi
  InstallerSha256: 2C1E5E57BD0998346D0AF407270C1B0AC186645866CD8D20B8259273123D2235
  ProductCode: " {99E7827A-5F3F-43E1-A0BF-14A1C26A12D6}"
- Architecture: arm64
  InstallerUrl: https://github.com/flowdevs-io/PrimeDictate/releases/download/v6.0.0/PrimeDictate-Setup-v6.0.0-arm64.msi
  InstallerSha256: 330C3FBAF6CDD252B97739C03799D06F5414F6DACFE2783E5DA7C71926576BF8
  ProductCode: " {9A801FDF-7A9C-43F0-A5EE-A5C3D524C244}"
ManifestType: installer
ManifestVersion: 1.10.0
