# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: Infracost.Infracost
PackageVersion: 0.10.46
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: infracost.exe
Commands:
- infracost
ReleaseDate: 2026-09-25
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/infracost/infracost/releases/download/v0.10.46/infracost-windows-amd64.zip
  InstallerSha256: 3A7A59266C5A44D22F5F0A55FBAE1C708FDBBE6B34A2C1557035F7AA528AA21D
- Architecture: arm64
  InstallerUrl: https://github.com/infracost/infracost/releases/download/v0.10.46/infracost-windows-arm64.zip
  InstallerSha256: E71D17F7E58F6B4CFEFAB1EA4B9857103964F4B18BC2CD6538BC044E666B89C2
ManifestType: installer
ManifestVersion: 1.12.0
