# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Microsoft.SafetyScanner
PackageVersion: 1.459.477.0
InstallerType: portable
Commands:
- safetyscanner
ReleaseDate: 2026-09-30
Installers:
- Architecture: x86
  InstallerUrl: https://definitionupdates.microsoft.com/packages/content/msert.exe?packageType=Scanner&packageVersion=1.459.477.0&arch=x86
  InstallerSha256: 288838663D853EA4A0D822677F309B19CABF1A4CB71DB6D7F6CBDD9BA501557F
- Architecture: x64
  InstallerUrl: https://definitionupdates.microsoft.com/packages/content/msert.exe?packageType=Scanner&packageVersion=1.459.477.0&arch=amd64
  InstallerSha256: B74C5B79420C7AC8EFC332B2FCE9F73B6548857FCFC24F3F1198DC36B3CD1F93
ManifestType: installer
ManifestVersion: 1.28.0
