# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: JitzuLang.Jitzu
PackageVersion: 0.1.48
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: jz.exe
  PortableCommandAlias: jz
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/jitzulang/Jitzu/releases/download/v0.1.48/jitzu-0.1.48-win-x64.zip
  InstallerSha256: 16665DE6534924B54742822712F136DC32A8455EC17300BB8D82706A1AE7E01C
ManifestType: installer
ManifestVersion: 1.12.0
