# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: sysmanage.sysmanage
PackageVersion: 3.9.0.16
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-09-27
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/bceverly/sysmanage/releases/download/v3.9.0.16/sysmanage-3.9.0.16-windows-x64.msi
  InstallerSha256: D9E19F1E039D237C48BBFA2CC68B72FEC804CC5596762E3B3E232E3191E4A09A
  ProductCode: '{FD44843E-5A22-411B-80C5-FE3A82905543}'
  AppsAndFeaturesEntries:
  - ProductCode: '{FD44843E-5A22-411B-80C5-FE3A82905543}'
    UpgradeCode: '{F1E2D3C4-B5A6-4D7C-9E8F-1A2B3C4D5E6F}'
- Architecture: arm64
  InstallerUrl: https://github.com/bceverly/sysmanage/releases/download/v3.9.0.16/sysmanage-3.9.0.16-windows-arm64.msi
  InstallerSha256: 49576215D38FAF6E0B1D2937A0B05B8A37A451462E5528F0248C08FB87CE1F4D
  ProductCode: '{AD4CBA65-C5DA-4E43-8134-4F986306F0CC}'
  AppsAndFeaturesEntries:
  - ProductCode: '{AD4CBA65-C5DA-4E43-8134-4F986306F0CC}'
    UpgradeCode: '{F1E2D3C4-B5A6-4D7C-9E8F-1A2B3C4D5E6F}'
ManifestType: installer
ManifestVersion: 1.12.0
