# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Sourcegraph.Amp
PackageVersion: 0.0.1790452833-gea4e33
InstallerType: portable
Commands:
- amp
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ReleaseDate: 2026-09-26
Installers:
- Architecture: x64
  InstallerUrl: https://static.ampcode.com/cli/0.0.1790452833-gea4e33/amp-windows-x64-baseline.exe
  InstallerSha256: F353187EB57368D8F7BE52FC087A2EB96D49C41CB069C5F7141E847C92EAA510
ManifestType: installer
ManifestVersion: 1.12.0
