# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: laurentiu021.SysManager
PackageVersion: 1.114.42
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: portable
Commands:
- SysManager
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/laurentiu021/SystemManager/releases/download/v1.114.42/SysManager-v1.114.42.exe
  InstallerSha256: 268F9605AAD127BE5D37BCF2D1F2495FF4AE3FBE9AB2B10F3407B9CB96F26F2D
ManifestType: installer
ManifestVersion: 1.12.0
