# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: KDE.Klines
PackageVersion: master
InstallerType: nullsoft
UpgradeBehavior: install
ProductCode: klines
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://cdn.kde.org/ci-builds/games/klines/master/windows/klines-master-926-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: 45AAC41C0B193CC29709B64ADDDB7DEA2556CC4156F02AF28015349C2BD35015
  InstallerSwitches:
    Custom: /CurrentUser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://cdn.kde.org/ci-builds/games/klines/master/windows/klines-master-926-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: 45AAC41C0B193CC29709B64ADDDB7DEA2556CC4156F02AF28015349C2BD35015
  InstallerSwitches:
    Custom: /AllUsers
ManifestType: installer
ManifestVersion: 1.12.0
