# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: ForgeLabsSoft.DriveForge
PackageVersion: 4.3.3
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: portable
Commands:
- driveforge
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ForgeLabsSoft/driveforge/releases/download/v4.3.3/DriveForge.exe
  InstallerSha256: 95D568EA35E613C2FD8E47326C8FA3415BD9AFDC492D65234FEA55F3DD8F923A
ManifestType: installer
ManifestVersion: 1.12.0
