# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.ta
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox ESR
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win32/ta/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 614F026FFB6CF5723ED0337D390690878672C35E7813E6536A1E676092FD87DB
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64/ta/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 12F6CC3E48A3541DCBB0CED25DED327D63E1E3C2A00825452356D20CAEAFF5DC
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64-aarch64/ta/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: D939B48FA19BEECD3DA211557901ED98B12412127DD0ECFABD4D60DA10BC37AB
ManifestType: installer
ManifestVersion: 1.12.0
