# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Carbide3D.CarbideCreate
PackageVersion: "8.0"
PackageLocale: en-US
Publisher: Carbide 3D LLC
PublisherUrl: https://carbide3d.com/
PublisherSupportUrl: https://carbide3d.com/hub/
Author: Carbide 3D LLC
PackageName: Carbide Create
PackageUrl: https://carbide3d.com/carbidecreate/
License: Proprietary
LicenseUrl: https://carbide3d.com/policy/eula/
Copyright: © 2026 Carbide 3D, All rights reserved.
CopyrightUrl: https://carbide3d.com/policy/eula/
ShortDescription: CAD/CAM Software for CNC Routers
Description: |-
  Carbide Create is a simple to use yet very powerful CAD/CAM software. It allows you to design, program, and export operations for your CNC with full 3D simulation built in.
  Carbide create uses a context sensitive user interface that only shows you the options that are relevant to your currently selected objects. This means that you are never left with a cluttered interface that has extra options that are not applicable to the task you are trying to perform.
  This also means that you may not see all options available in Carbide Create while navigating through the software at first glance. This is on purpose to allow newcomers to the CAD/CAM hobby to easily complete simple tasks.
  If you are looking for more advanced operations such as boolean tools, vector path grouping, or vector node editing, simply use the shift key to select more than one vector path, or create a vector path, select it, and see what new options appear.
Tags:
- cad
- cam
ReleaseNotes: |-
  - (NEW) Region Builder now has the option to delete the source vectors after crating a region.
  - (NEW) Added "Square Corner" option for the Offset command.
  - (NEW) Node Edit Command: Added "Check Cutter Access" option.  This is flipped from the dedicated command, where the red sections are inaccessable, to keep the view cleaner.  Added option to show vector direction.  Added option to flip the direction of a vector.  Shortcuts are now collapsible.
  - (NEW) Cutter Check command now uses green to show the accessable areas to b more consistent with the Node Edit version.
  - (NEW) Darken up vertical surfaces in 3D rendering to show depths better.
  - (FIX) Fixed how parts of the model are calculated to reduce the chance of overlapping components, like Angled Plane components that share an edge.
  - (FIX) More work to fix the "stale button" problem where some buttons remain in the hover state after the command runs.
  - (FIX) Swap renderer back to perspective mode instead of orthographic.
ReleaseNotesUrl: https://carbide3d.com/carbidecreate/download/
ManifestType: defaultLocale
ManifestVersion: 1.12.0
