# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Carbide3D.CarbideCreate
PackageVersion: "8.0"
InstallerType: inno
Scope: machine
UpgradeBehavior: install
Protocols:
- carbidecreate
FileExtensions:
- c2d
ProductCode: Carbide Create V8_is1
ReleaseDate: 2026-09-24
Installers:
- Architecture: x64
  InstallerUrl: https://carbide-downloads.website-us-east-1.linodeobjects.com/cc/stable/870/CarbideCreate-870.exe
  InstallerSha256: 4794FEB68D5DDD1F2FF27638A072837659C0E3CB1D4AA46763B0B6438106DC60
ManifestType: installer
ManifestVersion: 1.12.0
