# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: CirclebackAI.Circleback
PackageVersion: 2.9.27
InstallerLocale: en-US
InstallerType: nullsoft
InstallModes:
- interactive
- silent
UpgradeBehavior: install
ProductCode: baffa12c-9c44-5c54-938b-0f0bab38132a
ReleaseDate: 2026-09-23
AppsAndFeaturesEntries:
- DisplayName: Circleback 2.9.27
  Publisher: Circleback
  ProductCode: baffa12c-9c44-5c54-938b-0f0bab38132a
Installers:
- Architecture: x64
  InstallerUrl: https://download.circleback.ai/windows/nsis/x64
  InstallerSha256: 95F980BEEADA8756B56B2FEA9B3C6F5A8D633669A18DB463516F5C562467F2FA
ManifestType: installer
ManifestVersion: 1.12.0
