# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.cy
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox ESR
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win32/cy/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: D1E3790D8687F7B16DCA53321C54879C54034084F1188149C5EBA8A434E7D02F
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64/cy/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: BB5EAD20BC98D7F5387A3F98DD4CCEC8252F9D3FB5B0AA85965D3F03E77358E1
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64-aarch64/cy/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 92F1159D661564E4D84C9E8C51616CA94316D3F461F664414C3195AEF8CD9E1F
ManifestType: installer
ManifestVersion: 1.12.0
