# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Microsoft.SafetyScanner
PackageVersion: 1.459.471.0
InstallerType: portable
Commands:
- safetyscanner
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://definitionupdates.microsoft.com/packages/content/msert.exe?packageType=Scanner&packageVersion=1.459.471.0&arch=x86
  InstallerSha256: DC6124DBA43A97990329B72B9BDC973762CC1475ED8E5ED4CCCBD6FAF627B56B
- Architecture: x64
  InstallerUrl: https://definitionupdates.microsoft.com/packages/content/msert.exe?packageType=Scanner&packageVersion=1.459.471.0&arch=amd64
  InstallerSha256: C55A04C6B0B40842DF25982C4BFDA8D135ADE0D716A43D61DC0C4892D57AA024
ManifestType: installer
ManifestVersion: 1.28.0
