# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Stack-Cairn.LiveAgent
PackageVersion: 1.3.7
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/Stack-Cairn/LiveAgent/releases/download/v1.3.7/LiveAgent-v1.3.7-Windows-x64-Setup.exe
  InstallerSha256: 3B9283382BB5939F7DB3CF8B861A53DA595373F5C61492695C8C4D4A9FD6115C
  ProductCode: LiveAgent
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\LiveAgent'
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/Stack-Cairn/LiveAgent/releases/download/v1.3.7/LiveAgent-v1.3.7-Windows-x64.msi
  InstallerSha256: 85D52CEF36F0A572631067F70CD5D812634B93E223BA3281CBB053847146451C
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  ProductCode: '{48C830E2-4AB5-4EE9-BA9E-3743081BD5BC}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{5D56E0D3-9926-5493-A176-8C01F12BA19A}'
ManifestType: installer
ManifestVersion: 1.12.0
