# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: UnslothAI.Unsloth
PackageVersion: 0.1.900-beta
InstallerType: nullsoft
Scope: user
Protocols:
- unsloth
ProductCode: Unsloth Studio (Desktop)
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/unslothai/unsloth/releases/download/v0.1.900-beta/Unsloth-Desktop-Windows.exe
  InstallerSha256: 5BEA8D2CA54B7691EB3B34A33CAD517EE04AD9A0D925F068327B1E18D2D5611B
- Architecture: arm64
  InstallerUrl: https://github.com/unslothai/unsloth/releases/download/v0.1.900-beta/Unsloth-Desktop-Windows-ARM64.exe
  InstallerSha256: 5509A78B762BC5B4B7B1757502056DA96FA4DF0BD5FF5407DC5C6AB69310408F
ManifestType: installer
ManifestVersion: 1.12.0
