# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Excelano.blick
PackageVersion: 0.12.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: blick.exe
  PortableCommandAlias: blick
ReleaseDate: 2026-09-27
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/excelano/blick-cli/releases/download/v0.12.1/blick_0.12.1_windows_amd64.zip
  InstallerSha256: D029F7CEFDAF62A1568AFF74907B598A2C1D49F241FE15F0C9CC68F827A6E2B8
ManifestType: installer
ManifestVersion: 1.12.0
