# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ByteDance.Doudian
PackageVersion: 1.1.12
InstallerType: nullsoft
Scope: machine
ProductCode: 抖店工作台
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  InstallerUrl: https://lf3-cdn-tos.bytescm.com/obj/ecom-dianshang-im/pigeon-client/win-x64/1.1.12/1.0.3421_507190403/doudian_v1.1.12_x64.exe
  InstallerSha256: F2589FB93B5B0158EDD0FA35D4CF2C7E70F383F62E170C0FF7E5DFF52A359FBE
ManifestType: installer
ManifestVersion: 1.12.0
