# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Framer.Framer
PackageVersion: 2026.39.0
InstallerType: exe
Scope: user
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
UpgradeBehavior: install
Protocols:
- framer-app
ProductCode: Framer.Electron
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://updates.framer.com/electron/win32/x64/Framer-2026.39.0.exe
  InstallerSha256: 143A77DDAEACC5140C93B43142293911B918A9581E44BF8D3CC0C7E2F8432E3F
ManifestType: installer
ManifestVersion: 1.12.0
