# Automatically updated by the winget bot at 2026/Sep/28
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: PECB.PECBExams
PackageVersion: 4.2.1
InstallerType: nullsoft
InstallerSwitches:
  Upgrade: --updated
Protocols:
- myapp
ProductCode: 01beb2c1-cd95-5e95-aaf5-11957ca56efa
ReleaseDate: 2026-09-22
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://mypecb-public.s3.us-east-1.amazonaws.com/ExamApp/Windows/PECB%20Exams%20Setup%204.2.1.exe
  InstallerSha256: E4334FE477A6EB8AFE4EC5C06E0B4F643866E1C16FE300026D875099577AE4E8
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://mypecb-public.s3.us-east-1.amazonaws.com/ExamApp/Windows/PECB%20Exams%20Setup%204.2.1.exe
  InstallerSha256: E4334FE477A6EB8AFE4EC5C06E0B4F643866E1C16FE300026D875099577AE4E8
  InstallerSwitches:
    Custom: /allusers
ManifestType: installer
ManifestVersion: 1.28.0
