# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: JohnMacFarlane.Pandoc
PackageVersion: '3.12'
UpgradeBehavior: uninstallPrevious
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  InstallerType: wix
  Scope: user
  InstallerUrl: https://github.com/jgm/pandoc/releases/download/3.12/pandoc-3.12-windows-x86_64.msi
  InstallerSha256: A1342617C3EC4ADB2E005284B566A9FDE5DC20EE67012BBD9694FDDA93FDFD61
  InstallModes:
  - interactive
  - silent
  - silentWithProgress
  InstallerSwitches:
    InstallLocation: APPLICATIONFOLDER="<INSTALLPATH>"
    Custom: ALLUSERS=2
  ProductCode: '{671ADF5A-6B4A-4D75-9EBB-FC09E0A0382F}'
  AppsAndFeaturesEntries:
  - ProductCode: '{671ADF5A-6B4A-4D75-9EBB-FC09E0A0382F}'
    UpgradeCode: '{A68E8EF6-ABB1-4F22-A3C5-68DFDF0AB562}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/Pandoc'
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/jgm/pandoc/releases/download/3.12/pandoc-3.12-windows-x86_64.msi
  InstallerSha256: A1342617C3EC4ADB2E005284B566A9FDE5DC20EE67012BBD9694FDDA93FDFD61
  InstallModes:
  - interactive
  - silent
  - silentWithProgress
  InstallerSwitches:
    InstallLocation: APPLICATIONFOLDER="<INSTALLPATH>"
    Custom: ALLUSERS=1
  ProductCode: '{671ADF5A-6B4A-4D75-9EBB-FC09E0A0382F}'
  AppsAndFeaturesEntries:
  - ProductCode: '{671ADF5A-6B4A-4D75-9EBB-FC09E0A0382F}'
    UpgradeCode: '{A68E8EF6-ABB1-4F22-A3C5-68DFDF0AB562}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/Pandoc'
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: pandoc-3.12/pandoc.exe
  InstallerUrl: https://github.com/jgm/pandoc/releases/download/3.12/pandoc-3.12-windows-x86_64.zip
  InstallerSha256: 2A77EBC2517D13E95056E76B1CD5B574CFE958AC61AA6058117D80C22CA19B79
  ArchiveBinariesDependOnPath: true
ManifestType: installer
ManifestVersion: 1.28.0
