# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: Babashka.Babashka
PackageVersion: 1.13.225
PackageLocale: en-US
Publisher: Babashka
PublisherUrl: https://babashka.org/
PublisherSupportUrl: https://github.com/babashka/babashka/issues
PackageName: Babashka
PackageUrl: https://github.com/babashka/babashka/releases/latest
License: EPL-1.0
LicenseUrl: https://github.com/babashka/babashka/blob/HEAD/LICENSE
ShortDescription: Native, fast starting Clojure interpreter for scripting
Description: Babashka is a native Clojure interpreter for scripting with fast startup. Its main goal is to leverage Clojure in places where you would be using bash otherwise.
Tags:
- babashka
- bash
- clojure
- graalvm
- scripting
- shell-scripting
ReleaseNotes: |-
  ## What's Changed
  • Fix #2170：read handler var metadata in task :cmd trees by @borkdude in https://github.com/babashka/babashka/pull/2171
  • Run BABASHKA_PRELOADS before resolving bb.edn deps by @borkdude in https://github.com/babashka/babashka/pull/2173
  • Allow reify of jline Terminal$SignalHandler by @borkdude in https://github.com/babashka/babashka/pull/2174
  • Bump jline to 4.4.6 by @borkdude in https://github.com/babashka/babashka/pull/2175
  • Wait for :done in nREPL url-connect lib test by @borkdude in https://github.com/babashka/babashka/pull/2176
  • Add jsoup Document$OutputSettings class by @borkdude in https://github.com/babashka/babashka/pull/2177
  • Bump rewrite-clj to 1.3.58 by @borkdude in https://github.com/babashka/babashka/pull/2178


  **Full Changelog**：https://github.com/babashka/babashka/compare/v1.13.224...v1.13.225
ReleaseNotesUrl: https://github.com/babashka/babashka/releases/tag/v1.13.225
ManifestType: defaultLocale
ManifestVersion: 1.12.0
