# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.cak
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox ESR
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win32/cak/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 78627222363BF3524B8B1868E71F9E133AE1198DC8F90E6645B54ABA1CB80617
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64/cak/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 9C6CAA3E644D71F2B698E2BCCA38901EEC43982190B67C3C0C87333F4F2CE54D
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64-aarch64/cak/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 152D01ED0E5116EE3909ACBAB07FA21CD96CAC05355DF0710192F20B3C26CF4B
ManifestType: installer
ManifestVersion: 1.12.0
