# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.an
PackageVersion: "157.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win32/an/Firefox%20Setup%20157.0.exe
  InstallerSha256: 91B89CE48A968EA9F963C5D7D6C33629BE8A0C18CA6AABD80A8FC6A4DEC3088E
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64/an/Firefox%20Setup%20157.0.exe
  InstallerSha256: 39B72302DF14941605CB56F120A36BE759414EB3AFE7B0A485494C9FE5986FF5
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64-aarch64/an/Firefox%20Setup%20157.0.exe
  InstallerSha256: C68669EAFCAEEF4FDAE597A59D7AB5E2AE1EE6B84F980ED5FED2A3B3403CF0EF
ManifestType: installer
ManifestVersion: 1.12.0
