# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: eitsupi.arf
PackageVersion: 0.5.3
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: arf.exe
  PortableCommandAlias: arf
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
FileExtensions:
- R
ReleaseDate: 2026-09-27
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/eitsupi/arf/releases/download/v0.5.3/arf-console-x86_64-pc-windows-msvc.zip
  InstallerSha256: 6F9F7F57D9DC2388E203678F0E17E69EFC9F574C4800AF2A0CAE387ADB311363
- Architecture: arm64
  InstallerUrl: https://github.com/eitsupi/arf/releases/download/v0.5.3/arf-console-aarch64-pc-windows-msvc.zip
  InstallerSha256: 5F41BC4C47E65C84FE48A305CAA07F874C99A0FA01A1B23FFDAE202D9DAEF84E
ManifestType: installer
ManifestVersion: 1.12.0
