# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.my
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox ESR
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win32/my/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 7F9963177661DF7B2E7C2069385F946EDFCCA6485FA57C77239B478F1216282C
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64/my/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 1B0A930759E6FA59DFAB20D6FF833A520B73D19F5CBB4BF74D60263FB7EC081D
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64-aarch64/my/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 6B46957C8BF00156E2DBAF0BD9B2E6C401341F96D0C2A0670B824B50983BA98B
ManifestType: installer
ManifestVersion: 1.12.0
