# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: PrismLauncher.PrismLauncher
PackageVersion: 11.1.1
PackageLocale: en-US
Publisher: Prism Launcher Contributors
PublisherUrl: https://prismlauncher.org/
PublisherSupportUrl: https://github.com/PrismLauncher/PrismLauncher/issues
Author: Prism Launcher Contributors
PackageName: Prism Launcher
PackageUrl: https://github.com/PrismLauncher/PrismLauncher
License: GPL-3.0
LicenseUrl: https://github.com/PrismLauncher/PrismLauncher/blob/HEAD/LICENSE
Copyright: Copyright (C) 2022 Prism Launcher Contributors
ShortDescription: A custom launcher for Minecraft that allows you to easily manage multiple installations of Minecraft at once
Moniker: prismlauncher
Tags:
- fabricmc
- minecraft
- minecraft-launcher
- multimc
- polymc
- prism
- prismlauncher
ReleaseNotes: |-
  We're back!
  This is a hotfix release for a security vulnerability that appeared in 11.1.0. We'll disclose more information about this in the upcoming week. Special thanks to @OpenNerdz for reporting it!
  Changelog
  You can find a full list of changes here: 11.1.0...11.1.1
  Fixed
  - Prevent path traversal in CurseForge modpack overrides by @Trial97 in #6183
ReleaseNotesUrl: https://github.com/PrismLauncher/PrismLauncher/releases/tag/11.1.1
ManifestType: defaultLocale
ManifestVersion: 1.12.0
