# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: dotenvx.dotenvx
PackageVersion: 2.32.0
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: dotenvx.exe
  PortableCommandAlias: dotenvx
UpgradeBehavior: uninstallPrevious
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/dotenvx/dotenvx/releases/download/v2.32.0/dotenvx-2.32.0-windows-x86_64.zip
  InstallerSha256: 60C85CD79A3DE9E002359D1123DD0C599C4B56DAB4C7D0B8AC5D3C2723B502DB
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-29
