# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: KeeperSecurity.KeeperDesktop
PackageVersion: 18.6.4.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.15063.0
InstallerType: msix
UpgradeBehavior: install
Protocols:
- keeper
PackageFamilyName: KeeperSecurityInc.KeeperPasswordManager_zwgt23r867e2p
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download.keepersecurity.com/desktop_electron/packages/KeeperPasswordManager.msixbundle
  InstallerSha256: F5E2E3480AF1B4E6344CC21E516D53EACFC6F912C795282EEB276CD9AC2E5127
  SignatureSha256: D2F1B2B7CAD0FD2AB4ECBDB6F95C79B06CD168D4CBA1E8FF21456959B997C590
- Architecture: x64
  InstallerUrl: https://download.keepersecurity.com/desktop_electron/packages/KeeperPasswordManager.msixbundle
  InstallerSha256: F5E2E3480AF1B4E6344CC21E516D53EACFC6F912C795282EEB276CD9AC2E5127
  SignatureSha256: D2F1B2B7CAD0FD2AB4ECBDB6F95C79B06CD168D4CBA1E8FF21456959B997C590
ManifestType: installer
ManifestVersion: 1.12.0
