# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: PlanetScale.CLI
PackageVersion: 0.339.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: pscale.exe
Commands:
- pscale
ReleaseDate: 2026-09-27
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/planetscale/cli/releases/download/v0.339.0/pscale_0.339.0_windows_386.zip
  InstallerSha256: 46AA5D23F13A92B1E2A9EF124AB6AC5FE982207395CD2A117A780D9F85F3BA7C
- Architecture: x64
  InstallerUrl: https://github.com/planetscale/cli/releases/download/v0.339.0/pscale_0.339.0_windows_amd64.zip
  InstallerSha256: 696AA9735ABF6E25652FBEFED81117901C1C3702EF18A9C8EDE0A60C6D1567F7
- Architecture: arm64
  InstallerUrl: https://github.com/planetscale/cli/releases/download/v0.339.0/pscale_0.339.0_windows_arm64.zip
  InstallerSha256: 95DB91F42448C948CB1C42489B854796237FB5852516C776A0652B34CD0C56E7
ManifestType: installer
ManifestVersion: 1.12.0
