# Automatically updated by the winget bot at 2026/Sep/28
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Regressi.Regressi
PackageVersion: 4.26.9.0
Installers:
- InstallerLocale: fr-FR
  Architecture: neutral
  InstallerType: msi
  InstallerUrl: https://regressi.fr/zip/Regressi.msi
  InstallerSha256: 3829F3B793AA2D552958C5F141E80227E4E9D1631BF24239893F0A4A6551AE48
  ProductCode: '{B45277B1-F3E6-406A-A416-D8426F35F5EC}'
ManifestType: installer
ManifestVersion: 1.28.0
