# Automatically updated by the winget bot at 2026/Sep/27
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: XiaoweiCloud.CalendarTask
PackageVersion: 3.32.308.9365
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
ProductCode: XDiarys
ReleaseDate: 2025-08-01
AppsAndFeaturesEntries:
- DisplayName: CalendarTask
  Publisher: Xiaowei Cloud, Inc.
  ProductCode: XDiarys
Installers:
- Architecture: x86
  InstallerUrl: https://download.xdiarys.com/windows/xdiarys-setup-v3.exe
  InstallerSha256: 26386806D339000E5CF7CAE6775CAAF8DBDEA1CBAAA2ADDE25AFDAB5C049ED8E
ManifestType: installer
ManifestVersion: 1.28.0
