# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: LuisPater.CLIProxyAPI
PackageVersion: 7.3.20
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: cli-proxy-api.exe
Commands:
- cli-proxy-api
ReleaseDate: 2026-09-27
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/router-for-me/CLIProxyAPI/releases/download/v7.3.20/CLIProxyAPI_7.3.20_windows_amd64.zip
  InstallerSha256: F2E240A2C6D0E8AC33BF6B6CB993912B3D8C4129D51F6577B8FC1ADFAF6910A7
ManifestType: installer
ManifestVersion: 1.12.0
