# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: QZYH123.OrbCue
PackageVersion: 0.2.7
InstallerType: nullsoft
Scope: user
ProductCode: OrbCue
ReleaseDate: 2026-09-28
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\OrbCue'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/QZYH123/OrbCue/releases/download/v0.2.7/OrbCue_0.2.7_x64-setup.exe
  InstallerSha256: 55CFD0A9E7B277D7F0EE9C4522C80F336A8A1382C1BCF11FFFC4596144308FD5
ManifestType: installer
ManifestVersion: 1.12.0
