# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.pl
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox ESR
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win32/pl/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: E957BBD5F6EE894C376F3B0D3891EAC06CABF5720C9747D7F22F580544F112B7
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64/pl/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 05235F66590E9E43F1811027A6C84DE7BEDDAF13854129A254F1628EA2DC3EBE
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64-aarch64/pl/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 284A3F211EE2C4B4331661D9189E4A4402BE85A8C773D94261352C0333BD022B
ManifestType: installer
ManifestVersion: 1.12.0
