# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: JanMesarc.GodMan
PackageVersion: 1.4.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: godman.exe
  PortableCommandAlias: godman
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/jame581/GodotManager/releases/download/v1.4.1/godman-windows-x64-1.4.1.zip
  InstallerSha256: FEA07E712DF17FDE4DBF67782B46EED06B7CF289C071B656E4454F2FC17093C9
ManifestType: installer
ManifestVersion: 1.12.0
