# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: MoganLab.Mogan
PackageVersion: 2026.3.7
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
  InstallLocation: --installto "<INSTALLPATH>"
UpgradeBehavior: install
FileExtensions:
- tm
- tp
- ts
ProductCode: Mogan
ReleaseDate: 2026-09-29
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Mogan'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/MoganLab/mogan/releases/download/v2026.3.7/MoganSTEM-v2026.3.7-64bit-installer.exe
  InstallerSha256: 979342E40334E66A56B5365C8C831C0D552B243524A8AD1B84320929648AC67A
ManifestType: installer
ManifestVersion: 1.12.0
