# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.MSIX
PackageVersion: 153.4.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: msix
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
PackageFamilyName: Mozilla.MozillaFirefox_jag0gd4e3s9p2
RestrictedCapabilities:
- runFullTrust
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win32/multi/Firefox%20Setup%20153.4.0esr.msix
  InstallerSha256: 31D6B2A6D922A34512F8449A34DEF5FB9EF6FA2E7501295D27B51CA8CF291E0F
  SignatureSha256: 373242204C9690AE020A17584EB07A8681743FDAA06CCF8CFBCEBAE839BE394B
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\WindowsApps\Mozilla.MozillaFirefox_153.0.0.0_x86__jag0gd4e3s9p2'
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64/multi/Firefox%20Setup%20153.4.0esr.msix
  InstallerSha256: 20EEBE8D118B1B88FD528399133A3860F1B2A28DE3EC4F95EACE4FF221636F39
  SignatureSha256: 5655BFCC169F222FC409ADB2761FD9335B1052F1BC9F43E20DF5CBB311EE538B
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\WindowsApps\Mozilla.MozillaFirefox_153.0.0.0_x64__jag0gd4e3s9p2'
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64-aarch64/multi/Firefox%20Setup%20153.4.0esr.msix
  InstallerSha256: 0C489CC39676AC74E9CAE65B31CD52D27F09A0F304B4A2359F6BEB930482189D
  SignatureSha256: 7AFB2570253B4F21A6BB726607BC20ECD8E015FC84FAF334C5463FFA10A99776
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\WindowsApps\Mozilla.MozillaFirefox_153.0.0.0_arm64__jag0gd4e3s9p2'
ManifestType: installer
ManifestVersion: 1.12.0
