# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: XinTaoFei.Codeg
PackageVersion: 0.32.3
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
ProductCode: codeg
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/xintaofei/codeg/releases/download/v0.32.3/codeg_0.32.3_x64-setup.exe
  InstallerSha256: D6F9C6762AD56D3DC002B3F7A865A2238C44F1B56CA66D69B43115BD45D2A287
- Architecture: arm64
  InstallerUrl: https://github.com/xintaofei/codeg/releases/download/v0.32.3/codeg_0.32.3_arm64-setup.exe
  InstallerSha256: FB1A9167F24962E1362CFA02F9E7CE33258B89168355951B8B539DB6ED828879
ManifestType: installer
ManifestVersion: 1.12.0
