# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Notion.Notion
PackageVersion: 7.36.0
Protocols:
- notion
FileExtensions:
- markdown
- md
- mdown
- mkd
- mkdn
- rmd
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://desktop-release.notion-static.com/Notion%20Setup%207.36.0.exe
  InstallerSha256: 69C61C34493AA690667AE7A7520087355F9E4D430328F21048E30F2F59FB57B6
  InstallerSwitches:
    Upgrade: --updated
  ExpectedReturnCodes:
  - InstallerReturnCode: 2
    ReturnResponse: packageInUse
  UpgradeBehavior: install
  ProductCode: 661f0cc6-343a-59cb-a5e8-8f6324cc6998
- Architecture: arm64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://desktop-release.notion-static.com/Notion%20Setup%207.36.0%20arm64.exe
  InstallerSha256: 668BA4250DD9664C0A78924F5AE82A342431A1F11A06D3AAE57C61AA81754CCE
  InstallerSwitches:
    Upgrade: --updated
  ExpectedReturnCodes:
  - InstallerReturnCode: 2
    ReturnResponse: packageInUse
  UpgradeBehavior: install
  ProductCode: 661f0cc6-343a-59cb-a5e8-8f6324cc6998
- Platform:
  - Windows.Desktop
  MinimumOSVersion: 10.0.19041.0
  Architecture: x64
  InstallerType: msix
  InstallerUrl: https://desktop-release.notion-static.com/Notion-7.36.0.msix
  InstallerSha256: 5B4A016B24D0A6D49DA9494E61CF6112A4F070971565CB013CFB22647BD25920
  SignatureSha256: 1372DE07227F81753600D1252E5CDD690757B8526E934DF0644BA07FE349345A
  PackageFamilyName: com.notion.app.desktop.notion_87smfmv0eebam
  Capabilities:
  - internetClient
  - microphone
  RestrictedCapabilities:
  - packageManagement
  - runFullTrust
  - unvirtualizedResources
- Platform:
  - Windows.Desktop
  MinimumOSVersion: 10.0.19041.0
  Architecture: arm64
  InstallerType: msix
  InstallerUrl: https://desktop-release.notion-static.com/Notion-arm64-7.36.0.msix
  InstallerSha256: A3E7A1F0F2AB8B00039145FFF9C7A2FF3AB637FDA61894C3C14CEEA1A2CE4C6E
  SignatureSha256: 0661E6C5759C8E7EA295E3197678718B2402B6BBEFE1010B5E3FF2C20F5316BB
  PackageFamilyName: com.notion.app.desktop.notion_87smfmv0eebam
  Capabilities:
  - internetClient
  - microphone
  RestrictedCapabilities:
  - packageManagement
  - runFullTrust
  - unvirtualizedResources
ManifestType: installer
ManifestVersion: 1.12.0
