# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Discord.Discord.Canary.arm64
PackageVersion: 1.0.529
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Protocols:
- discord
ProductCode: DiscordCanary
ReleaseDate: 2026-09-29
Installers:
- Architecture: arm64
  InstallerUrl: https://canary.dl2.discordapp.net/distro/app/canary/win/arm64/1.0.529/DiscordCanarySetup.exe
  InstallerSha256: 5C39031AC38C8FA341725DB0C3F68FE810BB540236C7D19F0C00BAE417A12273
ManifestType: installer
ManifestVersion: 1.12.0
