# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Atlassian.ServiceManagementLTS
PackageVersion: 10.3.25
InstallerType: exe
InstallerSwitches:
  Silent: -q
  SilentWithProgress: -q -console
Installers:
- Architecture: x64
  InstallerUrl: https://www.atlassian.com/software/jira/downloads/binary/atlassian-servicedesk-10.3.25-x64.exe
  InstallerSha256: 4E2FFA3787391D43B1EAD3E16F134C80ABA6EDE5F6354DF9508EF03E42C72909
ManifestType: installer
ManifestVersion: 1.12.0
