# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: M-Igashi.mp3rgain
PackageVersion: 3.9.1
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: mp3rgain.exe
ReleaseDate: 2026-09-30
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/M-Igashi/mp3rgain/releases/download/v3.9.1/mp3rgain-v3.9.1-windows-x86_64.zip
    InstallerSha256: 25686CB630A09A04F345AAE747C6E1D56132DCFCE55B0BE5D2D8E78CD74E4701
  - Architecture: arm64
    InstallerUrl: https://github.com/M-Igashi/mp3rgain/releases/download/v3.9.1/mp3rgain-v3.9.1-windows-arm64.zip
    InstallerSha256: 93CCA64B8837BD45F85502757EDCCDF8DB5DA052B0C7EFED16CC307FC05AAD12
ManifestType: installer
ManifestVersion: 1.12.0
