# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: Synology.ActiveProtectAgent
PackageVersion: 2.0.0773
PackageLocale: zh-CN
PublisherUrl: https://www.synology.cn/zh-cn
PublisherSupportUrl: https://www.synology.cn/zh-cn/company/contact_us
PrivacyUrl: https://www.synology.cn/zh-cn/company/legal/privacy
License: 专有软件
LicenseUrl: https://www.synology.cn/zh-cn/company/legal/terms_EULA
Copyright: 版权所有 (c) 2026 Synology lnc. 保留所有权利。
CopyrightUrl: https://www.synology.cn/zh-cn/company/legal/terms_EULA
ShortDescription: 一款旨在简化和增强不同 IT 环境中的数据保护的一体化备份解决方案。
Description: ActiveProtect Manager 是一款一体化备份解决方案，旨在简化和增强不同 IT 环境中的数据保护。要备份 PC、Mac 和物理服务器上的数据，必须先在目标设备上安装 ActiveProtect 代理程序。
Tags:
- nas
- 备份
- 存储
ReleaseNotes: |-
  问题修正
  1. 修正若在两次备份间重新启动执行备份代理程序的 Linux 设备，可能会丢失异动区块追踪信息，进而造成备份数据遗漏的问题。更新至此版本后，代理程序将执行一次完整备份，以确保备份数据的完整性。
ReleaseNotesUrl: https://www.synology.cn/zh-cn/releaseNote/ActiveProtectAgent
ManifestType: locale
ManifestVersion: 1.12.0
