# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ia
PackageVersion: "157.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win32/ia/Firefox%20Setup%20157.0.exe
  InstallerSha256: 027970AF527FC862E3A9C025CC575A57F38D9BF10349BE0B3EC328BE3FEFB16D
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64/ia/Firefox%20Setup%20157.0.exe
  InstallerSha256: 6C77F1299C1E9362D727137EDB6D4D1BC841498593867273C39EA12F428040D3
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64-aarch64/ia/Firefox%20Setup%20157.0.exe
  InstallerSha256: A507D7886FA4F552E0008ABDF91CDA1D5CA6E7C51547D1C9667D608C61FF828A
ManifestType: installer
ManifestVersion: 1.12.0
