# Automatically updated by the winget bot at 2026/Sep/28
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Regressi.Regressi64
PackageVersion: 5.26.9.0
Installers:
- InstallerLocale: fr-FR
  Architecture: neutral
  InstallerType: msi
  InstallerUrl: https://regressi.fr/zip/Regressi64.msi
  InstallerSha256: 425F2A32E6204902E5D3CC96C830E927364D047FAE818B71E1D44DFB26E227F9
  ProductCode: '{80CC3EC2-1F31-4BD4-9AEC-1DD2EAE64A1C}'
ManifestType: installer
ManifestVersion: 1.28.0
