# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Gologin.Gologin
PackageVersion: 4.18.3
InstallerType: nullsoft
UpgradeBehavior: install
ProductCode: e254751a-2537-5636-8393-c4573034c5f6
ReleaseDate: 2026-09-28
AppsAndFeaturesEntries:
- ProductCode: e254751a-2537-5636-8393-c4573034c5f6
Installers:
- Architecture: x64
  InstallerUrl: https://releases.gologin.com/Gologin%20Setup%204.18.3.exe
  InstallerSha256: 44C61566D9F13EF8CA6AEA960CDDDE9323B0600C56FF672F424D67A47B3C9303
ManifestType: installer
ManifestVersion: 1.12.0
