# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: Fly-io.flyctl
PackageVersion: 0.4.109
PackageLocale: en-US
Publisher: Fly.io
PublisherUrl: https://fly.io/
PublisherSupportUrl: https://community.fly.io/
PrivacyUrl: https://fly.io/legal/privacy-policy
PackageName: flyctl
PackageUrl: https://github.com/superfly/flyctl
License: Apache-2.0
LicenseUrl: https://github.com/superfly/flyctl/blob/HEAD/LICENSE
ShortDescription: Command line tools for fly.io services
Tags:
- cli
- fly
- heroku
ReleaseNotes: |-
  ## Changelog
  • 3b3a0588b4915252c355011ad0cec46973ec41bc Bump fly-go to v0.11.2. (#5238)
  • 3ed1acbaae0c786d5210002ad77b642682e88b52 Stop creating dev tags. (#5243)
  • b517d0ea7606f798a02e3b587772177dac3c0668 Delete test tokens after use. (#5241)
  • 15291c2486f178c6bb9ff73e5fa661aa1b23c631 chore(deps)：bump google.golang.org/grpc from 1.83.2 to 1.84.0 (#5235)
  • 2b305cccd7613d8980dc8c17ee3d6788ee960aed chore(deps)：bump github.com/dustin/go-humanize from 1.0.1 to 1.1.0 (#5236)
  • fe73b7215a0ce2ed8e846d927446c1577cbcc217 add support for token-mode wireguard in flyctl agent (#5232)
ReleaseNotesUrl: https://github.com/superfly/flyctl/releases/tag/v0.4.109
ManifestType: defaultLocale
ManifestVersion: 1.12.0
