# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: MSEndpointMgr.1PhoneMirror
PackageVersion: 0.6.1
InstallerLocale: en-US
InstallerType: wix
ProductCode: '{755CA463-DF97-41D6-9E37-A04AF928A67C}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/MSEndpointMgr/1PhoneMirror/releases/download/v0.6.1/1PhoneMirror-0.6.1.msi
  InstallerSha256: F843E7CA6390BB40BF33A80E333B476FCEA57C5E86D25ABD1F63766F98F9C5CB
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-30
