# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: EventHelix.VisualEther
PackageVersion: 9.1.4
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://downloads.eventhelix.com/visualether/9.1.4/VisualEther-9.1.4-x86_64.msi
  InstallerSha256: 815BAC0F9DCBBF6E78B3B396D50116FF2A3BC30CEAA92CCC0A91CDF3C88890B2
  ProductCode: '{BD85CFDA-3766-4E43-9E38-1C19D681103A}'
  AppsAndFeaturesEntries:
  - ProductCode: '{BD85CFDA-3766-4E43-9E38-1C19D681103A}'
    UpgradeCode: '{7A3B8E2F-1C4D-4F6A-9E5B-2D8C7F0A1B3E}'
    InstallerType: wix
ManifestType: installer
ManifestVersion: 1.6.0
