# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ScytheLabs.Reaper
PackageVersion: 2026.9.1
InstallerType: inno
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/scythe-labs/reaper/releases/download/v2026.9.1/Reaper-2026.9.1-windows-x64-setup.exe
  InstallerSha256: 38CCB63AA3AA4A6D25B1E2192D00E8642FEAC0A1E7E3CE60480E626A0274916D
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-29
