# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: TVasilev.RainCleaner
PackageVersion: 2.12.3
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{F5FDF743-0238-4753-98EF-B097ECAE5602}'
ReleaseDate: '2026-09-28'
AppsAndFeaturesEntries:
- DisplayName: Rain Cleaner - Driver Installer, Cleaning and Game Booster
  Publisher: T. Vasilev
  DisplayVersion: 2.12.3
  ProductCode: '{F5FDF743-0238-4753-98EF-B097ECAE5602}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Rain Cleaner'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/raincleaner/RainCleaner/releases/download/v2.12.3/RainCleaner-Setup-2.12.3.msi
  InstallerSha256: F9222386864EC07BC55904AF7385D5648C4DC231D073CA81A361899C94B7B99B
ManifestType: installer
ManifestVersion: 1.12.0
