# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: AllroundAutomations.PLSQLDeveloper
PackageVersion: 17.0.2.2250
InstallerLocale: en-US
InstallerType: msi
Scope: machine
ProductCode: '{733007AE-EAB4-4C1C-914E-D454E55328B9}'
ReleaseDate: 2026-09-22
AppsAndFeaturesEntries:
- DisplayName: PL/SQL Developer 17 (64 bit)
  ProductCode: '{733007AE-EAB4-4C1C-914E-D454E55328B9}'
  UpgradeCode: '{32D1C907-182D-4D80-8F22-4F8D56E62078}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles(x86)%\PLSQL Developer 17\.'
Installers:
- Architecture: x64
  InstallerUrl: https://www.allroundautomations.com/files/plsqldev1702x64.msi
  InstallerSha256: FD7E2609F8D2DA67A82B718F759BEE6C1AFF3968A5A0A68DC3D96942A7629937
ManifestType: installer
ManifestVersion: 1.12.0
