# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: LudoTechnologies.Hiroba
PackageVersion: 0.1.37
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{C2F4DD83-9B1F-4F8D-9C8E-A4EDE1929D9D}'
ReleaseDate: 2026-09-28
AppsAndFeaturesEntries:
- Publisher: hiroba
  ProductCode: '{C2F4DD83-9B1F-4F8D-9C8E-A4EDE1929D9D}'
  UpgradeCode: '{815E00DE-B135-530B-AE43-0F7C815BAA54}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%/Hiroba'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ludo-technologies/hiroba/releases/download/v0.1.37/Hiroba_0.1.37_x64_en-US.msi
  InstallerSha256: 2C3C5E7C94D6BD6CB7C9FB74C2D17294068DAC1AA9076053C91F18045558DCCD
ManifestType: installer
ManifestVersion: 1.12.0
