# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ta
PackageVersion: "157.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win32/ta/Firefox%20Setup%20157.0.exe
  InstallerSha256: 030F03D4BF5C18CE75E4C20ECF95CD7E91B670FE5166DA28BE40993CEB4533E6
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64/ta/Firefox%20Setup%20157.0.exe
  InstallerSha256: 62A236D1CD3E6EB58E8CED2CBC60101D8A158D3A222CEC3D452264FAF556ED86
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64-aarch64/ta/Firefox%20Setup%20157.0.exe
  InstallerSha256: 6F760CA96C284581191B5B4D319B6BD085E6B7B8403E180309B16484E8C276F0
ManifestType: installer
ManifestVersion: 1.12.0
