# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.ast
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox ESR
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win32/ast/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: E3464B876A1178D42D7B1AC5F2BA45ADF0DD5E33B7E8D34DEC299F4B753E622C
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64/ast/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 371EF29A1448F5E29EF9CE4A133953AE4EF0FD7482AEA8170E0B329A2DA3C4BF
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64-aarch64/ast/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 6F6AD690D74D391E7A9220B62A4A502006459093D4F6DE822B5664D75D950B65
ManifestType: installer
ManifestVersion: 1.12.0
