# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Excelano.xsync
PackageVersion: 1.10.2
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: xsync.exe
  PortableCommandAlias: xsync
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/excelano/xfiles/releases/download/v1.10.2/xsync_1.10.2_windows_amd64.zip
  InstallerSha256: F7409CD7FF8DCDC53D69AA105067737213960D0212BBA22A6F1ECB3358C0098F
ManifestType: installer
ManifestVersion: 1.12.0
