# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: NovitasWebWorks.NovaTerm
PackageVersion: 1.4.0
PackageLocale: en-US
Publisher: Novitas Web Works
PublisherUrl: https://github.com/novitaswebworks
PublisherSupportUrl: https://github.com/novitaswebworks/novaterm/issues
PackageName: NovaTerm
PackageUrl: https://github.com/novitaswebworks/novaterm
License: Apache-2.0
LicenseUrl: https://github.com/novitaswebworks/novaterm/blob/HEAD/LICENSE
ShortDescription: A Next-Generation, AI-Native Terminal Workspace
Tags:
- ai-coding
- ai-tools
- ollama
- rust
- tauri
- terminal
ReleaseNotes: See the assets to download this version and install.
ReleaseNotesUrl: https://github.com/novitaswebworks/novaterm/releases/tag/v1.4.0
ManifestType: defaultLocale
ManifestVersion: 1.12.0
