# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ESEngine.ReasonixCLI
PackageVersion: 1.39.3
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: reasonix.exe
Commands:
- reasonix
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/esengine/DeepSeek-Reasonix/releases/download/v1.39.3/reasonix-windows-amd64.zip
  InstallerSha256: 7A828CD578F16D238F978050A09066335A1467263880582D55EB80DDC80FAC2B
- Architecture: arm64
  InstallerUrl: https://github.com/esengine/DeepSeek-Reasonix/releases/download/v1.39.3/reasonix-windows-arm64.zip
  InstallerSha256: CF2F89AA7BE206D1E82B0D0D81867B06890A56151B263419CEB960A095F87C5C
ManifestType: installer
ManifestVersion: 1.12.0
