# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Microsoft.SQLServerManagementStudio.22
PackageVersion: 22.10.2
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: --quiet
  SilentWithProgress: --passive
  InstallLocation: --installPath <INSTALLPATH>
  Upgrade: update
  Custom: --wait --campaign "winget"
ExpectedReturnCodes:
- InstallerReturnCode: 1001
  ReturnResponse: installInProgress
- InstallerReturnCode: 1003
  ReturnResponse: fileInUse
- InstallerReturnCode: 1641
  ReturnResponse: rebootInitiated
- InstallerReturnCode: 3010
  ReturnResponse: rebootRequiredToFinish
- InstallerReturnCode: -1073720687
  ReturnResponse: noNetwork
UpgradeBehavior: install
Commands:
- SSMS
FileExtensions:
- sql
AppsAndFeaturesEntries:
- DisplayVersion: 22.10.2
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  InstallerUrl: https://download.visualstudio.microsoft.com/download/pr/daabba86-451d-47eb-aae2-c96c177f6868/e7b3885d3a0febb83b7a5cb155efd8410a9a651a1be16eaaa35d594c4d1d75d2/vs_SSMS.exe
  InstallerSha256: e7b3885d3a0febb83b7a5cb155efd8410a9a651a1be16eaaa35d594c4d1d75d2
ManifestType: installer
ManifestVersion: 1.9.0
ReleaseDate: 2026-09-28
