# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.kab
PackageVersion: "157.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win32/kab/Firefox%20Setup%20157.0.exe
  InstallerSha256: 9DE9CDE2ED27C87A264E708CC20820C494ADC8C3FB6FBC479E7B0EEBC2491780
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64/kab/Firefox%20Setup%20157.0.exe
  InstallerSha256: 961E7D1B4BE8F51835615E6502201D372C7C0173F8CA433C29F8F4BC5C50ECFB
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64-aarch64/kab/Firefox%20Setup%20157.0.exe
  InstallerSha256: 4D9A15EC7E4D26B5F2496555CA64B0C3C65251692C2E3DD6875F2A8CC9857275
ManifestType: installer
ManifestVersion: 1.12.0
