# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: HiggX.QFCLI
PackageVersion: 0.3.8-beta
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: qfc.exe
    PortableCommandAlias: qfc
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/quotationfactory/qf_cli/releases/download/v0.3.8-beta/qfc-win-x64.zip
    InstallerSha256: CE6AD93C1D1674BAE19F00D9A15C96B6D25D4752DE880803900CD8B2F84A83CA
ManifestType: installer
ManifestVersion: 1.6.0
