# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.mr
PackageVersion: "157.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win32/mr/Firefox%20Setup%20157.0.exe
  InstallerSha256: 1AA22A4253EF286F1E628A4FA6901594EC519061483298B268C5E4857DC8FFBC
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64/mr/Firefox%20Setup%20157.0.exe
  InstallerSha256: B6D9513185846B5D418F854C82995A572E2C057F9A76BB8C60B7066D547BFA65
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64-aarch64/mr/Firefox%20Setup%20157.0.exe
  InstallerSha256: 42FE844D7021FB7390C289F54AA469635B2197A88AFC8F4628F26B61C38E6CF5
ManifestType: installer
ManifestVersion: 1.12.0
