# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ChangeXbc.WorkBuddySwitch
PackageVersion: 0.1.53
InstallerType: nullsoft
Scope: user
ProductCode: workbuddy-switch
ReleaseDate: 2026-09-26
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/changexbc/workbuddy-switch/releases/download/v0.1.53/workbuddy-switch_0.1.53_x64-setup.exe
  InstallerSha256: 5005A6CDE260EC7B72F7A7E95F071523D1E3EEAAD5BD60DA892C731B927E3D6D
ManifestType: installer
ManifestVersion: 1.12.0
