# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: HERE.MAPMAKING.CLI
PackageVersion: 18.6.26
InstallerLocale: en-US
InstallerType: wix
ProductCode: '{6A0FBDBE-712C-3923-9942-B6BC24BDED3F}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/heremaps/homebrew-map-making-cli/releases/download/18.6.26/maps_cli_2.13-18.6.26-installer.msi
  InstallerSha256: 1567511BB3E54ACC367BEA672C0762BDDA61BE5C0D338AD0469588CE28C4FE0D
ManifestType: installer
ManifestVersion: 1.6.0
