# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: LunarWerxs.SageThumbs2K
PackageVersion: 3.4.0
InstallerLocale: en-US
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
ProductCode: '{B0A1C2D3-E4F5-4607-8899-AABBCCDDEEFF}_is1'
ReleaseDate: 2026-09-27
AppsAndFeaturesEntries:
- ProductCode: '{B0A1C2D3-E4F5-4607-8899-AABBCCDDEEFF}_is1'
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\SageThumbs2K'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/LunarWerxs/SageThumbs-2k/releases/download/v3.4.0/SageThumbs2K-Setup-3.4.0.exe
  InstallerSha256: BC6C716852A7A158B14F0E3BC555A8FD3FBC91DC83D4F5947645A7C61CBE8140
  UnsupportedOSArchitectures:
  - arm64
- Architecture: arm64
  InstallerUrl: https://github.com/LunarWerxs/SageThumbs-2k/releases/download/v3.4.0/SageThumbs2K-Setup-3.4.0-arm64.exe
  InstallerSha256: EBD14063BB57B2075DB6D1614C2966E58A6AD7AF1977AA251F78E460C007B5D3
ManifestType: installer
ManifestVersion: 1.12.0
