# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: 8BitDo.UltimateSoftwareV2
PackageVersion: '1.37'
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: 8BitDo_Ultimate_Software_V2_Windows_V1.37/8BitDo Ultimate Software V2.exe
FileExtensions:
- exe
ReleaseDate: 2026-09-30
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://support.8bitdo.com/bd-uploads/files/ultimate_soft/8BitDo_Ultimate_Software_V2_Windows_V1.37.zip
  InstallerSha256: 5121512B889176EDD3819F581E23EC0AC7901B3060ECEF40D7FDDAA1CB5CBFCA
ManifestType: installer
ManifestVersion: 1.28.0
