# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.Nightly.MSIX
PackageVersion: 159.2609.2720.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: msix
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
PackageFamilyName: Mozilla.MozillaFirefoxNightly_jag0gd4e3s9p2
RestrictedCapabilities:
- runFullTrust
ReleaseDate: 2026-09-27
AppsAndFeaturesEntries:
- DisplayName: Firefox Nightly
  Publisher: Mozilla Corporation
Installers:
- Architecture: x86
  InstallerUrl: https://ftp.mozilla.org/pub/firefox/nightly/2026/09/2026-09-27-20-51-53-mozilla-central/firefox-159.0a1.multi.win32.installer.msix
  InstallerSha256: BF3861838F6E29F7787D2025175307E6A55597B73D66269D6688B0043D0144D3
  SignatureSha256: ED9603A63536744D5DD61B1954D5D917DC37426DF35C70B2FCE432821A27AF80
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/WindowsApps/Mozilla.MozillaFirefoxNightly_159.2609.2720.0_x86__jag0gd4e3s9p2'
- Architecture: x64
  InstallerUrl: https://ftp.mozilla.org/pub/firefox/nightly/2026/09/2026-09-27-20-51-53-mozilla-central/firefox-159.0a1.multi.win64.installer.msix
  InstallerSha256: A3515FEECD9CE8B38493CD4E030C15C646E3F46E8E62B216F19C2394F97CA64D
  SignatureSha256: D8333E946530387E6D484BB0C8D5F23C3E1962379EC5E9DE6CF7B8D11FD10F0C
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/WindowsApps/Mozilla.MozillaFirefoxNightly_159.2609.2720.0_x64__jag0gd4e3s9p2'
- Architecture: arm64
  InstallerUrl: https://ftp.mozilla.org/pub/firefox/nightly/2026/09/2026-09-27-20-51-53-mozilla-central/firefox-159.0a1.multi.win64-aarch64.installer.msix
  InstallerSha256: 850D9D6B4D2E63048277EB52FDBE52D4957BDA6D0AB6DA0CA1A1EF0A58C65A18
  SignatureSha256: F04C8B7C5BEB2E1A3FDA37035F21E5FE96AC957D3601AEFAC7DFEE006A147965
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/WindowsApps/Mozilla.MozillaFirefoxNightly_159.2609.2720.0_arm64__jag0gd4e3s9p2'
ManifestType: installer
ManifestVersion: 1.12.0
