# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: marcinz606.NegPy
PackageVersion: 0.62.0
InstallerLocale: en-US
InstallerType: nullsoft
Scope: machine
ReleaseDate: 2026-09-26
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/marcinz606/NegPy/releases/download/0.62.0/NegPy-0.62.0-Win64-Setup.exe
  InstallerSha256: E56D86B809EDD080EF4A0045FC8CF0340B3ADAD2611B20C0C20F2E7687731A05
ManifestType: installer
ManifestVersion: 1.12.0
