# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: HHDSoftware.FreeHexEditorNeo
PackageVersion: 8.25.01.9585
InstallerType: exe
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: -silent
  SilentWithProgress: -silent
UpgradeBehavior: install
FileExtensions:
- hex
- hexbook
- hexdwc7
- hexhis
- hexlic
- hexpatch
- hexpcs
- hexsel
- hexset7
- s19
- s28
- s37
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://hhdsoftware.com/download/free-hex-editor-neo.exe
  InstallerSha256: 791843D1870E4B482B4F6F1510F06FC923D27CB16EF8CB159FD5AF6540024143
  InstallerSwitches:
    Custom: -user
- Architecture: x64
  Scope: machine
  InstallerUrl: https://hhdsoftware.com/download/free-hex-editor-neo.exe
  InstallerSha256: 791843D1870E4B482B4F6F1510F06FC923D27CB16EF8CB159FD5AF6540024143
  InstallerSwitches:
    Custom: -machine
  ElevationRequirement: elevationRequired
- Architecture: arm64
  Scope: user
  InstallerUrl: https://hhdsoftware.com/download/free-hex-editor-neo-arm64.exe
  InstallerSha256: 0583D96F6AFE896B6E5F8523AE9F995913651375825027CA5F8B5E77188A7814
  InstallerSwitches:
    Custom: -user
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://hhdsoftware.com/download/free-hex-editor-neo-arm64.exe
  InstallerSha256: 0583D96F6AFE896B6E5F8523AE9F995913651375825027CA5F8B5E77188A7814
  InstallerSwitches:
    Custom: -machine
  ElevationRequirement: elevationRequired
ManifestType: installer
ManifestVersion: 1.12.0
