# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Servo.Servo.Nightly
PackageVersion: "1.0"
InstallerType: burn
Scope: machine
Protocols:
- http
- https
ProductCode: '{7C4F6A68-B864-45C7-8D2E-140CB167A2ED}'
ReleaseDate: 2026-09-27
AppsAndFeaturesEntries:
- DisplayName: ServoShell
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/servo/servo-nightly-builds/releases/download/2026-09-27/servo-x86_64-windows-msvc.exe
  InstallerSha256: C6DC01CD1DF8B0A0CEF766F8F88E5FB68F616E7897DA7971612F696BB8548187
ManifestType: installer
ManifestVersion: 1.12.0
