# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: StablyAI.Orca
PackageVersion: 1.4.215
InstallerType: nullsoft
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
ProductCode: 2b325ec9-0ed1-575f-ad70-e08307aee879
ReleaseDate: 2026-09-27
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/stablyai/orca/releases/download/v1.4.215/orca-windows-setup.exe
  InstallerSha256: D793B2239DA3AD9300DDFAB03D36C17772207A11088751B11B20DF50998356E1
ManifestType: installer
ManifestVersion: 1.12.0
