# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: makhlwf.HexPlayer
PackageVersion: 5.5.0
InstallerLocale: en-US
InstallerType: inno
Scope: machine
InstallerSwitches:
  Custom: /ALLUSERS
ProductCode: '{08A53112-0E98-433F-8E55-2D92C3120947}_is1'
ReleaseDate: 2026-09-28
AppsAndFeaturesEntries:
- DisplayName: HexPlayer 5.5.0
  ProductCode: '{08A53112-0E98-433F-8E55-2D92C3120947}_is1'
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\HexPlayer'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/makhlwf/accessible_youtube_downloader_pro/releases/download/v5.5.0/HexPlayer.exe
  InstallerSha256: 0475DB0EEF0EEFE66DD6DBCB5498A39D03C4188F4900AB23C602C030F56E8AEA
ManifestType: installer
ManifestVersion: 1.12.0
