# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.vi
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox ESR
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win32/vi/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: B0BAD9DA1A6EB2598526D874B4F84A9888D7A6C8BF8B9B4B0C6B84EED5BA1524
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64/vi/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 0F5471FCFDEEE3B270AB340BF325FFCE4EE560D2ACA3197FAFF9E6FB19E140FA
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64-aarch64/vi/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: D131A947C13D1314849265F2BBF2EE0E4DFB1620C1CF7FEA31CB2EBE912FF165
ManifestType: installer
ManifestVersion: 1.12.0
