# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Brave.BraveOrigin.Nightly
PackageVersion: 155.1.98.36
InstallerType: exe
ExpectedReturnCodes:
- InstallerReturnCode: -2147219440
  ReturnResponse: cancelledByUser
- InstallerReturnCode: -2147219416
  ReturnResponse: alreadyInstalled
- InstallerReturnCode: -2147218431
  ReturnResponse: invalidParameter
- InstallerReturnCode: -2147024809
  ReturnResponse: invalidParameter
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
- tel
FileExtensions:
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: BraveSoftware Brave-Origin-Nightly
ReleaseDate: 2026-09-28
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.98.36/BraveOriginStandaloneSilentNightlySetup32.exe
  InstallerSha256: 4EBA271AB0E03CD92740B235280E1EA2B3A8280A1D9D56D9F487720523162D50
  InstallModes:
  - silent
- Architecture: x86
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.98.36/BraveOriginStandaloneNightlySetup32.exe
  InstallerSha256: 71EE1218E6AE749943BDCAF8313FC2D0ED57FF63D44275D268209659CE3A6AD1
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.98.36/BraveOriginStandaloneSilentNightlySetup.exe
  InstallerSha256: 56F6E388B5FC5C8D154403DD1A3E6B641BDCB08FFFFFA7364BE6DCDAF63EB0A9
  InstallModes:
  - silent
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.98.36/BraveOriginStandaloneNightlySetup.exe
  InstallerSha256: E27A89D4D055DCC9588836D4AD49F9500F15769C265F769F5025BC7D6261B5B5
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.98.36/BraveOriginStandaloneSilentNightlySetupArm64.exe
  InstallerSha256: 6C220F714146D8983C572E0020780B67CC30918F4AF6DFAF6D985D13477310F6
  InstallModes:
  - silent
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.98.36/BraveOriginStandaloneNightlySetupArm64.exe
  InstallerSha256: C01A8F2190D5084B6E2418CF70A5A828E50CA82A451354AA7DCC3FF755833B23
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
ManifestType: installer
ManifestVersion: 1.12.0
