# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: SteveTheKiller.KillerScan
PackageVersion: 1.7.4
InstallerType: portable
InstallModes:
- silent
InstallerSwitches:
  Custom: /silent
UpgradeBehavior: install
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/SteveTheKiller/KillerScan/releases/download/v1.7.4/KillerScan.exe
  InstallerSha256: D932E9FFCEF4CD97B53A8394DE7490CE4C7BF23652E60FA3EAD81DB400483D79
ManifestType: installer
ManifestVersion: 1.12.0
