# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: T3Tools.T3Code
PackageVersion: 0.0.43
InstallerType: nullsoft
UpgradeBehavior: install
ProductCode: e9197887-efb3-55e0-985e-d6d3b5dd594a
ReleaseDate: 2026-09-29
AppsAndFeaturesEntries:
- ProductCode: e9197887-efb3-55e0-985e-d6d3b5dd594a
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/pingdotgg/t3code/releases/download/v0.0.43/T3-Code-0.0.43-x64.exe
  InstallerSha256: FAF2E8B84DB857D668C85E1FD3F3146683CDAAB326A0ADC6ABAEFDE679051372
- Architecture: arm64
  InstallerUrl: https://github.com/pingdotgg/t3code/releases/download/v0.0.43/T3-Code-0.0.43-arm64.exe
  InstallerSha256: FEB35A06CDED90FF493FD2FE1B033F736829312BD0DADC138DD80DAD0355ED0B
ManifestType: installer
ManifestVersion: 1.28.0
