# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Argente.RegistryCleaner
PackageVersion: 4.1.0.5
InstallerType: inno
Scope: machine
InstallerSwitches:
  Silent: /SP- /VERYSILENT /SUPPRESSMSGBOXES /NORESTART --hidden
  SilentWithProgress: /SP- /SILENT /SUPPRESSMSGBOXES /NORESTART --hidden
UpgradeBehavior: install
ProductCode: Argente Registry Cleaner 3.0
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://argenteutilities.com/en/download/registrycleanerx86
  InstallerSha256: AD6F7CBE9D08D66E7A797FD4084AF7723367E14E84E9C6D78EEA9A52E671FD8F
- Architecture: x64
  InstallerUrl: https://argenteutilities.com/en/download/registrycleanerx64
  InstallerSha256: 1052A1DD61D8AAE589378EA4636D7946591564131545152D6CEB4BB797D14FF5
- Architecture: arm64
  InstallerUrl: https://argenteutilities.com/en/download/registrycleanerarm64
  InstallerSha256: 4985B4BEFDEB7488178CC517921C6192C04BAA1955238B6856F4EE03715AFAB8
ManifestType: installer
ManifestVersion: 1.12.0
