# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Rustlang.rust-analyzer
PackageVersion: 2026-09-28
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: rust-analyzer.exe
  PortableCommandAlias: rust-analyzer
Commands:
- rust-analyzer
ReleaseDate: 2026-09-28
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/rust-lang/rust-analyzer/releases/download/2026-09-28/rust-analyzer-i686-pc-windows-msvc.zip
  InstallerSha256: 3CE2D485FE42ACFBFAB36640ADB3F1303CCC8D63A3163A6275320BC59A31DB45
- Architecture: x64
  InstallerUrl: https://github.com/rust-lang/rust-analyzer/releases/download/2026-09-28/rust-analyzer-x86_64-pc-windows-msvc.zip
  InstallerSha256: AD78FB368525404C6AC09C4BBA33E90797902CE1F5A17DB0925C695CAE096CCC
- Architecture: arm64
  InstallerUrl: https://github.com/rust-lang/rust-analyzer/releases/download/2026-09-28/rust-analyzer-aarch64-pc-windows-msvc.zip
  InstallerSha256: F63C7FC9A00A7E863B21B5E0B77CDA7FF61AAA9F6F83B0AFFA5BBB525BE7C43C
ManifestType: installer
ManifestVersion: 1.12.0
