# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Fluxer.Fluxer
PackageVersion: 2026.927.142044
InstallerType: exe # Velopack
Scope: user
InstallModes:
- silent
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
  InstallLocation: --installto "<INSTALLPATH>"
  Log: --log "<LOGPATH>"
UpgradeBehavior: install
ProductCode: fluxer_desktop
ReleaseDate: 2026-09-27
AppsAndFeaturesEntries:
- Publisher: Fluxer Platform AB
  ProductCode: fluxer_desktop
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\fluxer_desktop'
Installers:
- Architecture: x64
  InstallerUrl: https://api.fluxer.app/dl/desktop/stable/win32/x64/2026.927.142044/setup
  InstallerSha256: 6693A4EF6418878BD9C4CAB0B7241535AF90A71D2F414AC7D79F0880D467F6CD
- Architecture: arm64
  InstallerUrl: https://api.fluxer.app/dl/desktop/stable/win32/arm64/2026.927.142044/setup
  InstallerSha256: D863286285FA7028EFE0AE963EF5A873135B43261640279C81C0E4DA7C37D87D
ManifestType: installer
ManifestVersion: 1.12.0
