# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: MikeFarah.yq
PackageVersion: 4.53.6
ReleaseDate: 2026-08-20
InstallerLocale: en-US
InstallerType: portable
Commands:
- yq
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/mikefarah/yq/releases/download/v4.53.6/yq_windows_amd64.exe
  InstallerSha256: ECE3DD8BB50D39F93610506273EA262FEB91E5C486BBDDBB10ABF91B2A6C0F14
- Architecture: x86
  InstallerUrl: https://github.com/mikefarah/yq/releases/download/v4.53.6/yq_windows_386.exe
  InstallerSha256: 3cabc5e4ca1aad2489fe2ada4d220d444f385dcd5c5a75078a159d65ba43a1de
  AppsAndFeaturesEntries:
  - DisplayName: yq (x86)
- Architecture: arm64
  InstallerUrl: https://github.com/mikefarah/yq/releases/download/v4.53.6/yq_windows_arm64.exe
  InstallerSha256: 9a0ec8f648b0749d3d71286df96384f358c0eeca486bbcdec04e747307021d3a
  AppsAndFeaturesEntries:
  - DisplayName: yq (ARM64)
ManifestType: installer
ManifestVersion: 1.12.0
