# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: GrafanaLabs.Grafana.Enterprise
PackageVersion: 13.2.3
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
UpgradeBehavior: install
ProductCode: '{2D25F50C-5037-494F-9318-FBB965C06C34}'
ReleaseDate: 2026-09-29
AppsAndFeaturesEntries:
- ProductCode: '{2D25F50C-5037-494F-9318-FBB965C06C34}'
  UpgradeCode: '{D534EC50-476B-4EDC-A25E-FE854C949F4F}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%/GrafanaLabs'
Installers:
- Architecture: x64
  InstallerUrl: https://dl.grafana.com/grafana-enterprise/release/13.2.3/grafana-enterprise_13.2.3_36482603486_windows_amd64.msi
  InstallerSha256: 1C13AD386D889A35192E9B5DB8438C48AB99FD62C7DCCDD21A6EEFB12C45C564
ManifestType: installer
ManifestVersion: 1.28.0
