# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.nn-NO
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox ESR
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win32/nn-NO/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: F15414209DF7069DFD1895C6E4A810FF3CC91A71B154A599705A2D3DE0001337
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64/nn-NO/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 1593DB47B2161356E473FDC5A2ED879FF12682FECA6313CAF2BED6DD537855EF
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64-aarch64/nn-NO/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: C14DC3FEAC679DD2DC3D203E5AD3E131052E200ABCC2B20BA60BEEE1347F4A9D
ManifestType: installer
ManifestVersion: 1.12.0
