# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Argente.SystemManager
PackageVersion: 1.0.5.0
InstallerType: inno
Scope: machine
InstallerSwitches:
  Silent: /SP- /VERYSILENT /SUPPRESSMSGBOXES /NORESTART --hidden
  SilentWithProgress: /SP- /SILENT /SUPPRESSMSGBOXES /NORESTART --hidden
UpgradeBehavior: install
ProductCode: Argente System Manager 3.0
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://argenteutilities.com/en/download/systemmanagerx86
  InstallerSha256: A33B309A44202ADA1F3C52BA00E4273A254070C192369A37BFA013BAE1E721EB
- Architecture: x64
  InstallerUrl: https://argenteutilities.com/en/download/systemmanagerx64
  InstallerSha256: E3740295DF659E822DA3131582452EC63A5809618C5E2CDF0981A2BD10C6DB76
- Architecture: arm64
  InstallerUrl: https://argenteutilities.com/en/download/systemmanagerarm64
  InstallerSha256: DB7F8523090A5BF20BC91B2BF307DFA8BABE363F2ECF6E02EFD04CF6B542661E
ManifestType: installer
ManifestVersion: 1.12.0
