# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: laurentiu021.SysManager
PackageVersion: 1.114.39
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: portable
Commands:
- SysManager
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/laurentiu021/SystemManager/releases/download/v1.114.39/SysManager-v1.114.39.exe
  InstallerSha256: D727724939D07C184D95E198989A907A96F0C8BBF24B612D63E3F5B11DA01AAA
ManifestType: installer
ManifestVersion: 1.12.0
