# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.fy-NL
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox ESR
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win32/fy-NL/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 084E410FC5C2C59498128D6A314F5594FC4C31BE528BC8CAE45A5AA318647CAF
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64/fy-NL/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 57D66D2FF59571C924B3A3CFDF57C4683892DD8E0DC12BFE402CF172AD160370
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64-aarch64/fy-NL/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 2AF8BBF89B168AA117575B4897C291A56336E5EC0FA71410DA7A634C451B9750
ManifestType: installer
ManifestVersion: 1.12.0
