# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: KDE.Klickety
PackageVersion: master
InstallerType: nullsoft
UpgradeBehavior: install
ProductCode: klickety
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://cdn.kde.org/ci-builds/games/klickety/master/windows/klickety-master-1013-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: 4606B5E4BE4CDC8A7C0C658379FECDB290863D052CCD69BEED19C537520062BD
  InstallerSwitches:
    Custom: /CurrentUser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://cdn.kde.org/ci-builds/games/klickety/master/windows/klickety-master-1013-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: 4606B5E4BE4CDC8A7C0C658379FECDB290863D052CCD69BEED19C537520062BD
  InstallerSwitches:
    Custom: /AllUsers
ManifestType: installer
ManifestVersion: 1.12.0
