# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.fi
PackageVersion: "157.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win32/fi/Firefox%20Setup%20157.0.exe
  InstallerSha256: B746829550B0B566EFF5820C566F57E1BBE415FC52270050816EA23E589E21CE
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64/fi/Firefox%20Setup%20157.0.exe
  InstallerSha256: 89E51A2148482100E2AC334B9D14067D33DF0C85D2AE8BBAB885FAA11978964B
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64-aarch64/fi/Firefox%20Setup%20157.0.exe
  InstallerSha256: 09FD41AEA83F84004DA0DDF3017D24865BDAF873B69BD9541898A658227F4025
ManifestType: installer
ManifestVersion: 1.12.0
