# Created with WinGet Updater using komac v2.15.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: autobrr.mkbrr
PackageVersion: 1.26.0
PackageLocale: en-US
Publisher: autobrr
PublisherUrl: https://github.com/autobrr
PublisherSupportUrl: https://github.com/autobrr/mkbrr/issues
PackageName: mkbrr
PackageUrl: https://github.com/autobrr/mkbrr
License: GPL-2.0
LicenseUrl: https://github.com/autobrr/mkbrr/blob/HEAD/LICENSE
ShortDescription: mkbrr is a tool to create, modify and inspect torrent files. Fast.
Tags:
- bittorrent
- go
- golang
- metafile
- torrent
ReleaseNotes: |-
  Changelog
  New Features
  - 65ccb97: feat(torrent): honor explicit tracker piece-size ranges (#201) (@maghuro)
  - 5fc15cc: feat(trackers): add Portugas.org rules (#199) (@maghuro)
  Other work
  - 30e7fb5: Fix test that depend on the local timezone (#197) (@n-peugnet)
  - 0f1926e: ci: remove Claude code review workflow (#203) (@s0up4200)
  Full Changelog: v1.25.1...v1.26.0
ReleaseNotesUrl: https://github.com/autobrr/mkbrr/releases/tag/v1.26.0
ManifestType: defaultLocale
ManifestVersion: 1.12.0
