# Created with WinGet Updater using komac v2.15.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: autobrr.mkbrr
PackageVersion: 1.26.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: mkbrr.exe
  PortableCommandAlias: mkbrr
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/autobrr/mkbrr/releases/download/v1.26.0/mkbrr_1.26.0_windows_x86_64.zip
  InstallerSha256: 82C58E8E888F4464289C391D93DD7D4B52303FFE937A37831B587FDCE1EC5EE9
ManifestType: installer
ManifestVersion: 1.12.0
