# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: SQLBI.Whiteboard
PackageVersion: 1.7.2
MinimumOSVersion: 10.0.19041.0
InstallerType: wix
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/sql-bi/SQLBI-Whiteboard/releases/download/v1.7.2/SQLBI.Whiteboard.1.7.2.x64.msi
  InstallerSha256: 557AAF762DFCC35E98BE870CDBE50013BFE9C728432077100EEE5AEA16D8AFA1
  ProductCode: '{0A07D212-08F4-4F1B-A254-BF79103C4ED7}'
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/sql-bi/SQLBI-Whiteboard/releases/download/v1.7.2/SQLBI.Whiteboard.1.7.2.x64-userinstaller.msi
  InstallerSha256: 8AF4E09B8092C9C756780B7CAD2A9881697229BE7AF237FC9E5C3AB455C451FF
  ProductCode: '{850820AB-354D-4009-9D5C-6C767B4EB7DB}'
ManifestType: installer
ManifestVersion: 1.12.0
