# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: xAI.GrokBuild
PackageVersion: 1.0.44
InstallerType: portable
Commands:
- grok
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://x.ai/cli/grok-1.0.44-windows-x86_64.exe
  InstallerSha256: 0F2AB84FB066D60F99B861F1030984CD190754DE28E7982A859B25D82FA52FAC
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  InstallerUrl: https://x.ai/cli/grok-1.0.44-windows-aarch64.exe
  InstallerSha256: FCD752E6157E7BA577AE03251F94CD8C9724322E4C088B0C8B7CD569BAB32AA2
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.12.0
