# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ntwind.MediaRemote
PackageVersion: 1.0.3
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: install
AppsAndFeaturesEntries:
- DisplayName: Media Remote
  Publisher: NTWIND LLC
ElevationRequirement: elevationRequired
Installers:
- Architecture: x64
  InstallerUrl: https://www.ntwind.com/files/MediaRemote_1.0.3-win-x64.exe
  InstallerSha256: A47B7070A70E0FB4894FE9E3CE1ABE3F66987E862329C5B950F96C7BB2C56CED
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-07
