# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Tautulli.Tautulli
PackageVersion: 2.18.2.1
Platform:
- Windows.Desktop
InstallerType: nullsoft
InstallerSwitches:
  Silent: /S
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Tautulli/Tautulli/releases/download/v2.18.2/Tautulli-windows-v2.18.2-x64.exe
  InstallerSha256: 650B907C445244067E7BA8040273E428C54721EAC5E5906915BA8973B109FC7E
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-28
