# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: TrackerSoftware.PDF-XChangeStandard
PackageVersion: 11.1.0.0
InstallerType: wix
Scope: machine
UpgradeBehavior: install
FileExtensions:
- xcvault
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://downloads.pdf-xchange.com/11.1.0.0/StandardV11.x86.msi
  InstallerSha256: DE7EE43D49E5596E5D1E6741F881EB4452E02CF39C14FC8496FD3DABC12E3556
  ProductCode: '{A3E8A650-BF98-4C9B-A414-5A18EA68EE7F}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{B0A987BC-5E91-4930-9437-ABFFA517DBE1}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles(x86)%/Tracker Software'
- Architecture: x64
  InstallerUrl: https://downloads.pdf-xchange.com/11.1.0.0/StandardV11.x64.msi
  InstallerSha256: 4C4E51A84260F949ADA3EA672656B4C402525602CFF58674FC204316EE98FBCA
  ProductCode: '{D564ECE3-8BAE-4303-B4F8-695DD0AFFBE1}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{CA231CAC-3C44-45AD-BB95-0F6288945DF6}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/Tracker Software'
- Architecture: arm64
  InstallerUrl: https://downloads.pdf-xchange.com/11.1.0.0/StandardV11.ARM64.msi
  InstallerSha256: 5A147DB2052C79A9CFB0F0D13C3259FB4DF2B862A35A4BD86E987CA0B07C036F
  ProductCode: '{C5186799-25DC-4BD8-ABC5-83777091D5A5}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{CEC32EB8-3A4E-493B-8193-EB6DEDDF1D0B}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/Tracker Software'
ManifestType: installer
ManifestVersion: 1.12.0
