# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: skim-rs.skim
PackageVersion: 5.7.2
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: sk.exe
  PortableCommandAlias: sk
Commands:
- sk
ReleaseDate: 2026-09-27
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/skim-rs/skim/releases/download/v5.7.2/skim-x86_64-pc-windows-msvc.zip
  InstallerSha256: 664EC9691E538C8B524D30CFD9E6DA65EAA6567747B6F2704C484F53220ED459
ManifestType: installer
ManifestVersion: 1.12.0
