# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.mk
PackageVersion: "157.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win32/mk/Firefox%20Setup%20157.0.exe
  InstallerSha256: 1CF5AB582C678ABE593673ED8E48C46887EA8C85D35ADCC63450885A8F5B8069
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64/mk/Firefox%20Setup%20157.0.exe
  InstallerSha256: F30B2A81A844197705D215E0E723D81A909E0833ED8B9E317299D66FCD10FA60
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64-aarch64/mk/Firefox%20Setup%20157.0.exe
  InstallerSha256: C47E2F22320FFDE3221A5EC6692FD047CC67D67BCF5851EB789104621D733360
ManifestType: installer
ManifestVersion: 1.12.0
