# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json
PackageIdentifier: gorodulin.prj
PackageVersion: 0.11.1
InstallerType: portable
Commands:
- prj
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/gorodulin/prj/releases/download/v0.11.1/prj-windows-amd64.exe
  InstallerSha256: 80B07B368D2F2BBC151DA5C39C103ADE1CB6CB7D75564965B6E3FE802BE76010
- Architecture: arm64
  InstallerUrl: https://github.com/gorodulin/prj/releases/download/v0.11.1/prj-windows-arm64.exe
  InstallerSha256: 33AF4B7CDD7E79079904076AFCF5C4C5F26BF8C06A06AC2EE29289A10B5E0FED
ManifestType: installer
ManifestVersion: 1.9.0
