# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Herdr.Herdr.Preview
PackageVersion: 0.9.1-preview.2026-09-28-80c0c07250d2
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: herdr.exe
  PortableCommandAlias: herdr
Commands:
- herdr
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ReleaseDate: 2026-09-28
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/herdrdev/herdr/releases/download/preview-2026-09-28-80c0c07250d2/herdr-windows-x86_64.zip
  InstallerSha256: E688BDC81CF4C8C608CCA5ED7528626CF82C8DDF1EAA8E35274B9FC6E202BE1C
ManifestType: installer
ManifestVersion: 1.12.0
