# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: NuvioMedia.NuvioDesktop
PackageVersion: 0.1.26-alpha
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{47543BAA-CD50-3953-8556-D4EF6DE8508B}'
ReleaseDate: 2026-09-26
AppsAndFeaturesEntries:
- DisplayName: Nuvio
  Publisher: Nuvio Media
  DisplayVersion: 1.1.26
  ProductCode: '{47543BAA-CD50-3953-8556-D4EF6DE8508B}'
  UpgradeCode: '{395990EE-9B8A-3548-922C-E7A23A495B8D}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Nuvio'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/NuvioMedia/NuvioDesktop/releases/download/0.1.26-alpha/Nuvio-Windows-x64-0.1.26-alpha.msi
  InstallerSha256: D88EB7D9B5D59B9D840F68D3F9357B49266AEC10FECA8ACC8AA70E40E6DE7DC0
ManifestType: installer
ManifestVersion: 1.12.0
