# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: blakazulu.Findra
PackageVersion: 0.6.2
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Custom: /INSTALLSOURCE=winget
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/blakazulu/findra/releases/download/v0.6.2/findra-setup-x64.exe
  InstallerSha256: 13E7C0553E5245A097C38D5C35B443F58F34105405C11965512924A9DCE05496
- Architecture: arm64
  InstallerUrl: https://github.com/blakazulu/findra/releases/download/v0.6.2/findra-setup-arm64.exe
  InstallerSha256: 383BD3E5932E90AAA1DC8516349961CACF9A0A3B311EF9683EEDAE9AB027FF8F
ManifestType: installer
ManifestVersion: 1.6.0
