# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Microsoft.GameInput
PackageVersion: 3.5.283
InstallerType: zip
NestedInstallerType: wix
NestedInstallerFiles:
- RelativeFilePath: redist\GameInputRedist.msi
Scope: machine
ProductCode: '{DE514461-35F8-4F95-AAE9-630369B9E844}'
ReleaseDate: 2026-09-28
AppsAndFeaturesEntries:
- ProductCode: '{DE514461-35F8-4F95-AAE9-630369B9E844}'
  UpgradeCode: '{37042BD3-CED5-451B-818A-3E9454BDF060}'
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%/Microsoft GameInput'
Installers:
- Architecture: x64
  InstallerUrl: https://globalcdn.nuget.org/packages/microsoft.gameinput.3.5.283.nupkg
  InstallerSha256: B5988CB8FF9D7009B6DDF6AD4E3FF87E91B00CC17FFCD5D628DABC21C208F100
ManifestType: installer
ManifestVersion: 1.12.0
