# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: UniClipboard.UniClipboard
PackageVersion: 1.0.1
InstallerType: nullsoft
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/UniClipboard/UniClipboard/releases/download/v1.0.1/UniClipboard_1.0.1_x64-setup.exe
  InstallerSha256: CAA7A24BABAE533DC590647314D3F416AB143C99A0CA0BE8DBA4958357219296
- Architecture: arm64
  InstallerUrl: https://github.com/UniClipboard/UniClipboard/releases/download/v1.0.1/UniClipboard_1.0.1_arm64-setup.exe
  InstallerSha256: 238C1CC9169A6D6203CF9E3539C74C1B7DFE77964CAEC2A969FC74511DD2C938
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-29
