# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: KDE.Granatier
PackageVersion: master
InstallerType: nullsoft
UpgradeBehavior: install
ProductCode: granatier
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://cdn.kde.org/ci-builds/games/granatier/master/windows/granatier-master-961-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: 2EB317DDDF3A1BB4979579735E0042EEB9E4985E80DF82772DABA58F085270C3
  InstallerSwitches:
    Custom: /CurrentUser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://cdn.kde.org/ci-builds/games/granatier/master/windows/granatier-master-961-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: 2EB317DDDF3A1BB4979579735E0042EEB9E4985E80DF82772DABA58F085270C3
  InstallerSwitches:
    Custom: /AllUsers
ManifestType: installer
ManifestVersion: 1.12.0
