# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: LibreDB.Studio
PackageVersion: 0.17.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: libredb-studio.exe
  PortableCommandAlias: libredb-studio
Commands:
- libredb-studio
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/libredb/libredb-studio/releases/download/0.17.0/libredb-studio-standalone-0.17.0-win32-x64.zip
  InstallerSha256: 5BBE01B13EEB38A6DF514A583D96977E89B7449626F5AE3EC7DF0B9474FE1427
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-26
