# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.it
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox ESR
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win32/it/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: D5719935B9AE14BA98A36CF64BAFB06CC0655DF391D82AB16D9E2753BE91BFEC
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64/it/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 725F74B2C8D758F8BB5F459DBB4079D9A507257F4FE1232A2DBED6F85B4D125B
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64-aarch64/it/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 7319BAC56E51FD78F7CB7336D8B87603D5105760B95C837855A2378A7B4248E9
ManifestType: installer
ManifestVersion: 1.12.0
