# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: VladimirYakovlev.ElectronMail
PackageVersion: 5.3.10
InstallerType: nullsoft
UpgradeBehavior: install
ProductCode: dda31663-c6b6-5593-afb9-19792a7a8c9d
ReleaseDate: 2026-09-29
AppsAndFeaturesEntries:
- ProductCode: dda31663-c6b6-5593-afb9-19792a7a8c9d
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/vladimiry/ElectronMail/releases/download/v5.3.10/electron-mail-5.3.10-windows-x64-nsis-installer.exe
  InstallerSha256: 1B1AB30A86D21335D4E67CF807F0B808C1BE2AA633D4DBACA1F9402DE62DDFCB
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/vladimiry/ElectronMail/releases/download/v5.3.10/electron-mail-5.3.10-windows-x64-nsis-installer.exe
  InstallerSha256: 1B1AB30A86D21335D4E67CF807F0B808C1BE2AA633D4DBACA1F9402DE62DDFCB
  InstallerSwitches:
    Custom: /ALLUSERS
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/vladimiry/ElectronMail/releases/download/v5.3.10/electron-mail-5.3.10-windows-arm64-nsis-installer.exe
  InstallerSha256: CFD7B9DE1E33C8A81556C0DFD6B2F20BCF76126D2CCC54463F55BB6685D74B41
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/vladimiry/ElectronMail/releases/download/v5.3.10/electron-mail-5.3.10-windows-arm64-nsis-installer.exe
  InstallerSha256: CFD7B9DE1E33C8A81556C0DFD6B2F20BCF76126D2CCC54463F55BB6685D74B41
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.28.0
