# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.son
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox ESR
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win32/son/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 7385E5C5FC26BCEBD24511F65FBF3D4F308C8E03AECC2406346C883BB7922701
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64/son/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 927C9E84ED7D59DB46E38658BF3C74E8876E80073A7810F50152C21F2AA2B56E
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64-aarch64/son/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 2FBCC7346869651F1786F931CA14274431100DE1AE2A1ECF5FC9E0EF33FBB9E5
ManifestType: installer
ManifestVersion: 1.12.0
