# Automatically updated by the winget bot at 2026/Sep/28
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: SpecialK.SpecialK
PackageVersion: 26.9.25
InstallerType: inno
UpgradeBehavior: install
ProductCode: '{F4A43527-9457-424A-90A6-17CF02ACF677}_is1'
ReleaseDate: 2026-09-25
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://sk-data.special-k.info/repository/SpecialK_26.9.25.exe
  InstallerSha256: 9E758BF3921A7714D17506B3ED24FEA65079657D9EEF6986D3C6C612D696C3F6
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x64
  Scope: machine
  InstallerUrl: https://sk-data.special-k.info/repository/SpecialK_26.9.25.exe
  InstallerSha256: 9E758BF3921A7714D17506B3ED24FEA65079657D9EEF6986D3C6C612D696C3F6
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.28.0
