# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ESEngine.ReasonixCLI
PackageVersion: 1.39.4
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: reasonix.exe
Commands:
- reasonix
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/esengine/DeepSeek-Reasonix/releases/download/v1.39.4/reasonix-windows-amd64.zip
  InstallerSha256: 16DC9ACADBBB06047F52F795725C965AEFDD65A1D00DBA4C00BE0B1DDE0B5059
- Architecture: arm64
  InstallerUrl: https://github.com/esengine/DeepSeek-Reasonix/releases/download/v1.39.4/reasonix-windows-arm64.zip
  InstallerSha256: 38C87B3AEBA3ED8ACA300D412DD123C8B0E1D23079183D3F6BFCDD354123BE4D
ManifestType: installer
ManifestVersion: 1.12.0
