# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.en-CA
PackageVersion: "157.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win32/en-CA/Firefox%20Setup%20157.0.exe
  InstallerSha256: 200268C17525E8DDAF6FAE082315DD3D02278B8EFC8FB1E62A05C3CE5FE58BB7
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64/en-CA/Firefox%20Setup%20157.0.exe
  InstallerSha256: 6652F5E69896767765F1E365E17FBDA2826BD1EBD47CB3ACE2F6861CEA18DB54
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64-aarch64/en-CA/Firefox%20Setup%20157.0.exe
  InstallerSha256: 01C53F5507F945019032B5F58B964D282906C901B288CF726DA40C028C7D8EB1
ManifestType: installer
ManifestVersion: 1.12.0
