# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Ruihu.Apifox
PackageVersion: 2.8.49
InstallerType: nullsoft
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://file-assets.apifox.com/download/2.8.49/Apifox-2.8.49.exe
  InstallerSha256: 7F954C6CD8B87704EA55F09E2C2BF35720D55A312C5FC09DFDBC8393E9ECCD77
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://file-assets.apifox.com/download/2.8.49/Apifox-2.8.49.exe
  InstallerSha256: 7F954C6CD8B87704EA55F09E2C2BF35720D55A312C5FC09DFDBC8393E9ECCD77
  InstallerSwitches:
    Custom: /allusers
ManifestType: installer
ManifestVersion: 1.12.0
