# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: Automattic.Wordpress
PackageVersion: 8.2.4
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: nullsoft
InstallModes:
- interactive
- silent
InstallerSwitches:
  Custom: /CURRENTUSER
UpgradeBehavior: install
ProductCode: "{ED4E3354-70D4-58F5-8F6D-7420253356E2}"
ReleaseDate: 2026-09-16
AppsAndFeaturesEntries:
- DisplayName: WordPress.com 8.2.4
  ProductCode: "{ED4E3354-70D4-58F5-8F6D-7420253356E2}"
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://github.com/Automattic/wp-desktop/releases/download/v8.2.4/wordpress.com-win32-setup-8.2.4.exe
  InstallerSha256: 750F097AC3D76F6E6394650501E0F6CC5DCEB571F7E061AD7644D9DBB36E03FD
- Architecture: x86
  Scope: machine
  InstallerUrl: https://github.com/Automattic/wp-desktop/releases/download/v8.2.4/wordpress.com-win32-setup-8.2.4.exe
  InstallerSha256: 750F097AC3D76F6E6394650501E0F6CC5DCEB571F7E061AD7644D9DBB36E03FD
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.12.0
