# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.es-AR
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox ESR
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win32/es-AR/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: F0B471A5CCEFC23557991B094ADD288B57C3BCEC922A812A937C1B83AB3EF2FB
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64/es-AR/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 5EE6B212422A2D9A94552EC50C03C509A80C733833915E3AFE8C4A8CEFCBE963
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64-aarch64/es-AR/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 2427F14B3149A77368657477F71C0DE43AA498588ECB4B771E72389E3A2C4BA9
ManifestType: installer
ManifestVersion: 1.12.0
