# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: dotenvx.dotenvx
PackageVersion: 2.31.1
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: dotenvx.exe
  PortableCommandAlias: dotenvx
UpgradeBehavior: uninstallPrevious
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/dotenvx/dotenvx/releases/download/v2.31.1/dotenvx-2.31.1-windows-x86_64.zip
  InstallerSha256: 391BC70FFCD7B57C0E6F563925FB6856AB77AB8DBB59470BAC20B49B9990EFCC
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-27
