# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: TrackerSoftware.PDF-Tools
PackageVersion: 11.1.0.0
InstallerType: wix
Scope: machine
UpgradeBehavior: install
Protocols:
- pxce
FileExtensions:
- fdf
- pdf
- pdtex
- pdts
- xces
- xcesession
- xcesessionbk
- xclpack
- xcvault
- xfdf
- xps
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://downloads.pdf-xchange.com/11.1.0.0/ToolsV11.x86.msi
  InstallerSha256: 9705116F34ED975C1416F38AC4497421EE54FE8D38D33CBB6D4B6E7D6B931C93
  ProductCode: '{F29D2235-DF94-454D-9761-1CB46A360DDD}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{8B29DB03-A8AB-4B2B-ABA8-3A7DF2CE0096}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles(x86)%/Tracker Software'
- Architecture: x64
  InstallerUrl: https://downloads.pdf-xchange.com/11.1.0.0/ToolsV11.x64.msi
  InstallerSha256: BC9CCA3D0B914C76F2F9E9B7F104EC8C75B60A0E6712C3A74C5AE9527FE724C9
  ProductCode: '{94304AFA-DD57-47A7-91BF-55260FE89020}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{0A909602-6CB4-4CD3-AC7A-6808D8F272BD}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/Tracker Software'
- Architecture: arm64
  InstallerUrl: https://downloads.pdf-xchange.com/11.1.0.0/ToolsV11.ARM64.msi
  InstallerSha256: 9BAB4B0BFE23AA795921077ADB2089BF955F22DFDC45D401AB17CBFF972853F6
  ProductCode: '{E9631333-3873-481F-8BB7-AAB244D5ED6D}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{CACC4F67-BE85-4C1A-BC94-82681AE1B8F5}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/Tracker Software'
ManifestType: installer
ManifestVersion: 1.12.0
