# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ff
PackageVersion: "157.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win32/ff/Firefox%20Setup%20157.0.exe
  InstallerSha256: B7F5AF577ED54A3EEB54F196F0E74277372533A8B63E8C0702F2A7B89EE51502
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64/ff/Firefox%20Setup%20157.0.exe
  InstallerSha256: B26A468224D1267CA2F0A863966009B08F6F77356989FB0527C0D37EEBAD9735
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64-aarch64/ff/Firefox%20Setup%20157.0.exe
  InstallerSha256: 6D319CD9B8DC61033988257F5487D7778A0C8BA605AD2F65EDC91268CCFB0043
ManifestType: installer
ManifestVersion: 1.12.0
