# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Flint.Fls
PackageVersion: 0.4.2-core
InstallerLocale: en-US
InstallerType: portable
Commands:
- fls
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/flint-lang/flintc/releases/download/v0.4.2-core/fls.exe
  InstallerSha256: fdcd3c16e729e31fbf4bfca2655ca95f6599dce922c8bfa9311e9fdc045471ac
ManifestType: installer
ManifestVersion: 1.6.0
