# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Amazon.AWSCLI
PackageVersion: 2.37.6
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: AWSCLIV2="<INSTALLPATH>"
UpgradeBehavior: install
Commands:
- aws
ProductCode: '{B02BB19D-983F-40CE-8C9B-86ADBF181246}'
ReleaseDate: 2026-09-29
AppsAndFeaturesEntries:
- UpgradeCode: '{E1C1971C-384E-4D6D-8D02-F1AC48281CF8}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Amazon\AWSCLIV2'
Installers:
- Architecture: x64
  InstallerUrl: https://awscli.amazonaws.com/AWSCLIV2-2.37.6.msi
  InstallerSha256: 98FEAB7E92E7F360C7E209266209B273DBE04AF031F0CC0EC471C2156E7EE292
ManifestType: installer
ManifestVersion: 1.12.0
