# Created with WinGet Tracker using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: t8y2.DBX
PackageVersion: 0.6.27
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: DBX
ReleaseDate: 2026-09-28
AppsAndFeaturesEntries:
- Publisher: dbx
  ProductCode: DBX
InstallationMetadata:
  DefaultInstallLocation: placeholder\DBX
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/t8y2/dbx/releases/download/v0.6.27/DBX_0.6.27_x64-setup.exe
  InstallerSha256: 72EA77965C074FE5ADDC7A3F6A3413BF232087EB08DAC9008CB323AB17037E25
ManifestType: installer
ManifestVersion: 1.12.0
