# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.zh-CN
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox ESR
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win32/zh-CN/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 525155FE9668DF550230EBC972083EDC6B957E58D22F395CE131C5643059C4A0
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64/zh-CN/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: DBB0557FB90F4D0527933F58F2399B02F86115EF93D8763E0C2A1FD1635C4A3F
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64-aarch64/zh-CN/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 589437339FACB6E8847FA3CD65B997701D93CFB22BA89BE2D1A91B362D1D9B19
ManifestType: installer
ManifestVersion: 1.12.0
