# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Herdr.Herdr.Preview
PackageVersion: 0.9.2-preview.2026-09-29-8e78f929d8f0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: herdr.exe
  PortableCommandAlias: herdr
Commands:
- herdr
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ReleaseDate: 2026-09-29
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/herdrdev/herdr/releases/download/preview-2026-09-29-8e78f929d8f0/herdr-windows-x86_64.zip
  InstallerSha256: BBEBBD192FC6356228EFDFB89AD1CE86813F3AFF41AD48DBF5082FBE94E2485C
ManifestType: installer
ManifestVersion: 1.12.0
