# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: Microsoft.PowerBI
PackageVersion: 2.158.1177.0
PackageLocale: da-DK
PackageName: Skrivebordsversion af Microsoft Power BI
PackageUrl: https://www.microsoft.com/da-dk/download/details.aspx?id=58494
License: Proprietær
Description: Bygget til analytikere. Den kombinerer de nyeste interaktive visualiseringer med integreret brancheførende dataforespørgsel og modellering. Opret og publicer rapporterne til Power BI. Skrivebordsversionen af Power BI gør det muligt for dig rettidigt at give andre vigtig indsigt – når som helst og hvor som helst.
Tags:
- 9ntxr16hnw1t
- analytics
- business-intelligence
- dashboarding
- dataanalyse
- datavisualisering
- microsoft-power-bi-desktop
- microsoftpowerbidesktop
- rapportering
ManifestType: locale
ManifestVersion: 1.12.0
