# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: Microsoft.PowerBI
PackageVersion: 2.158.1177.0
PackageLocale: ca-ES
PackageName: Escriptori del Microsoft Power BI
PackageUrl: https://www.microsoft.com/ca-es/download/details.aspx?id=58494
Description: S’ha dissenyat per a analistes. Combina visualitzacions interactives d'última generació amb les millors modelitzacions i consultes de dades del sector integrades. Creeu i publiqueu els informes al Power BI. L’Escriptori del Power BI us permet facultar els altres amb coneixements tècnics oportuns, en qualsevol moment i a qualsevol lloc.
Tags:
- 9ntxr16hnw1t
- analytics
- business-intelligence
- dashboarding
- data
- data-analysis
- data-visualization
- escriptori-del-microsoft-power-bi
- escriptoridelmicrosoftpowerbi
- microsoft-power-bi-desktop
- microsoftpowerbidesktop
- reporting
- visualitzacions
ManifestType: locale
ManifestVersion: 1.12.0
