# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: SureshJanakiReddy.GeminiDesktop
PackageVersion: 0.2.16
InstallerType: portable
Commands:
- gemini-desktop
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/sureshjsreddy/gemini-desktop/releases/download/v0.2.16/GeminiDesktop-Portable.exe
  InstallerSha256: 5A6B745E15266493A03737DA6DF7762161F077305CF9A93851888F742E3D9122
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-30
