# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.hr
PackageVersion: "157.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win32/hr/Firefox%20Setup%20157.0.exe
  InstallerSha256: 85384247E7C44A5DC289B573F2C8DE6BDD65E412D9C03E3454D748F656FAB377
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64/hr/Firefox%20Setup%20157.0.exe
  InstallerSha256: FB2EE4441E0BD5C91BF55A39341CE6FE65660490700440D043A1D1910FFCEB7D
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64-aarch64/hr/Firefox%20Setup%20157.0.exe
  InstallerSha256: 2BCA4FF55F2E4780FC74CAD5308F7CFFEB12D62F97C29F03C3BB915300253747
ManifestType: installer
ManifestVersion: 1.12.0
