# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Postman.Postman
PackageVersion: 12.30.0
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
UpgradeBehavior: install
Protocols:
- postman
ProductCode: Postman
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://dl.pstmn.io/download/version/12.30.0/windows_64
  InstallerSha256: AD90BC262F02603634EE9498A42657D3D6E69BAEAD65B9B245ED4837D942F18E
ManifestType: installer
ManifestVersion: 1.12.0
