# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: PowerUserZ.OpenTokenUsage
PackageVersion: 0.7.1
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: wix
Scope: machine
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
InstallerSwitches:
  Custom: AUTOLAUNCHAPP=True
ProductCode: '{EF69DDF1-4881-40E8-96E0-C2D2C395ABD3}'
ReleaseDate: 2026-09-28
AppsAndFeaturesEntries:
- Publisher: sunstory
  ProductCode: '{EF69DDF1-4881-40E8-96E0-C2D2C395ABD3}'
  UpgradeCode: '{28D7E68F-C9A6-5E8E-A566-097F6F3B8A75}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%/OpenTokenUsage'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/PowerUserZ/OpenTokenUsage/releases/download/v0.7.1/OpenTokenUsage_0.7.1_x64_en-US.msi
  InstallerSha256: C1E245CD9749BCFC01DC1D2C89AAE6135FAF7D7F9934D3556F4D02F34398FBC6
ManifestType: installer
ManifestVersion: 1.12.0
