# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.en-GB
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox ESR
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win32/en-GB/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 6228FEADBD004C412529576264715F5689E9C6B2BEF2AB6965036F94A5199A20
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64/en-GB/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: F56C59F059D5F580922F0F7566B6CC0084962785766EB7CFA89067F11BD1893B
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64-aarch64/en-GB/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 772F284A97BFA9626A4402AD3850045B82D0FEE7AB33AFC3E3173732C108023E
ManifestType: installer
ManifestVersion: 1.12.0
