# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: axllent.mailpit
PackageVersion: 1.31.3
PackageLocale: en-US
Publisher: Ralph Slooten
PublisherUrl: https://github.com/axllent
PublisherSupportUrl: https://github.com/axllent/mailpit/issues
Author: Ralph Slooten
PackageName: Mailpit
PackageUrl: https://github.com/axllent/mailpit
License: MIT
LicenseUrl: https://github.com/axllent/mailpit/blob/develop/LICENSE
Copyright: Copyright (c) 2022-Now() Ralph Slooten
CopyrightUrl: https://github.com/axllent/mailpit/blob/develop/LICENSE
ShortDescription: An email and SMTP testing tool with API for developers
Description: |-
  Mailpit is a small, fast, low memory, zero-dependency, multi-platform email testing tool & API for
  developers.

  It acts as an SMTP server, provides a modern web interface to view & test captured emails, and
  includes an API for automated integration testing.

  Mailpit was originally inspired by MailHog which is no longer maintained and hasn't seen active
  development or security updates for a few years now.
Moniker: mailpit
Tags:
- email-testing
- go
- golang
- mailpit
- pop3-server
- smtp-relay
- smtp-server
- smtp-testing
ReleaseNotes: |-
  ### Chore
  • Limit maximum MIME parts parsed per message to 500
  • Refactor regex usage for string cleaning and normalization
  • Optimize envelope parsing by using a shared parser instance
  • Optimize message summary construction by eliminating JSON round-trip
  • Replace bytes.ToLower with containsFold for case-insensitive tag matching
  • Replace inline regex for leading whitespace with a package-level variable
  • Symlink sendmail to Mailpit in Docker image ([#736](https://github.com/axllent/mailpit/issues/736))
  • Update Go dependencies
  • Update node dependencies
  • Update GitHub Actions dependencies
ReleaseNotesUrl: https://github.com/axllent/mailpit/releases/tag/v1.31.3
ManifestType: defaultLocale
ManifestVersion: 1.12.0
