# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ByteDance.FeishuRooms
PackageVersion: 7.76.1
InstallerType: nullsoft
Scope: machine
ProductCode: df9d73a0-80d6-524e-a0a1-376fe8586818
ReleaseDate: 2026-09-16
ElevationRequirement: elevationRequired
Installers:
- Architecture: x64
  InstallerUrl: https://sf3-cn.feishucdn.com/obj/ee-entrust/FeishuRooms-x64-7.76.1_20260916200217.exe
  InstallerSha256: 386D7F72A679871B949601718F8B6CF34B5181613A66A93DC147289577330156
ManifestType: installer
ManifestVersion: 1.12.0
