# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: TooYi.IShell
PackageVersion: 3.1.59
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
ProductCode: ishellpro
ReleaseDate: 2026-09-27
Installers:
- Architecture: x64
  InstallerUrl: https://ishell-down.oss-cn-beijing.aliyuncs.com/ishellpro_3.1.59_x64-setup.exe
  InstallerSha256: EDD8A2686EDCD104080CCCF63E64086A43A8E24D43D0139C51282B94453EFEB3
ManifestType: installer
ManifestVersion: 1.12.0
