# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: VaclavJedlicka.ProfiCAD
PackageVersion: 14.1.2
MinimumOSVersion: 10.0.22000.0
InstallerType: inno
Scope: machine
FileExtensions:
- sxe
ProductCode: ProfiCAD_is1
ReleaseDate: 2026-09-28
Installers:
- Architecture: x86
  InstallerUrl: https://www.proficad.com/down/14/setup_full.exe
  InstallerSha256: C47EFC6AE2EF5F6C8CDB72CC80F37A8BA06E33116B7B03C06ED1056CF8B404C0
ManifestType: installer
ManifestVersion: 1.12.0
