# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.es-MX
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox ESR
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win32/es-MX/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 409AA0C9775C08E99D7746781DA70B9521642E80D8A15C4733EB5965877ADA06
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64/es-MX/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 70E0977E295D10E29E5A8A0B41B59384F58FA70A4E831E98C5192C8A2447E1C6
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64-aarch64/es-MX/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: CC675DFC393A0174CCA31EF1B3FDA70711F5F99C1AF2A92AFCE57AB8F2A880E7
ManifestType: installer
ManifestVersion: 1.12.0
