# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: OrcaSVN.OrcaSVN
PackageVersion: 0.6.2
InstallerLocale: en-US
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: OrcaSVN
ReleaseDate: 2026-09-29
AppsAndFeaturesEntries:
- Publisher: orcasvn
  ProductCode: OrcaSVN
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\OrcaSVN'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/wustites/OrcaSVN/releases/download/v0.6.2/OrcaSVN_0.6.2_x64-setup.exe
  InstallerSha256: AEBDC7EC685D9237110264487CF4A47653CEED59AA24A11E033D651EF5EE1988
ManifestType: installer
ManifestVersion: 1.12.0
