# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: SoftDeluxe.FreeDownloadManager
PackageVersion: 6.35.1.7021
PackageLocale: en-GB
Description: |-
  Free Download Manager for Windows, macOS, Android, and Linux allows you to adjust traffic usage, organise downloads, control file priorities for torrents, efficiently download large files and resume broken downloads.
  FDM can boost all your downloads up to 10 times, process media files of various popular formats, drag and drop URLs right from a web browser as well as simultaneously download multiple files!
ManifestType: locale
ManifestVersion: 1.12.0
