# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: co2lab.Anchors
PackageVersion: 0.1.241
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: anchors.exe
  PortableCommandAlias: anchors
Commands:
- anchors
ReleaseDate: 2026-09-30
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/co2-lab/anchors/releases/download/v0.1.241/anchors_0.1.241_windows_amd64.zip
  InstallerSha256: 9BF7E25C2E5838D648E3FB9F678AD1F6AF0A14454D778EBE8825CA5D8C261776
- Architecture: arm64
  InstallerUrl: https://github.com/co2-lab/anchors/releases/download/v0.1.241/anchors_0.1.241_windows_arm64.zip
  InstallerSha256: D27BF92841DA296B0D20D8AAE78E155C0698E362463B27E36692A4BB0BB49BE1
ManifestType: installer
ManifestVersion: 1.12.0
