# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: Hanthor.BluefinCLI
PackageVersion: 0.11.4
PackageLocale: en-US
Publisher: Hanthor
PublisherUrl: https://github.com/tuna-os
PublisherSupportUrl: https://github.com/tuna-os/bluefin-cli/issues
PackageName: BluefinCLI
PackageUrl: https://github.com/tuna-os/bluefin-cli
License: Apache-2.0
LicenseUrl: https://github.com/tuna-os/bluefin-cli/blob/main/LICENSE
Copyright: Copyright 2025 Bluefin CLI contributors
ShortDescription: Modern CLI for managing shell config and dev environment customization on Universal Blue.
Moniker: BluefinCLI
Tags:
- cli
- shell
- bluefin
- universal-blue
ReleaseNotes: |-
  ## [0.11.4](https://github.com/tuna-os/bluefin-cli/compare/v0.11.3...v0.11.4) (2026-09-29)


  ### Bug Fixes

  • **deps:** update module charm.land/bubbletea/v2 to v2.0.10 ([#297](https://github.com/tuna-os/bluefin-cli/issues/297)) ([59b5bc6](https://github.com/tuna-os/bluefin-cli/commit/59b5bc6c8b093843f805b4fba3da0fa178d9d905))
ReleaseNotesUrl: https://github.com/tuna-os/bluefin-cli/releases/tag/v0.11.4
ManifestType: defaultLocale
ManifestVersion: 1.12.0
