# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Tencent.WeType
PackageVersion: 3.0.0.17
InstallerLocale: zh-CN
InstallerType: exe
Scope: machine
InstallerSwitches:
  Silent: /s
  SilentWithProgress: /s
UpgradeBehavior: deny
ProductCode: WeType
ReleaseDate: 2026-09-29
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  InstallerUrl: https://download.z.weixin.qq.com/app/win/WeTypeSetup_3.0.0.17_3.exe
  InstallerSha256: A013E3C2DFA93A0DC30BAB7958920DFF691AA3989A3863FC5019286F6AA64CFD
- Architecture: arm64
  InstallerUrl: https://download.z.weixin.qq.com/app/win/WeTypeSetup_3.0.0.17_3.exe
  InstallerSha256: A013E3C2DFA93A0DC30BAB7958920DFF691AA3989A3863FC5019286F6AA64CFD
ManifestType: installer
ManifestVersion: 1.12.0
