# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Microsoft.Azure.ArcSetup
PackageVersion: '1.68'
InstallerType: portable
Commands:
- arcsetup
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.Azure.ConnectedMachineAgent
ReleaseDate: 2026-09-14
Installers:
- Architecture: x64
  InstallerUrl: https://gbl.his.arc.azure.com/azcmagent/1.68/arcsetup.exe
  InstallerSha256: CADB5CCA467A7840ECD0B606C4CF0F96EC4E6BA322C07121F23C5B0FA867CD34
ManifestType: installer
ManifestVersion: 1.28.0
