# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: blakazulu.Findra
PackageVersion: 0.6.0
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Custom: /INSTALLSOURCE=winget
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/blakazulu/findra/releases/download/v0.6.0/findra-setup-x64.exe
  InstallerSha256: AC40C5D8942F6FCC003A4651802FB80553AAB53C16BE365B1F9291E613835051
- Architecture: arm64
  InstallerUrl: https://github.com/blakazulu/findra/releases/download/v0.6.0/findra-setup-arm64.exe
  InstallerSha256: 8DDD9750998B33606CD7F76DBE0B1D4464F385B24F582E12B9B78E83F4B71872
ManifestType: installer
ManifestVersion: 1.6.0
