# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.si
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox ESR
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win32/si/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 4B90109D7239E131B349409CF44F7D58D2EF7005DB9C515FEF4BF9F929A907E9
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64/si/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: C02937A7E3266E1ED8B8625D128DEC43B0F09689DDD282E5FEF75951632D6498
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64-aarch64/si/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 34200F29843BAB8265B83E91F3CC23C215EA910B9D8808CD0474F23D4385C733
ManifestType: installer
ManifestVersion: 1.12.0
