# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: NimbusAgent.Nimbus
PackageVersion: 7.32.1
InstallerType: wix
ProductCode: '{ED2EBF8B-1E3A-4617-AFCE-8FE182481A26}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/nimbus-agent/Nimbus/releases/download/v7.32.1/nimbus-headless-windows-x64.msi
  InstallerSha256: ACEBE558878A8E3B716548E607450B00362695B6413C5A65CF76281D4C990B0D
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-30
