# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: SecretLUL.WinMedic
PackageVersion: 0.7.0
InstallerType: portable
Commands:
- winmedic
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ReleaseDate: 2026-09-27
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/SecretLUL/WinMedic/releases/download/v0.7.0/winmedic-v0.7.0.exe
  InstallerSha256: AE489F2C667029E06F5B3C239E61CB3B0D4151D36D8191F43FAE9F59251F9E42
ManifestType: installer
ManifestVersion: 1.12.0
