# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: TheGridTrackerTeam.GridTracker2
PackageVersion: 2.260925.2
InstallerType: nullsoft
ProductCode: d49850c2-5bb1-5a36-96e6-a017a4bf99b6
ReleaseDate: 2026-09-26
AppsAndFeaturesEntries:
- ProductCode: d49850c2-5bb1-5a36-96e6-a017a4bf99b6
Installers:
- Architecture: x64
  InstallerUrl: https://download2.gridtracker.org/GridTracker2-2.260925.2-setup.exe
  InstallerSha256: F2BC71FC6C79C5DA45EEA70C15124BDD59254A9E419FF58FF73607F8D141CB92
ManifestType: installer
ManifestVersion: 1.28.0
