# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: dotenvx.dotenvx
PackageVersion: 2.31.0
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: dotenvx.exe
  PortableCommandAlias: dotenvx
UpgradeBehavior: uninstallPrevious
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/dotenvx/dotenvx/releases/download/v2.31.0/dotenvx-2.31.0-windows-x86_64.zip
  InstallerSha256: 55711B9DE4D2F6ECBB42276FE52BBD267A34177881C1323AE10D997A5E0A8DE1
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-27
