PackageIdentifier: ChristofMueller.DeviceShelf
PackageVersion: 1.9.64
InstallerType: nullsoft
Scope: user
InstallModes:
  - interactive
  - silent
  - silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-09-27
Installers:
  - Architecture: x64
    InstallerUrl: https://downloads.deviceshelf.app/DeviceShelf-1.9.64-setup.exe
    InstallerSha256: 19B26DBB1539AFF6CF0025ED6B2B41B624CB5F7E90D11F59FC45832C5C645D37
ManifestType: installer
ManifestVersion: 1.6.0
