# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ntwind.StickyPreviews
PackageVersion: "3.1"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: install
AppsAndFeaturesEntries:
- DisplayName: Sticky Previews
  Publisher: NTWind Software
ElevationRequirement: elevationRequired
Installers:
- Architecture: x86
  InstallerUrl: https://www.ntwind.com/files/StickyPreviews_3.1-setup.exe
  InstallerSha256: 0120207F8DAC690E1D65DF83AABD10212356567104A4FF6F29970AFE7F315593
- Architecture: x64
  InstallerUrl: https://www.ntwind.com/files/StickyPreviews_3.1-setup.exe
  InstallerSha256: 0120207F8DAC690E1D65DF83AABD10212356567104A4FF6F29970AFE7F315593
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-05
