# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Waterfox.Waterfox
PackageVersion: 6.7.5
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: -ms
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Waterfox
ReleaseDate: 2026-09-30
AppsAndFeaturesEntries:
- ProductCode: Waterfox
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  InstallerUrl: https://cdn.waterfox.com/waterfox/releases/6.7.5/WINNT_x86_64/Waterfox%20Setup%206.7.5.exe
  InstallerSha256: AE7806E7A61B668BB0EC7AF13714179B794195626794852D0DFBFB5C8421643D
- Architecture: arm64
  InstallerUrl: https://cdn.waterfox.com/waterfox/releases/6.7.5/WINNT_aarch64/Waterfox%20Setup%206.7.5.exe
  InstallerSha256: 77EE538F26F02EDC50EC7AB5D46F15D9EE74289DCF9576F830E30A8600908993
ManifestType: installer
ManifestVersion: 1.28.0
