# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Dais.Dais
PackageVersion: 0.15.7
UpgradeBehavior: install
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/Dais-Project/Dais/releases/download/app-v0.15.7/Dais_0.15.7_x64-setup.exe
  InstallerSha256: 6356C4170D6F7A4F47E10BB0918BD0F83A2406909B0EA2030AFAC27B24814AD1
  ProductCode: Dais
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/Dais-Project/Dais/releases/download/app-v0.15.7/Dais_0.15.7_x64_en-US.msi
  InstallerSha256: 4C8D2D5507CC7DB46CA9A8CCFCD62A9654A5E8B002AA6C6AED4DF60B43A84783
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  ProductCode: '{BE5856B5-45DB-4ECD-984B-8BBD2824DBDD}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{4F1EF755-A3C3-5E42-B1C3-DA56D31ED950}'
ManifestType: installer
ManifestVersion: 1.12.0
