# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: co2lab.Anchors
PackageVersion: 0.1.219
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: anchors.exe
  PortableCommandAlias: anchors
Commands:
- anchors
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/co2-lab/anchors/releases/download/v0.1.219/anchors_0.1.219_windows_amd64.zip
  InstallerSha256: DB8A59076B9FAB2472E589E924745CA0EA4EEF54C64B9C94CC5D5FE128514C68
- Architecture: arm64
  InstallerUrl: https://github.com/co2-lab/anchors/releases/download/v0.1.219/anchors_0.1.219_windows_arm64.zip
  InstallerSha256: 65EFC215A437C304424C3374473CA5753DDDE2609FE0ADD830A4B8C72636E230
ManifestType: installer
ManifestVersion: 1.12.0
