# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: HetoAndrade.NoteZap
PackageVersion: 1.9.2909
InstallerType: inno
InstallerLocale: pt-BR
Scope: user
InstallModes:
  - interactive
  - silent
  - silentWithProgress
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /SILENT /SUPPRESSMSGBOXES /NORESTART
UpgradeBehavior: install
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/hetoandrade/hetoandrade.github.io/releases/download/notezap-v1.9.2909/NoteZap_Setup_v1.9.2909.exe
    InstallerSha256: 7368277FDB56308DD20D7E9AC23CC8FEE9F84C4D61E8C99B9A30082882BEE9A5
    ProductCode: "{F306435F-8861-42C8-B641-E9D80B540E0A}_is1"
    AppsAndFeaturesEntries:
      - DisplayName: "NoteZap versão 1.9.2909"
        Publisher: "Hetoandrade"
        ProductCode: "{F306435F-8861-42C8-B641-E9D80B540E0A}_is1"
ManifestType: installer
ManifestVersion: 1.10.0
