# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: KDE.Dolphin
PackageVersion: 26.08.1
InstallerType: nullsoft
UpgradeBehavior: install
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://cdn.kde.org/ci-builds/system/dolphin/release-26.08/windows/dolphin-release_26.08-8619-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: EB2AA5CB9E7C49C60A38F2A0CD35BA667088DF8A0812240DA76CDED36588B210
  InstallerSwitches:
    Custom: /CurrentUser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://cdn.kde.org/ci-builds/system/dolphin/release-26.08/windows/dolphin-release_26.08-8619-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: EB2AA5CB9E7C49C60A38F2A0CD35BA667088DF8A0812240DA76CDED36588B210
  InstallerSwitches:
    Custom: /AllUsers
ManifestType: installer
ManifestVersion: 1.12.0
