# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Excelano.xfind
PackageVersion: 1.10.2
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: xfind.exe
  PortableCommandAlias: xfind
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/excelano/xfiles/releases/download/v1.10.2/xfind_1.10.2_windows_amd64.zip
  InstallerSha256: F43FE02CF41048322CF3BA556E79C5C7E929924C69AB2755F580D32E1994ED6B
ManifestType: installer
ManifestVersion: 1.12.0
