# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Serverdata.ElevateUC
PackageVersion: 2.33.58
UpgradeBehavior: install
Protocols:
- gomeet
ReleaseDate: 2026-09-18
Installers:
- Architecture: x86
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://cp.serverdata.net/voice/pbx/softphonereleases/default/latest-win/elevate-uc.exe
  InstallerSha256: 7D326ABE015B0D6AFB3A9DD9CBAAA3D4B688D801471C098FFBD40A2DE21200E0
  InstallerSwitches:
    Upgrade: --updated
    Custom: /currentuser
  ProductCode: c77f9299-6e72-55da-a779-2b144b12f627
- Architecture: x86
  InstallerType: nullsoft
  Scope: machine
  InstallerUrl: https://cp.serverdata.net/voice/pbx/softphonereleases/default/latest-win/elevate-uc.exe
  InstallerSha256: 7D326ABE015B0D6AFB3A9DD9CBAAA3D4B688D801471C098FFBD40A2DE21200E0
  InstallerSwitches:
    Upgrade: --updated
    Custom: /allusers
  ProductCode: c77f9299-6e72-55da-a779-2b144b12f627
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://cp.serverdata.net/voice/pbx/softphonereleases/default/latest-win/elevate-uc.exe
  InstallerSha256: 7D326ABE015B0D6AFB3A9DD9CBAAA3D4B688D801471C098FFBD40A2DE21200E0
  InstallerSwitches:
    Upgrade: --updated
    Custom: /currentuser
  ProductCode: c77f9299-6e72-55da-a779-2b144b12f627
- Architecture: x64
  InstallerType: nullsoft
  Scope: machine
  InstallerUrl: https://cp.serverdata.net/voice/pbx/softphonereleases/default/latest-win/elevate-uc.exe
  InstallerSha256: 7D326ABE015B0D6AFB3A9DD9CBAAA3D4B688D801471C098FFBD40A2DE21200E0
  InstallerSwitches:
    Upgrade: --updated
    Custom: /allusers
  ProductCode: c77f9299-6e72-55da-a779-2b144b12f627
- Architecture: x86
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://cp.serverdata.net/voice/pbx/softphonereleases/default/latest-win/elevate-uc-ia32.msi
  InstallerSha256: A56E6F6EB7E82ABAED8830B9EA2B40EE72CAB0AC49D54916426D618FE616E37C
  InstallerSwitches:
    InstallLocation: APPLICATIONFOLDER="<INSTALLPATH>"
  ProductCode: '{7F9B6223-189B-4F22-AE53-CE9497C21BC7}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{B7411227-AA11-4234-A03F-88494D4F714D}'
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://cp.serverdata.net/voice/pbx/softphonereleases/default/latest-win/elevate-uc-x64.msi
  InstallerSha256: F1C5250B5D105A62D43B45551BED38D334531583E418B4D0199E7A46861A7B68
  InstallerSwitches:
    InstallLocation: APPLICATIONFOLDER="<INSTALLPATH>"
  ProductCode: '{E6CE00AF-5609-406F-9FB6-B335DF4E1653}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{B7411227-AA11-4234-A03F-88494D4F714D}'
ManifestType: installer
ManifestVersion: 1.12.0
