# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Ruben2776.PicView
PackageVersion: 5.1.4
InstallerType: inno
Scope: machine
UpgradeBehavior: install
FileExtensions:
- 3fr
- arw
- bmp
- cr2
- crw
- cut
- dcr
- dds
- dib
- dng
- emf
- erf
- exr
- gif
- hdr
- heic
- ico
- jfif
- jpe
- jpeg
- jpg
- kdc
- mdc
- mef
- mos
- mrw
- nef
- nrw
- orf
- pcx
- pef
- pgm
- png
- psb
- psd
- raf
- raw
- rw2
- srf
- svg
- tga
- tif
- tiff
- wbmp
- webp
- wmf
- wpg
- x3f
- xbm
- xcf
- xpm
ProductCode: '{F102E394-0FA6-4AEA-826D-9FE699115BAB}_is1'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Ruben2776/PicView/releases/download/5.1.4/Setup-PicView-v5.1.4-win-x64.exe
  InstallerSha256: 246F3FD08726DE52452FEB645262B32F8B3A069C63E825AEF2C8B45E96C9570D
- Architecture: arm64
  InstallerUrl: https://github.com/Ruben2776/PicView/releases/download/5.1.4/Setup-PicView-v5.1.4-win-arm64.exe
  InstallerSha256: D0DA80747A6A2695B4632EEE9FCECD0761BE949E999FCEB76799D3C176D98998
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-28
