# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: laurentiu021.SysManager
PackageVersion: 1.114.23
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: portable
Commands:
- SysManager
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/laurentiu021/SystemManager/releases/download/v1.114.23/SysManager-v1.114.23.exe
  InstallerSha256: 22B19457B097BF29C464C37BD887EB50EF5E4C2984425F94C0EF563D609616FD
ManifestType: installer
ManifestVersion: 1.12.0
