# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Google.AndroidCLI
PackageVersion: 1.0.16457483
InstallerType: portable
UpgradeBehavior: install
Commands:
- android
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://dl.google.com/android/cli/1.0.16457483/windows_x86_64/android.exe
  InstallerSha256: 8EEC3F16622693F77B73B4A5581634E29803D11FEDFBD163C484C2273221DBBA
ManifestType: installer
ManifestVersion: 1.12.0
