# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: IOBend.IOBend
PackageVersion: 2.6.4
InstallerLocale: en-US
InstallerType: wix
ProductCode: '{5FEFD46C-71C9-4723-8607-88FE7A3C986B}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Iobend/iobend/releases/download/v2.6.4/IOBend-v2.6.4-win-x64.msi
  InstallerSha256: CEAE344017F3986B32E0DA32D43128B3E084C852D72BF82DC8D47FB339426A04
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-27
