# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.nb-NO
PackageVersion: "157.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win32/nb-NO/Firefox%20Setup%20157.0.exe
  InstallerSha256: DA399A7D164270A39FD675FA41F5CDE3E976009992DACA68B3B2DA3A0725165B
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64/nb-NO/Firefox%20Setup%20157.0.exe
  InstallerSha256: 011D285C36EAC51EB257524288DBA3EFEDF18C57CFE6D1A035273744A14E6A04
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64-aarch64/nb-NO/Firefox%20Setup%20157.0.exe
  InstallerSha256: A0B009579CFE87E1834A559E21EB85DB6144B666BC84113AE05B272BEFACB502
ManifestType: installer
ManifestVersion: 1.12.0
