# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: PlanetScale.CLI
PackageVersion: 0.341.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: pscale.exe
Commands:
- pscale
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/planetscale/cli/releases/download/v0.341.0/pscale_0.341.0_windows_386.zip
  InstallerSha256: 01D4A8E2A50846F792DBD132AC609C1D5AB3DD2643A9F44C322E4E1FF4FE15DE
- Architecture: x64
  InstallerUrl: https://github.com/planetscale/cli/releases/download/v0.341.0/pscale_0.341.0_windows_amd64.zip
  InstallerSha256: 0F89C43913C8E55232AA6E00EE0B5AF166D6C91B564072FCB94BE9904B815B99
- Architecture: arm64
  InstallerUrl: https://github.com/planetscale/cli/releases/download/v0.341.0/pscale_0.341.0_windows_arm64.zip
  InstallerSha256: E67A759C4519BB481DA27702EDF9666648EA9C8F96641F3AD0D641A4CB7E8002
ManifestType: installer
ManifestVersion: 1.28.0
