# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.ka
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox ESR
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win32/ka/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 4FBBEF2F9FAF99E9E091BEEFF21B04BF2D9FB3AE6101C2244FA72283B2408428
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64/ka/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: D8B374B91AC9436F75C9865480AE551FDEB7438D32BCD786D67776F920F20BA8
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64-aarch64/ka/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: FE66BF92965BDC82D8EAC2F84FA684DCA0B446865AD17502B0EC75CAAF93946E
ManifestType: installer
ManifestVersion: 1.12.0
