# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Devolutions.Pinget
PackageVersion: 0.12.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: pinget.exe
ReleaseDate: 2026-09-09
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Devolutions/pinget/releases/download/v0.12.0/pinget-windows-x64.zip
  InstallerSha256: 1AC7F55E8CCB1F1A737F848C812FBDD500EA687DF047A4C8E97FFB59DD9DCF7E
- Architecture: arm64
  InstallerUrl: https://github.com/Devolutions/pinget/releases/download/v0.12.0/pinget-windows-arm64.zip
  InstallerSha256: B584ECDD33DA2EFFCCE0AB33861F8846A8EBAC3A587B51EF6C424AA9930E052A
ManifestType: installer
ManifestVersion: 1.28.0
