# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Paseo.Paseo
PackageVersion: 0.10.0
InstallerType: nullsoft
ProductCode: ca8eee31-e786-591a-8405-a3710823b93a
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/getpaseo/paseo/releases/download/v0.10.0/Paseo-Setup-0.10.0-x64.exe
  InstallerSha256: 4EC31DD5412931FFE674AF6BF039C67120456EABDD39B03A61A0CEA300BCF17F
  InstallerSwitches:
    Custom: /currentuser
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\Programs\Paseo'
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/getpaseo/paseo/releases/download/v0.10.0/Paseo-Setup-0.10.0-x64.exe
  InstallerSha256: 4EC31DD5412931FFE674AF6BF039C67120456EABDD39B03A61A0CEA300BCF17F
  InstallerSwitches:
    Custom: /allusers
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\Paseo'
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/getpaseo/paseo/releases/download/v0.10.0/Paseo-Setup-0.10.0-arm64.exe
  InstallerSha256: A11E3F0F7D763C432C6970B64CF71247E5C88E6FDB9298426B4245B070915973
  InstallerSwitches:
    Custom: /currentuser
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\Programs\Paseo'
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/getpaseo/paseo/releases/download/v0.10.0/Paseo-Setup-0.10.0-arm64.exe
  InstallerSha256: A11E3F0F7D763C432C6970B64CF71247E5C88E6FDB9298426B4245B070915973
  InstallerSwitches:
    Custom: /allusers
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles(x86)%\Paseo'
ManifestType: installer
ManifestVersion: 1.12.0
