# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Excelano.blick
PackageVersion: 0.12.2
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: blick.exe
  PortableCommandAlias: blick
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/excelano/blick-cli/releases/download/v0.12.2/blick_0.12.2_windows_amd64.zip
  InstallerSha256: BFAD5D388645397BE3A0DB4862CB85189F40CC8D73CDB943F7529B49B68396FE
ManifestType: installer
ManifestVersion: 1.12.0
