# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Jackett.Jackett
PackageVersion: 0.24.2738
PackageLocale: en-US
Publisher: Jackett
PublisherUrl: https://github.com/Jackett/Jackett
PublisherSupportUrl: https://github.com/Jackett/Jackett/issues
Author: Jackett Contributors
PackageName: Jackett
PackageUrl: https://github.com/Jackett/Jackett
License: GPL-2.0
LicenseUrl: https://github.com/Jackett/Jackett/blob/HEAD/LICENSE
Copyright: Copyright (C) 1989, 1991 Free Software Foundation, Inc.
CopyrightUrl: https://github.com/Jackett/Jackett/blob/master/LICENSE
ShortDescription: API Support for your favorite torrent trackers.
Description: |-
  Jackett works as a proxy server, it translates queries from apps (Sonarr, Radarr, SickRage, CouchPotato, Mylar, etc) into tracker-site-specific http queries, parses the html response, then sends results back to the requesting software.
  This allows for getting recent uploads (like RSS) and performing searches.
  Jackett is a single repository of maintained indexer scraping and translation logic - removing the burden from other apps.
Moniker: jackett
Tags:
- indexer
- p2p
- proxy
- rss
- sonarr
- torent-management
- torrent
- torrent-search-engine
- trackers
ReleaseNotes: |-
  Changes:
  - 0716462 magnetcat: new alt domains
  - a16eca6 52bt: new domains
  - 6ec31d4 docs(schema): update schema docs (#17134)
  - 8dc2813 docs(schema): fix truncated summaries and broken schema link (#17133)
  - 4b12c48 add phoenixpt a Chinese private site resolves #17131
  - 2a16d0d wolfmax4k: fix content code and enlacito link protector resolves #14511 (#17115)
  - f85e50b add periodical a private site. resolves #17022
  - 195b130 torrentbyte: handle no results resolves #17127
  - f11b71c mactorrentsdownload: drop editor posts resolves #17126
  - aad6248 freejavtorrent: default size for missing ones resolves #17125
  See More
  - 0cb78c0 byrutor: new selectors resolves #17121
  - 3c10b9b extratorrent-st: lint
  - e482127 btdirectory: fix size detection. resolves #17120
  - c2b51f1 extratorrent-st: update cats resolves #17124
  - 9eb3c8b ebookbay: amend cat detection resolves #17123
  - a31aecd catorrent: update cats resolves #17122
  - e846f65 anirena: handle no results resolves #17119
  - 25554f9 0magnet: handle no results resolves #17118
  - 1cc63cb zamundalife: update cats resolves #17129
  - bccf835 sportz247: update cats
  - f7561f2 LDU: update cats
  - d009868 0dayfiles: update cats
  - 67c13ed Update CONTRIBUTING.md
  - c3949ca docs(schema): update schema docs. resolves #13468 (#17116)
  - 2467522 Update azure-pipelines.yml
  - 98828cc Update schema-docs.yml
  - f5b3737 Update schema.json
  - 9b5914c actions: add schema docs workflow #13468
  - 5edc847 bitpalace: removed, down for 30 days. resolves #15296 (#17114)
  This list of changes was auto generated.
ReleaseNotesUrl: https://github.com/Jackett/Jackett/releases/tag/v0.24.2738
ManifestType: defaultLocale
ManifestVersion: 1.12.0
