# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Wondershare.Filmora
PackageVersion: 16.0.10.22341
InstallerType: inno
Scope: user
UpgradeBehavior: install
Protocols:
- fmapplaunch
- fmrespack
FileExtensions:
- wfip
- wfp
- wfpbundle
- wfpbundles
- wfpbundlexii
- wfpbundlexiis
- wfps
- wfpts
- wfpxii
- wfpxiis
ProductCode: Wondershare Filmora 15_is1
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://download.wondershare.com/cbs_down/filmora_64bit_16.0.10_full846.exe
  InstallerSha256: 94D02D4A37408158AF2A1D1A469A62B01CBABD27CF2CEB318B36D8B0BF2500F4
ManifestType: installer
ManifestVersion: 1.12.0
