# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.pt-PT
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox ESR
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win32/pt-PT/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 810CB236179001828452989615E99E1410376A3E4D4C906F7E1BA75D5D9A37C2
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64/pt-PT/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 211B5AD0386728E331D67F2A2A4D93D7652BE81662B084F79EB34ACE0190FBB1
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64-aarch64/pt-PT/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 666A219D407CE8EB4C26151954437444553CA360C4137173E6507BB6B01C1EFC
ManifestType: installer
ManifestVersion: 1.12.0
