# Created with Codex release workflow using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: OpenAI.Codex
PackageVersion: 0.159.2
InstallerType: zip
NestedInstallerType: portable
Commands:
- codex
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: codex-command-runner.exe
  - RelativeFilePath: codex-windows-sandbox-setup.exe
  - RelativeFilePath: codex-x86_64-pc-windows-msvc.exe
    PortableCommandAlias: codex
  InstallerUrl: https://github.com/openai/codex/releases/download/rust-v0.159.2/codex-x86_64-pc-windows-msvc.exe.zip
  InstallerSha256: 583A577B127304EB8CC88C427641D730257EF64DC608C581990CC23EB0161052
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: BurntSushi.ripgrep.MSVC
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  NestedInstallerFiles:
  - RelativeFilePath: codex-aarch64-pc-windows-msvc.exe
    PortableCommandAlias: codex
  - RelativeFilePath: codex-command-runner.exe
  - RelativeFilePath: codex-windows-sandbox-setup.exe
  InstallerUrl: https://github.com/openai/codex/releases/download/rust-v0.159.2/codex-aarch64-pc-windows-msvc.exe.zip
  InstallerSha256: C84578AA147E326CCEE47BCFF2D512A8DCA4DE0E89E977EB9142491C3FA6C055
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: BurntSushi.ripgrep.MSVC
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.12.0
