# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.af
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox ESR
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win32/af/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: F9FB3B77ACAAA6A721787A284D535772E652C3477BC2C9916A0802E7AB4A89ED
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64/af/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 4D093C5F7579E859E8B228531BEC4005D0D382A46ED05A67BA5AA827FDE84D50
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64-aarch64/af/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: F69CFF4EF18CCDB0B5A0F9CCA7766525FE472185B2F88F16CFCD5786897CABCC
ManifestType: installer
ManifestVersion: 1.12.0
