# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Excelano.xtree
PackageVersion: 1.10.2
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: xtree.exe
  PortableCommandAlias: xtree
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/excelano/xfiles/releases/download/v1.10.2/xtree_1.10.2_windows_amd64.zip
  InstallerSha256: E53F165F53F6A882590736DFDC10F92720369D5941632AF71ABF7B2936C2768C
ManifestType: installer
ManifestVersion: 1.12.0
