# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Amazon.AWSCLI
PackageVersion: 2.37.5
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: AWSCLIV2="<INSTALLPATH>"
UpgradeBehavior: install
Commands:
- aws
ProductCode: '{300BE229-2FCE-4CE6-B795-CEE42E6FE012}'
ReleaseDate: 2026-09-28
AppsAndFeaturesEntries:
- UpgradeCode: '{E1C1971C-384E-4D6D-8D02-F1AC48281CF8}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Amazon\AWSCLIV2'
Installers:
- Architecture: x64
  InstallerUrl: https://awscli.amazonaws.com/AWSCLIV2-2.37.5.msi
  InstallerSha256: 20C3764B3D67462A219CF31505195E5E38BBF87F7EC6AE48B67AED6B78E57E51
ManifestType: installer
ManifestVersion: 1.12.0
