# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.rm
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox ESR
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win32/rm/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 8D6003D05F79434DF84FD79A7D9A97103F7534EB801224CA51034609793B137D
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64/rm/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 610B3CB1EF85E0AE464ED25514029D21630CA714B9B23CF9D7C3E9A89A0A791C
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64-aarch64/rm/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 63F47B120A4CAD7963F872C68B5128693629BFE61D792ACB5462EDB7D312BD40
ManifestType: installer
ManifestVersion: 1.12.0
