# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Microsoft.SafetyScanner
PackageVersion: 1.459.468.0
InstallerType: portable
Commands:
- safetyscanner
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://definitionupdates.microsoft.com/packages/content/msert.exe?packageType=Scanner&packageVersion=1.459.468.0&arch=x86
  InstallerSha256: 3DF9DB5C898D1D1E208DC6C2CFC0ED53E0DB24DD42201E52B213A2E1B0889709
- Architecture: x64
  InstallerUrl: https://definitionupdates.microsoft.com/packages/content/msert.exe?packageType=Scanner&packageVersion=1.459.468.0&arch=amd64
  InstallerSha256: 2D8DEE99AE97DE4511DAAE54CC5B8F5AE4CD5328AA2B64D09959A8D81AF3B619
ManifestType: installer
ManifestVersion: 1.28.0
