# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: SergeySvistunov.Uptooda
PackageVersion: 1.4.7
InstallerType: inno
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/zenden2k/uptooda/releases/download/1.4.7/uptooda-1.4.7-build-5524-x64-setup.exe
  InstallerSha256: FC0F0484082DD820FDBB980CB4EE1AB4A0A0B0580B340825BD6C6ED740037160
- Architecture: x86
  InstallerUrl: https://github.com/zenden2k/uptooda/releases/download/1.4.7/uptooda-1.4.7-build-5524-x86-setup.exe
  InstallerSha256: 724D08E51F501172CB5B1F681B6A5B9F20E0CDEB6A017259A991F1DE59390235
- Architecture: arm64
  InstallerUrl: https://github.com/zenden2k/uptooda/releases/download/1.4.7/uptooda-1.4.7-build-5524-arm64-setup.exe
  InstallerSha256: 48161D0BC221619D6270877E9367017E3658EB38D06BD1978AE1CD95907418EC
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-20
