# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ESEngine.ReasonixCLI
PackageVersion: 1.39.2
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: reasonix.exe
Commands:
- reasonix
ReleaseDate: 2026-09-27
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/esengine/DeepSeek-Reasonix/releases/download/v1.39.2/reasonix-windows-amd64.zip
  InstallerSha256: 5DABA70E45AA16AA00C327A88E7F7F06D5EC25A6FA5159A5B79B87D1E917AA4E
- Architecture: arm64
  InstallerUrl: https://github.com/esengine/DeepSeek-Reasonix/releases/download/v1.39.2/reasonix-windows-arm64.zip
  InstallerSha256: BB06D0AC4E036BE16F492EF9F02B604561B825E12C61AA38068CDE70D70A7079
ManifestType: installer
ManifestVersion: 1.12.0
