# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.en-GB
PackageVersion: "157.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win32/en-GB/Firefox%20Setup%20157.0.exe
  InstallerSha256: 8D75071E071B2D33657571B602A4AEDE25308D607341853F1ACF788633357B32
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64/en-GB/Firefox%20Setup%20157.0.exe
  InstallerSha256: 9F3BCB66A77D8CF4615C0BDF57791A5B60E2D73578470B8C6B8485C046FAFF2B
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64-aarch64/en-GB/Firefox%20Setup%20157.0.exe
  InstallerSha256: 41A48F1211CCEE494A39462679BCC12D64BF85831C43170C1FE50C1D3F6788EA
ManifestType: installer
ManifestVersion: 1.12.0
