# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Brave.Brave.Nightly
PackageVersion: 155.1.98.36
InstallerType: exe
ExpectedReturnCodes:
- InstallerReturnCode: -2147219440
  ReturnResponse: cancelledByUser
- InstallerReturnCode: -2147219416
  ReturnResponse: alreadyInstalled
- InstallerReturnCode: -2147218431
  ReturnResponse: invalidParameter
- InstallerReturnCode: -2147024809
  ReturnResponse: invalidParameter
UpgradeBehavior: install
Protocols:
- ftp
- http
- https
- mailto
- tel
FileExtensions:
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: BraveSoftware Brave-Browser
ReleaseDate: 2026-09-28
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.98.36/BraveBrowserStandaloneSilentNightlySetup32.exe
  InstallerSha256: 88A429BF43026C9BC6E7D215260D07EB4FF25473EE37EBFE191C3D3F9BDCBF17
  InstallModes:
  - silent
- Architecture: x86
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.98.36/BraveBrowserStandaloneNightlySetup32.exe
  InstallerSha256: 8466F8821D51738B2CBA1AA2A036731BEEE4F85F515C7DDA247B1B311A41DED4
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.98.36/BraveBrowserStandaloneSilentNightlySetup.exe
  InstallerSha256: B5450D3AE9F2F50014476C266EA22AA183CB30681A70F39A4040420AAB17A58A
  InstallModes:
  - silent
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.98.36/BraveBrowserStandaloneNightlySetup.exe
  InstallerSha256: 7E9B05A90BF4F9220E22CA5DCC806CB1ABCFCB85C8C5D2103EAC8928F490C1F7
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.98.36/BraveBrowserStandaloneSilentNightlySetupArm64.exe
  InstallerSha256: 8EE41D6906B7FBC578FDBF08BBE6367D30F03AC2276120754ABA0562CFC7B646
  InstallModes:
  - silent
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.98.36/BraveBrowserStandaloneNightlySetupArm64.exe
  InstallerSha256: E7742CEC5500A39D8995B94B291F3BB29D8D828E42BDCBC9B0666C8BA5026639
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
ManifestType: installer
ManifestVersion: 1.12.0
