# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: evilmartians.lefthook
PackageVersion: 2.1.15
InstallerType: portable
UpgradeBehavior: install
Commands:
- lefthook
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/evilmartians/lefthook/releases/download/v2.1.15/lefthook_2.1.15_Windows_i386.exe
  InstallerSha256: 976D299BD0BA141A0C7B848E89DCA619B3548374723F9BA2D812C81FB3ED5084
- Architecture: x64
  InstallerUrl: https://github.com/evilmartians/lefthook/releases/download/v2.1.15/lefthook_2.1.15_Windows_x86_64.exe
  InstallerSha256: 6978EC0FF16D2F4283819B3907972EE2F33B266F163B3EA359D0949C6B8A4766
- Architecture: arm64
  InstallerUrl: https://github.com/evilmartians/lefthook/releases/download/v2.1.15/lefthook_2.1.15_Windows_arm64.exe
  InstallerSha256: DA804215F5FF063ED2ED719F1BB352A0947F260A22E524436697BDE1453E88E8
ManifestType: installer
ManifestVersion: 1.12.0
