# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: co2lab.Anchors
PackageVersion: 0.1.217
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: anchors.exe
  PortableCommandAlias: anchors
Commands:
- anchors
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/co2-lab/anchors/releases/download/v0.1.217/anchors_0.1.217_windows_amd64.zip
  InstallerSha256: 4963B80D65D0BF0AB5249784358C7970B6D0845B9832D25B894F67B66AFD888C
- Architecture: arm64
  InstallerUrl: https://github.com/co2-lab/anchors/releases/download/v0.1.217/anchors_0.1.217_windows_arm64.zip
  InstallerSha256: F6BC561D1D0495031EF016BF00A4B5F30288B7F088CDDBF32961616E2D127705
ManifestType: installer
ManifestVersion: 1.12.0
