# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Aserto.Topaz
PackageVersion: 0.33.21
PackageLocale: en-US
Publisher: Aserto
PublisherUrl: https://aserto.com/
PublisherSupportUrl: https://github.com/aserto-dev/topaz/issues
Author: Gert Drapers
PackageName: Topaz
PackageUrl: https://github.com/aserto-dev/topaz
License: Apache-2.0
LicenseUrl: https://github.com/aserto-dev/topaz/blob/HEAD/LICENSE
ShortDescription: ReBAC & ABAC Application Authorization Solution
Tags:
- abac
- access-control
- api
- authorization
- cloud-native
- golang
- opa
- rbac
- rebac
- security
- zanzibar
ReleaseNotes: |-
  Changelog
  - 67d3c5f topaz config info (#766)
  - 773988c upd opa to v1.21.0 (#762)
  - 40486ce upd toolchain (#765)
ReleaseNotesUrl: https://github.com/aserto-dev/topaz/releases/tag/v0.33.21
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/aserto-dev/topaz/wiki
ManifestType: defaultLocale
ManifestVersion: 1.12.0
