# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: XinTaoFei.Codeg
PackageVersion: 0.32.4
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
ProductCode: codeg
ReleaseDate: 2026-09-30
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/xintaofei/codeg/releases/download/v0.32.4/codeg_0.32.4_x64-setup.exe
  InstallerSha256: 82312E9430B4037A98C5953FB5C813CA8D4A56A061E35F1A84F46F411C21991E
- Architecture: arm64
  InstallerUrl: https://github.com/xintaofei/codeg/releases/download/v0.32.4/codeg_0.32.4_arm64-setup.exe
  InstallerSha256: 18A2BF674745F90D8235B17DA6589ED0191690BF7797CDA24678F9E7272DEAAF
ManifestType: installer
ManifestVersion: 1.12.0
