# Automatically updated by the winget bot at 2026/Sep/29
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: OrbForge.Orb.EXE
PackageVersion: 1.6.0
InstallerType: nullsoft
Scope: machine
Protocols:
- orb
ProductCode: Orb Forge Inc.Orb
ReleaseDate: 2026-08-28
Installers:
- Architecture: x64
  InstallerUrl: https://pkgs.orb.net/earlyaccess/windows/Orb-installer.exe
  InstallerSha256: 9A72C0A788DA7C8BAD88B0D78ED0D50C890E101E43AF766E72943CD4E5807D16
ManifestType: installer
ManifestVersion: 1.28.0
