# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.fr
PackageVersion: "157.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win32/fr/Firefox%20Setup%20157.0.exe
  InstallerSha256: EF5D4E5D8D86A3E1960AE7F43B84A0B93E32A8D142C334C17447A8D3618B22A5
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64/fr/Firefox%20Setup%20157.0.exe
  InstallerSha256: 2FEDE9F0A31C4321D61652572E745988106390D52D7FD93762ED7541A9CE7AB4
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64-aarch64/fr/Firefox%20Setup%20157.0.exe
  InstallerSha256: 436DD7BD3B7D6CCDB223E3EB2F4ECBCAA72FCF90BD9EDC2FE77CD70BBD36B52D
ManifestType: installer
ManifestVersion: 1.12.0
