# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: rstream.rstream
PackageVersion: 1.32.7
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: bin/rstream.exe
    PortableCommandAlias: rstream
Installers:
  - Architecture: x64
    InstallerUrl: https://rstream.io/api/packages/cmukbb7h6000004l64xr1bsrk/download
    InstallerSha256: 184a4e0cb55ae551b712d29ce8b41338aba67c2faed29813f1c84e2837e2139a
  - Architecture: arm64
    InstallerUrl: https://rstream.io/api/packages/cmukbb41g001o04l8v7vhtzjy/download
    InstallerSha256: f0eab9420bfb2198ab32fe4696241f3359d421948c21e5835380cd03c60630cc
ManifestType: installer
ManifestVersion: 1.10.0
