# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Google.AndroidStudio.Beta
PackageVersion: 2026.2.1.7
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
InstallerSuccessCodes:
- 1223
UpgradeBehavior: deny
ReleaseDate: 2026-09-28
RequireExplicitUpgrade: true
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  InstallerUrl: https://edgedl.me.gvt1.com/android/studio/install/2026.2.1.7/android-studio-rabbit1-rc2-windows.exe
  InstallerSha256: D41CCC25ED49DBFC80255F6E0C82F22282A08E56A66D35D1B7F5496CF2A1F3BF
ManifestType: installer
ManifestVersion: 1.12.0
