# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Inbjo.MirrorProxy
PackageVersion: 1.4.3
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: mirrorproxy.exe
  PortableCommandAlias: mirrorproxy
Commands:
- mirrorproxy
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/inbjo/MirrorProxy/releases/download/v1.4.3/mirrorproxy-client-x86_64-pc-windows-msvc.zip
  InstallerSha256: 4A9CBE4F4027D1322415BC0B7347B85765705CA69C9D753A5293B3DE1471FDB0
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-30
