# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.sc
PackageVersion: "157.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win32/sc/Firefox%20Setup%20157.0.exe
  InstallerSha256: EC0D59CE0D37D91546F4BC239CBECE808E087031407442FCA46742FD51EA9111
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64/sc/Firefox%20Setup%20157.0.exe
  InstallerSha256: 1E6E78AE01F623F159B43A4FB148E65FF8C90EF1BE01CC13E7B4DCF104490CB1
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64-aarch64/sc/Firefox%20Setup%20157.0.exe
  InstallerSha256: 0206A97F85F56B387D5DF5A39154BC5D645D32B71CE6815ABC995A153704D3D1
ManifestType: installer
ManifestVersion: 1.12.0
