# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Zoho.Cliq
PackageVersion: 1.8.5
UpgradeBehavior: install
Protocols:
- zohocliqapp
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerType: exe
  Scope: user
  InstallerUrl: https://downloads.zohocdn.com/chat-desktop/windows/Cliq_1.8.5_x32.exe
  InstallerSha256: 86857E1D04D566F6D67100A13C88D9D6713DFB2E5482722490F82C45668AA363
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
  ProductCode: cliq
- Architecture: x64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://downloads.zohocdn.com/chat-desktop/windows/Cliq_1.8.5_x64.exe
  InstallerSha256: 6ABB07B37A03C4701A5D1627772C256E10C1CE42B51042FC1A53F44DABD52A7D
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
  ProductCode: cliq
- Architecture: x86
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://downloads.zohocdn.com/chat-desktop/windows/Cliq-1.8.5-x32.msi
  InstallerSha256: 8493BE581F68F4FB1C0DD77C390B7B8B35D9D2D24DC3B5D6896921DCDBD0C448
  InstallerSwitches:
    InstallLocation: APPLICATIONROOTDIRECTORY="<INSTALLPATH>"
  ProductCode: '{BA0D98D8-71B2-4394-B74E-23CDCBD55B8F}'
  AppsAndFeaturesEntries:
  - DisplayName: Cliq Deployment Tool
    UpgradeCode: '{6E41F8CE-742A-5996-84DE-5EC736DE8876}'
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://downloads.zohocdn.com/chat-desktop/windows/Cliq-1.8.5-x64.msi
  InstallerSha256: C8A9917B81578CAE304A3780E3D54B63918697975A02D661E5CEC756EDA1BC04
  InstallerSwitches:
    InstallLocation: APPLICATIONROOTDIRECTORY="<INSTALLPATH>"
  ProductCode: '{1938D9A8-3C09-42D0-8A5D-8643B47D0C6B}'
  AppsAndFeaturesEntries:
  - DisplayName: Cliq Deployment Tool
    UpgradeCode: '{6E41F8CE-742A-5996-84DE-5EC736DE8876}'
ManifestType: installer
ManifestVersion: 1.12.0
