# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: GregorDadera.AIContextBuilder
PackageVersion: 0.5.465.1
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: machine
ElevationRequirement: elevationRequired
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/gregordadera/aicb-roslyn-mcp/releases/download/v0.5.465.1/AIContextBuilder-Setup-0.5.465.1.exe
  InstallerSha256: 9A87319289596BABD567884A8ADB1E702FA97698DC1DEBC461652C5DEB37D4FC
  InstallerSwitches:
    Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
    SilentWithProgress: /SILENT /SUPPRESSMSGBOXES /NORESTART
ManifestType: installer
ManifestVersion: 1.12.0
