# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: AurelioAvila.Redaxa
PackageVersion: 0.4.6
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /S
UpgradeBehavior: install
ProductCode: Redaxa
ReleaseDate: 2026-09-28
AppsAndFeaturesEntries:
- ProductCode: Redaxa
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Redaxa'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/AurelioAvila/redaxa/releases/download/v0.4.6/Redaxa_0.4.6_x64-setup.exe
  InstallerSha256: E9C6812634FA8B1B4760E2A0DD95EEFF3DA324FF74D42847049C03223EDFDE2C
ManifestType: installer
ManifestVersion: 1.12.0
