# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: VovSoft.AIRequester
PackageVersion: 5.4.0.0
InstallerLocale: en-US
Installers:
- Architecture: x86
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://files.vovsoft.com/ai-requester.exe
  InstallerSha256: BAC2EE9DA9C3DC95AA6567D7393AAF1D02A7A13D7948BFD767BB9DD3630829EF
  InstallModes:
  - interactive
  - silent
  - silentWithProgress
  UpgradeBehavior: install
  ProductCode: AI Requester_is1
  AppsAndFeaturesEntries:
  - ProductCode: AI Requester_is1
  ElevationRequirement: elevatesSelf
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\VOVSOFT\AI Requester'
- Architecture: x86
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: airequester.exe
    PortableCommandAlias: airequester
  InstallerUrl: https://files.vovsoft.com/ai-requester-portable.zip
  InstallerSha256: 2A37DA2D01CEB5879230D382B009412D28592C1F50098968782F4CE125079C59
  ArchiveBinariesDependOnPath: true
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-29
