# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Aircall.AircallWorkspace
PackageVersion: 1.18.8
UpgradeBehavior: install
Protocols:
- aircall
- callto
- tel
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://download-electron.aircall.io/aircall-workspace/Aircall-Workspace-1.18.8-x64.exe
  InstallerSha256: 6CE77521A8AB47ABC1B4C0B6DABEB8F897856F7C338C71D0A730EFAA8F049408
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
  ProductCode: 3ec9d337-6374-5d93-9484-d59100254d53
  AppsAndFeaturesEntries:
  - DisplayVersion: 1.18.8
    InstallerType: nullsoft
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://download-electron.aircall.io/aircall-workspace/Aircall-Workspace-1.18.8-x64.msi
  InstallerSha256: B1DF81F429F03CE0FBF24E0C829D23BFF1AE6667A30EEDD11F4857060D4EE331
  InstallerSwitches:
    InstallLocation: APPLICATIONFOLDER="<INSTALLPATH>"
  ProductCode: '{38F6367D-5797-4EEA-8F7D-B6E36CCA85B5}'
  AppsAndFeaturesEntries:
  - DisplayVersion: 1.18.8.71268
    UpgradeCode: '{4267F4EE-71BB-5FAA-9A6A-70660A24E665}'
ManifestType: installer
ManifestVersion: 1.12.0
