# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.bg
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox ESR
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win32/bg/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: ACA1A189B34F746514116FB637ACD7F04499687F1C0CEF4ED21C5424B73BDB54
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64/bg/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: C9766D1874CBD74C075C88A7C1A886BFFFDD21E0F427CF468DA78A0603A101A0
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64-aarch64/bg/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: CAE1645F4579B7947B6FFBDE6D56970C22EDBDC907E201CF0CD5264188BCD51B
ManifestType: installer
ManifestVersion: 1.12.0
