# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.hi-IN
PackageVersion: "157.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win32/hi-IN/Firefox%20Setup%20157.0.exe
  InstallerSha256: 07D1506CE1683994D326BF64331FF36941AD270580BD06E19104F0B173EE64C5
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64/hi-IN/Firefox%20Setup%20157.0.exe
  InstallerSha256: CBFAE791EDE4AC1BBEED6C0F3CC1BA01434E575860C0898097243A40BC8A2305
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64-aarch64/hi-IN/Firefox%20Setup%20157.0.exe
  InstallerSha256: 0D59AA044939FBD65AB71C74DB00EB987D54F0803A6B228A138FC4AD7886084B
ManifestType: installer
ManifestVersion: 1.12.0
