# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Buildkite.CLI
PackageVersion: 3.58.0
PackageLocale: en-US
Publisher: Buildkite Pty. Ltd.
PublisherUrl: https://buildkite.com/home/
PublisherSupportUrl: https://forum.buildkite.community/
Author: Buildkite Pty. Ltd.
PackageName: Buildkite CLI
PackageUrl: https://buildkite.com/docs/platform/cli
License: MIT
LicenseUrl: https://github.com/buildkite/cli/blob/HEAD/LICENSE.md
Copyright: Copyright (c) 2014-2026 Buildkite Pty Ltd
CopyrightUrl: https://github.com/buildkite/cli/blob/HEAD/LICENSE.md
ShortDescription: A command line interface for Buildkite.
Description: |-
  The Buildkite CLI is a command-line interface (CLI) tool for interacting directly with the Buildkite platform itself. This tool provides command line/terminal access to work with a subset of the Buildkite platform's features, as you normally would through its web interface.

  Using the Buildkite CLI, you can manage Buildkite agents and their configuration, work with a Buildkite pipeline's builds, control job execution, and manipulate its artifacts, along with several other actions.
Moniker: buildkite-cli
Tags:
- buildkite
- cd
- ci
- ci-cd
- continuous-integration
ReleaseNotes: |-
  Changelog
  - 2269c15: Omit cluster secret request bodies from REST debug logs (#959) (@lox)
  - 93676fc: Track CLI commands with a stable privacy-safe PostHog schema (#999) (@PriyaSudip)
  - f8fd364: fix(deps): update module github.com/posthog/posthog-go to v1.25.3 (#1000) (@renovate[bot])
  - 9c4957a: Support stdin request bodies in bk api (#1001) (@lox)
  - b358993: fix(deps): update module github.com/posthog/posthog-go to v1.26.0 (#1002) (@renovate[bot])
  - a2d429c: fix(deps): update module github.com/posthog/posthog-go to v1.27.0 (#1003) (@renovate[bot])
  - 3d39b72: Support repeated --path flags for artifacts (#1005) (@mcncl)
ReleaseNotesUrl: https://github.com/buildkite/cli/releases/tag/v3.58.0
Documentations:
- DocumentLabel: Docs
  DocumentUrl: https://buildkite.com/docs/platform/cli
ManifestType: defaultLocale
ManifestVersion: 1.12.0
