# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Buildkite.CLI
PackageVersion: 3.58.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: bk.exe
  PortableCommandAlias: bk
UpgradeBehavior: install
Commands:
- bk
ReleaseDate: 2026-09-27
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/buildkite/cli/releases/download/v3.58.0/bk_3.58.0_windows_amd64.zip
  InstallerSha256: 5B7F287216E8427431037F3547B4B9550659BED212BD90BCC629D42828A31D87
- Architecture: arm64
  InstallerUrl: https://github.com/buildkite/cli/releases/download/v3.58.0/bk_3.58.0_windows_arm64.zip
  InstallerSha256: 833B5E93EBC6110D908ED537B46B0FD418962ABF22D2BFCD3D67529EBCD9E9CD
ManifestType: installer
ManifestVersion: 1.12.0
