# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.cy
PackageVersion: "157.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win32/cy/Firefox%20Setup%20157.0.exe
  InstallerSha256: 5BEDACB2915E1E2F9AF185A088969F4B90D73CB15ED5F4001D6332D8180FF5FD
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64/cy/Firefox%20Setup%20157.0.exe
  InstallerSha256: B90422DCAD958412DA7A12A474139846A77B300F7A2CBA788AFB3C6B79F4D619
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64-aarch64/cy/Firefox%20Setup%20157.0.exe
  InstallerSha256: DA4B4219FF7370C19E11BA453D73BD64FC27B6544909634B4A3B09F893F69EEC
ManifestType: installer
ManifestVersion: 1.12.0
