# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Discord.Discord.Canary.arm64
PackageVersion: 1.0.527
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Protocols:
- discord
ProductCode: DiscordCanary
ReleaseDate: 2026-09-28
Installers:
- Architecture: arm64
  InstallerUrl: https://canary.dl2.discordapp.net/distro/app/canary/win/arm64/1.0.527/DiscordCanarySetup.exe
  InstallerSha256: 3D01B24EB40AA29D657D4FA8FF3254F3F13D2EEFB333A67E2E861FDE16592B2E
ManifestType: installer
ManifestVersion: 1.12.0
