# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Vivaldi.Vivaldi
PackageVersion: 8.2.4133.80
InstallerType: exe
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: --vivaldi-silent
  SilentWithProgress: --vivaldi-silent
  InstallLocation: --vivaldi-install-dir="<INSTALLPATH>"
  Log: --verbose-logging --log-file="<LOGPATH>"
ExpectedReturnCodes:
- InstallerReturnCode: 60
  ReturnResponse: installInProgress
- InstallerReturnCode: 22
  ReturnResponse: cancelledByUser
- InstallerReturnCode: 7
  ReturnResponse: cancelledByUser
- InstallerReturnCode: 4
  ReturnResponse: downgrade
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
- tel
FileExtensions:
- apng
- flac
- gif
- htm
- html
- ico
- jpeg
- jpg
- log
- m4v
- mht
- mhtml
- mp3
- mp4
- ogg
- pdf
- png
- shtml
- svg
- txt
- webp
- xht
- xhtml
- xml
ProductCode: Vivaldi
ReleaseDate: 2026-09-30
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://downloads.vivaldi.com/stable/Vivaldi.8.2.4133.80.exe
  InstallerSha256: 05D45F7DDE45C49CC5489D2857EC03CD281E8B698C0B465E3B788930F3FADF0A
  InstallerSwitches:
    Custom: --do-not-launch-chrome
- Architecture: x86
  Scope: machine
  InstallerUrl: https://downloads.vivaldi.com/stable/Vivaldi.8.2.4133.80.exe
  InstallerSha256: 05D45F7DDE45C49CC5489D2857EC03CD281E8B698C0B465E3B788930F3FADF0A
  InstallerSwitches:
    Custom: --do-not-launch-chrome --system-level
- Architecture: x64
  Scope: user
  InstallerUrl: https://downloads.vivaldi.com/stable/Vivaldi.8.2.4133.80.x64.exe
  InstallerSha256: 94C6AD434FF20C09D67CA5647B2CB48C84E727F8084A455C6A0BC822F34FEC3A
  InstallerSwitches:
    Custom: --do-not-launch-chrome
- Architecture: x64
  Scope: machine
  InstallerUrl: https://downloads.vivaldi.com/stable/Vivaldi.8.2.4133.80.x64.exe
  InstallerSha256: 94C6AD434FF20C09D67CA5647B2CB48C84E727F8084A455C6A0BC822F34FEC3A
  InstallerSwitches:
    Custom: --do-not-launch-chrome --system-level
- Architecture: arm64
  Scope: user
  InstallerUrl: https://downloads.vivaldi.com/stable/Vivaldi.8.2.4133.80.arm64.exe
  InstallerSha256: 7BBC749F684BB33D7709A64A4F2D5ACA1BDDF00FBBF2CE47570BC2F57B8B35C8
  InstallerSwitches:
    Custom: --do-not-launch-chrome
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://downloads.vivaldi.com/stable/Vivaldi.8.2.4133.80.arm64.exe
  InstallerSha256: 7BBC749F684BB33D7709A64A4F2D5ACA1BDDF00FBBF2CE47570BC2F57B8B35C8
  InstallerSwitches:
    Custom: --do-not-launch-chrome --system-level
ManifestType: installer
ManifestVersion: 1.12.0
