# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.es-ES
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox ESR
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win32/es-ES/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 8F4512097CE9D4EADD1802A700B762E5C515F086475D55698425C3E8CACE6CB4
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64/es-ES/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 3B7294938B87774A30CB8975EC55C9E8E61AAA0D02757404CC434ADAAA9A9690
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64-aarch64/es-ES/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 885F72A1B71718E767277CF8B618D55C2D1219B60E645ABB438FEC27E459FE96
ManifestType: installer
ManifestVersion: 1.12.0
