# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: hongfeiyucode.DeepSeekHarnessDesktop
PackageVersion: 0.1.7-rc.2.0
InstallerType: nullsoft
ProductCode: 8130bffd-e844-54a3-92cb-3efa89c19b34
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/hongfeiyucode/deepseek-harness-desktop/releases/download/desktop-v0.1.7-rc.2.0/DeepSeek.Harness.Desktop.Setup.0.1.7-rc.2.0.exe
  InstallerSha256: 61530B5471A589037181EC2F36B76E6594F78EB2B89E4261FFDA6297A1E43253
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/hongfeiyucode/deepseek-harness-desktop/releases/download/desktop-v0.1.7-rc.2.0/DeepSeek.Harness.Desktop.Setup.0.1.7-rc.2.0.exe
  InstallerSha256: 61530B5471A589037181EC2F36B76E6594F78EB2B89E4261FFDA6297A1E43253
  InstallerSwitches:
    Custom: /allusers
ManifestType: installer
ManifestVersion: 1.12.0
