# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: SnowMint.FluentScrobbler
PackageVersion: 1.1.0
InstallerLocale: en-US
InstallerType: inno
Scope: user
ProductCode: Fluent Scrobbler_is1
ReleaseDate: 2026-09-28
AppsAndFeaturesEntries:
- ProductCode: Fluent Scrobbler_is1
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\FluentScrobbler'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/snw-mint/fluent-scrobbler/releases/download/v1.1/FluentScrobbler-Setup-x64.exe
  InstallerSha256: 7FAB0C1BAD03C4DC1D0956556BDAE845BEE4A509B8AF9202E34DDA8CBA69D750
- Architecture: arm64
  InstallerUrl: https://github.com/snw-mint/fluent-scrobbler/releases/download/v1.1/FluentScrobbler-Setup-arm64.exe
  InstallerSha256: 0079884D5F9DDD8F7632922D582BD8E3794E74070569D221208C9FB639DD5241
ManifestType: installer
ManifestVersion: 1.12.0
