# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ESEngine.ReasonixDesktop
PackageVersion: 1.39.2
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
ProductCode: ReasonixReasonix
ReleaseDate: 2026-09-27
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/esengine/DeepSeek-Reasonix/releases/download/desktop-v1.39.2/Reasonix-windows-amd64-installer.exe
  InstallerSha256: D3F744300424F9DD306BE5F7308DBA904704D16AFA2D6CC8D2E5AE4BBD3D2974
ManifestType: installer
ManifestVersion: 1.12.0
