# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: CatoNetworks.CatoClient
PackageVersion: 6.12.6.9050
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLFOLDER="<INSTALLPATH>"
  Upgrade: CATO_AUTOMATIC_UPGRADE=1
UpgradeBehavior: install
Protocols:
- catoias
FileExtensions:
- ccst
ProductCode: '{577CEFD5-EC29-4CA9-97A9-05C5FB1F701A}'
ReleaseDate: 2026-08-16
AppsAndFeaturesEntries:
- UpgradeCode: '{E72B4A8E-159B-4616-BEEB-A517E8F32151}'
ElevationRequirement: elevationRequired
Installers:
- Architecture: x64
  InstallerUrl: https://clients.catonetworks.com/windows/6.12.6.9050/setup.msi
  InstallerSha256: 811FBB170441551B5ED967DA8A154526C63231164D8B28CA340989E479033741
ManifestType: installer
ManifestVersion: 1.12.0
