# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ntwind.ClipboardRemote
PackageVersion: 2.0.3
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: install
AppsAndFeaturesEntries:
- DisplayName: Clipboard Remote
  Publisher: NTWIND LLC
ElevationRequirement: elevationRequired
Installers:
- Architecture: x64
  InstallerUrl: https://www.ntwind.com/files/ClipboardRemote_2.0.3-win-x64.exe
  InstallerSha256: 59D9DCCCDAF5B5D2E0929E367D23C9FCA18BD110001E97CD5945DBBB3091ED91
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-03
