# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.is
PackageVersion: "157.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win32/is/Firefox%20Setup%20157.0.exe
  InstallerSha256: 70FAE7BE97657CD17911299073591FA3B0B07C12BDD4608C236EB8CB3FAA009E
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64/is/Firefox%20Setup%20157.0.exe
  InstallerSha256: 7155E3B5A0ACFDC4193A6FBA84EB3CCE1FC009FC1D781EC50CBF8E07F8768F75
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64-aarch64/is/Firefox%20Setup%20157.0.exe
  InstallerSha256: 01C8559D60CA00D280A8003C72801548918955A42E800A36B2030084E5EB7B79
ManifestType: installer
ManifestVersion: 1.12.0
