# Created with WinGet Updater using komac v2.15.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: QGIS.QField
PackageVersion: 4.3.4
PackageLocale: en-US
Publisher: QGIS
PublisherUrl: https://github.com/opengisch
PublisherSupportUrl: https://github.com/opengisch/QField/issues
PackageName: QField
PackageUrl: https://github.com/opengisch/QField
License: GPL-2.0
LicenseUrl: https://github.com/opengisch/QField/blob/HEAD/LICENSE
ShortDescription: A simplified touch optimized interface for QGIS in the field.
Tags:
- android
- gis
- ios
- linux
- macos
- mobile
- qgis
- qml
- windows
ReleaseNotes: |-
  What's Changed
  - Fix project translation failure to match app locale when available
  - Allow for folders to be deleted in non-folder view to clear up imported / created projects
  - Fix for cloudify button and project creation interference between cloudify and clone/template
  - Fix permission issue with files generated by the image sketcher
  - Fix dashboard editing toggle switch padding by
  - Add an object name to the identify tool item for plugins to access and customize
  - Fix missing global/project/map settings expression context when rendering the map texture for the 3D map view
  - Fix loss of location metadata when rotating / mirroring camera images
  - Show upload progress on the upload button instead of the busy page
  - Fix inverted lighting on 3D polygon fills and walls
  - Insure that the add child feature actions within relation editors are only visible when the project configuration allows for it
  - Apply eye of dome lighting effect on the terrain instead of the View3D to avoid rendering on top of geometry overlays
  - Restore value relation search speed by bailing out of unaccented searches for large datasets
  Full Changelog: v4.3.3...v4.3.4
ReleaseNotesUrl: https://github.com/opengisch/QField/releases/tag/v4.3.4
ManifestType: defaultLocale
ManifestVersion: 1.12.0
