# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: wingtk.gvsbuild.GTK4
PackageVersion: 2026.8.0
PackageLocale: en-US
Publisher: wingtk
PublisherUrl: https://github.com/wingtk
PublisherSupportUrl: https://github.com/wingtk/gvsbuild/issues
PackageName: gvsbuild
PackageUrl: https://github.com/wingtk/gvsbuild
License: GPLv2
ShortDescription: Comes with the tools needed to run GTK on Windows, including GTK4, Cairo, PyGObject, Pycairo, GtkSourceView5, adwaita-icon-theme, and all of their dependencies.
Tags:
- adwaita-icon-theme
- adwaitaicontheme
- cairo
- gtk-4
- gtksourceview5
- pygobject
- requirescmd
ReleaseNotes: |-
  Changes
  - Skip clone if archive exists @saste (#1818)
  - Update libpsl to 0.23.1 and patch date @danyeaw (#1815)
  - GLib 2.88.3, GStreamer 1.28.5, and other updates @danyeaw (#1814)
  - Use glob pattern for x264 PDB file installation @AlessandroBono (#1808)
  - Update go hash for 1.26.4 @VedaviBalaji (#1811)
  - Bump wing from 0.3.24 to 0.3.26 @VedaviBalaji (#1809)
  - fix building expat @zhw2101024 (#1799)
  - Use glob patterns for FFmpeg PDB file installation @AlessandroBono (#1804)
  - Include project version in the tarball @AlessandroBono (#1795)
  - Fetch only @Ytsejam76 (#1792)
  - Handle None value for skip in make_graph @hwf1324 (#1785)
  Thanks again to @AlessandroBono, @danyeaw, @hwf1324, @saste, @VedaviBalaji, @Ytsejam76, @zhw2101024, Stefano Sabatini and Vedavi Balaji! 🎉
ReleaseNotesUrl: https://github.com/wingtk/gvsbuild/releases/tag/2026.8.0
ManifestType: defaultLocale
ManifestVersion: 1.12.0
