# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: Microsoft.PerfView
PackageVersion: 3.2.8
InstallerType: portable
Commands:
- perfview
ReleaseDate: 2026-09-28
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/microsoft/perfview/releases/download/v3.2.8/PerfView.exe
  InstallerSha256: E6B89A6DA0FE7DA5F64302306153C6AAC7A4BE67C800426A91AE014093E4DF2D
ManifestType: installer
ManifestVersion: 1.12.0
