# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: FunRoutine.WorkFlowy
PackageVersion: 4.3.2609291146
InstallerType: nullsoft
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
Protocols:
- workflowy
ProductCode: 338bed7b-1324-505d-8cb6-5c266cbaa6b3
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/workflowy/desktop/releases/download/v4.3.2609291146/WorkFlowy-Installer-4.3.2609291146.exe
  InstallerSha256: 15E5B31EFDE502F95FA4C81373B782AF84694AACF05B7ECC5B7A70DC2044A3AE
- Architecture: x64
  InstallerUrl: https://github.com/workflowy/desktop/releases/download/v4.3.2609291146/WorkFlowy-Installer-4.3.2609291146.exe
  InstallerSha256: 15E5B31EFDE502F95FA4C81373B782AF84694AACF05B7ECC5B7A70DC2044A3AE
ManifestType: installer
ManifestVersion: 1.12.0
