# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.bg
PackageVersion: "157.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win32/bg/Firefox%20Setup%20157.0.exe
  InstallerSha256: 12FFB1043C078B2F0EE626146CD2BF4935F1BC08478F592BAE9A813648506D53
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64/bg/Firefox%20Setup%20157.0.exe
  InstallerSha256: C777351B1A843BC2E47CECFEFE56B62AA0E9E2D93F088DDB13B04A32E551E92A
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64-aarch64/bg/Firefox%20Setup%20157.0.exe
  InstallerSha256: 45166DD97D01CC38CD1CCC018A942312B28544BC1D49D0927E5B5C8DAAA149B2
ManifestType: installer
ManifestVersion: 1.12.0
