# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.fy-NL
PackageVersion: "157.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win32/fy-NL/Firefox%20Setup%20157.0.exe
  InstallerSha256: 88F50239BDB862E7D24AF414CB69C65D3F63459419759FBC80B99F4F452BF061
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64/fy-NL/Firefox%20Setup%20157.0.exe
  InstallerSha256: 6D7D5CA11A335DC160767945914B27A5D3CB4F8BEE35A5636C2F0B15079A95DD
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64-aarch64/fy-NL/Firefox%20Setup%20157.0.exe
  InstallerSha256: 5A1793588E638689A7F764E596BF182FD7E92DA2971CA75887B7EA143018FFF6
ManifestType: installer
ManifestVersion: 1.12.0
