# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Tricerat.ScrewDriversClient
PackageVersion: 7.9.7.21357
InstallerType: msi
Scope: machine
InstallerSwitches:
  InstallLocation: APPDIR="<INSTALLPATH>"
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x86
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ProductCode: '{C04466F4-9C23-4FF2-8B0A-CD34958F1853}'
ReleaseDate: 2026-09-28
AppsAndFeaturesEntries:
- UpgradeCode: '{6CE3200F-E515-4D06-976F-73007971AF04}'
Installers:
- Architecture: x64
  InstallerUrl: https://www.tricerat.com/hubfs/ScrewDriversClient_7.9.7.21357_x64.msi
  InstallerSha256: 756D0FFDEDEEB3882E30C80BF68407901A0A7B8FC384717885B404D0B5CA5934
ManifestType: installer
ManifestVersion: 1.12.0
