# Created with WinGet Tracker using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: t8y2.DBX
PackageVersion: 0.6.26
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: DBX
ReleaseDate: 2026-09-27
AppsAndFeaturesEntries:
- Publisher: dbx
  ProductCode: DBX
InstallationMetadata:
  DefaultInstallLocation: placeholder\DBX
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/t8y2/dbx/releases/download/v0.6.26/DBX_0.6.26_x64-setup.exe
  InstallerSha256: DD2E65DD04F0770CAB8346E02944EB446474BCCAA3F6A0C18FD643780A90D06C
ManifestType: installer
ManifestVersion: 1.12.0
