# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: YACReader.YACReader
PackageVersion: 10.3.2
PackageLocale: en-US
Publisher: YACReader
PublisherUrl: https://www.yacreader.com/
PublisherSupportUrl: https://github.com/YACReader/yacreader/issues
Author: YACReader
PackageName: YACReader
PackageUrl: https://www.yacreader.com/
License: GPL-3.0
LicenseUrl: https://github.com/YACReader/yacreader/blob/develop/COPYING.txt
Copyright: Copyright (C) 2007 Free Software Foundation, Inc.
CopyrightUrl: https://github.com/YACReader/yacreader/blob/develop/COPYING.txt
ShortDescription: Read, browse and manage your comics collection.
Moniker: yacreader
Tags:
- comic
- comics
- read
- reader
- yacreader
ReleaseNotes: |-
  YACReader
  - Improve double page layout stability when going back and forth after finding single image exceptions.
  - Add more system information about the rendering pipelines used.
  - Improve zooming performance in the regular reading mode.
  - Fix unnecessary animation when the flow is shown.
  - Fix continuous scroll mode not updating the flow.
  - Fix bookmarks when continuous scroll mode is used.
  - Fix saving pages in continuous scroll mode.
  - Fix saving/exporting while pages are still missing.

  All GUI apps
  - Fix performance degradation on high-resolution screens. This has affected builds using Qt 6.5 or later. It's a deep change, so please let me know if you find any issues in the flow views or grid views.

  All apps
  - Fix sorting when using Qt builds without ICU. This mostly affected Linux users.
ReleaseNotesUrl: https://github.com/YACReader/yacreader/releases/tag/10.3.2
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/YACReader/yacreader/wiki
ManifestType: defaultLocale
ManifestVersion: 1.12.0
