# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: YACReader.YACReader
PackageVersion: 10.3.2
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{019AC70F-0312-76B8-BD8F-BE9DCBF49E25}_is1'
ReleaseDate: 2026-09-28
AppsAndFeaturesEntries:
- DisplayVersion: 10.3.2.260928407
  ProductCode: '{019AC70F-0312-76B8-BD8F-BE9DCBF49E25}_is1'
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\YACReader'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/YACReader/yacreader/releases/download/10.3.2/YACReader-v10.3.2.260928407-winx64-7z-qt6.exe
  InstallerSha256: 2F1456DB5A1A6C5585D45643135AA8C280FFBC60B68B09E2BFEDEFBE593E5A44
- Architecture: arm64
  InstallerUrl: https://github.com/YACReader/yacreader/releases/download/10.3.2/YACReader-v10.3.2.260928407-winarm64-7z-qt6.exe
  InstallerSha256: BC4C025CE2541DA4130770C3A0AFCDED5875E31E5400DC615409D3F704E2FC45
ManifestType: installer
ManifestVersion: 1.12.0
