# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: misxzaiz.Polaris
PackageVersion: 10.5.8
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
UpgradeBehavior: install
ProductCode: '{4ABA5F16-E1F4-4F9F-805E-7389B7581979}'
ReleaseDate: 2026-09-28
AppsAndFeaturesEntries:
- UpgradeCode: '{B90F6FC4-DDEE-59A6-9DE8-49A41A495360}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/misxzaiz/Polaris/releases/download/v10.5.8/polaris_10.5.8_x64_en-US.msi
  InstallerSha256: 6ED436CE2F8D41F6305B896CA00C38A0A3853F5644415D217DEBF41155FFCBC4
ManifestType: installer
ManifestVersion: 1.12.0
