# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: RebonAI.RebonDesktop
PackageVersion: 1.7.2
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
ProductCode: Rebon
ReleaseDate: 2026-09-27
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/RebonAI/Rebon-Code/releases/download/app-v1.7.2/Rebon_1.7.2_x64-setup.exe
  InstallerSha256: 34ABDB2E25E9B047D8F129AA99D6B9DD92B2133A34080C90F502E32FEF2D9952
ManifestType: installer
ManifestVersion: 1.12.0
