# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: Fly-io.flyctl
PackageVersion: 0.4.110
PackageLocale: en-US
Publisher: Fly.io
PublisherUrl: https://fly.io/
PublisherSupportUrl: https://community.fly.io/
PrivacyUrl: https://fly.io/legal/privacy-policy
PackageName: flyctl
PackageUrl: https://github.com/superfly/flyctl
License: Apache-2.0
LicenseUrl: https://github.com/superfly/flyctl/blob/HEAD/LICENSE
ShortDescription: Command line tools for fly.io services
Tags:
- cli
- fly
- heroku
ReleaseNotes: |-
  ## Changelog
  • 7951745a09f1e5dd869e0d3924a50ce092311ac7 Retry 404s during machine smoke checks. (#5247)
  • 3660e18cf63a59706666352f0c3259d907f0c512 Revert "Allow fdaf::/16 and fdaa::3/128 over wg tunnels" (#5248)
  • a29728d8dbfe18713ffa307be2324c79d95c2256 Allow fdaf::/16 and fdaa::3/128 over wg tunnels (#5244)
ReleaseNotesUrl: https://github.com/superfly/flyctl/releases/tag/v0.4.110
ManifestType: defaultLocale
ManifestVersion: 1.12.0
