# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: Fly-io.flyctl
PackageVersion: 0.4.110
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: flyctl.exe
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/superfly/flyctl/releases/download/v0.4.110/flyctl_0.4.110_Windows_x86_64.zip
  InstallerSha256: A44E972EA401B5ECE290C477E8721DB81C0F34FFA01AF2BCF8306D86972D9575
- Architecture: arm64
  InstallerUrl: https://github.com/superfly/flyctl/releases/download/v0.4.110/flyctl_0.4.110_Windows_arm64.zip
  InstallerSha256: E4096BBB054FEAD6D49DBDBF5168AD9141937C9D9A3204EDD5C8D3F14888FD93
ManifestType: installer
ManifestVersion: 1.12.0
