# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.ko
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox ESR
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win32/ko/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 5C33AF05C9897D6C2EFE8AB8F08A19834082F61AA1112E09EEC6CDE5AA5BB033
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64/ko/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 623582CCCCEB4D371DB3E98AB572D47093E31188FE146DC693844323B9652E24
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64-aarch64/ko/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 8BC0EA7FD4A15D7E514A01DCF88E055941D13751505662F1993B6BB792991A8A
ManifestType: installer
ManifestVersion: 1.12.0
