# Created with sumologic-otel-collector-packaging using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Sumologic.OtelcolSumo
PackageVersion: 0.161.0.3119
InstallerLocale: en-US
InstallerType: wix
Scope: machine
UpgradeBehavior: install
ProductCode: '{F081724B-FBC3-4C51-90C4-64AB6C3A7981}'
ReleaseDate: 2026-09-29
AppsAndFeaturesEntries:
- DisplayName: OpenTelemetry Collector
  ProductCode: '{F081724B-FBC3-4C51-90C4-64AB6C3A7981}'
  UpgradeCode: '{33D8E84A-1581-41DC-AF17-E48459B895C5}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%/./Sumo Logic/OpenTelemetry Collector'
Installers:
- Architecture: x64
  InstallerUrl: https://download-otel.sumologic.com/0.161.0-3119/otelcol-sumo_0.161.0.3119_en-US.x64.msi
  InstallerSha256: 545230B0AA6D750AE05FBA3E1D0C586D9099A72E4517512FE82860356EA0EEED
ManifestType: installer
ManifestVersion: 1.12.0
