# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.mk
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox ESR
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win32/mk/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 596D7CC08DB8739052613A40F50EEB25F843BCD7F4483F412E35BC6B90CA8F80
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64/mk/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 12C71CC9B956BE0E8C6B29C97C2F0762FB8B8449A96166D31F1FE435D22C4F25
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64-aarch64/mk/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 6E97F2AADC5D182EA7DBE1852E69090E43EBACBAD851B44B01BBDC06F78CFFF5
ManifestType: installer
ManifestVersion: 1.12.0
