# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Nextmv.CLI
PackageVersion: 1.11.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: nextmv.exe
  PortableCommandAlias: nextmv
Commands:
- nextmv
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/nextmv-io/nextmv-py/releases/download/nextmv-v1.11.1/nextmv-windows-x64.zip
  InstallerSha256: 5F9C98C90815A0081675DEC28702F6407A7299C59F216B943B702A3F3CEF2C6E
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-29
