# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Namespace.nsc
PackageVersion: 0.0.580
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: bazel-credential-nsc.exe
- RelativeFilePath: docker-credential-nsc.exe
- RelativeFilePath: nsc.exe
Commands:
- nsc
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://get.namespace.so/packages/nsc/v0.0.580/nsc_0.0.580_windows_amd64.zip
  InstallerSha256: 8BEFCF8107800CFD36636167205BD9D33FBB339B6B9F824519D623AF260159DF
- Architecture: arm64
  InstallerUrl: https://get.namespace.so/packages/nsc/v0.0.580/nsc_0.0.580_windows_arm64.zip
  InstallerSha256: 5121FD33014B1BF37592815D11609273A60E54F899411D5A44B0F1BC8CB5A2BB
ManifestType: installer
ManifestVersion: 1.12.0
