# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: 8BitDo.UltimateSoftwareV2
PackageVersion: '1.36'
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: 8BitDo_Ultimate_Software_V2_Windows_V1.36/8BitDo Ultimate Software V2.exe
FileExtensions:
- exe
ReleaseDate: 2026-09-28
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://support.8bitdo.com/bd-uploads/files/ultimate_soft/8BitDo_Ultimate_Software_V2_Windows_V1.36.zip
  InstallerSha256: EDDDBD407FABDC0D2264B8FD553B59F46F8D4D404E6D98C3FE171571EF204AA7
ManifestType: installer
ManifestVersion: 1.28.0
