# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.hy-AM
PackageVersion: "157.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win32/hy-AM/Firefox%20Setup%20157.0.exe
  InstallerSha256: 7105CA2A6498CA9B6978C4A7A5C51CEB29D148336874C55479C51A9F324EEE18
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64/hy-AM/Firefox%20Setup%20157.0.exe
  InstallerSha256: 4A83FB166F356F096A95E103901752C9B9A2F741399969F0272E31066869178C
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64-aarch64/hy-AM/Firefox%20Setup%20157.0.exe
  InstallerSha256: FB395F374BBDA99B69AF88DDECB3492D3A0FC2E8D520D6ACE035DA0DCE34E905
ManifestType: installer
ManifestVersion: 1.12.0
