# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: EarendilWorks.pi
PackageVersion: 0.99.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: pi.exe
Commands:
- pi
ReleaseDate: 2026-09-29
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/earendil-works/pi/releases/download/v0.99.1/pi-windows-x64.zip
  InstallerSha256: 7E5C2971C0BE6019A8B89EDC5E3F0EFB4CBDEB0AC236FD3A3307C1F62057528F
- Architecture: arm64
  InstallerUrl: https://github.com/earendil-works/pi/releases/download/v0.99.1/pi-windows-arm64.zip
  InstallerSha256: A16CFD489DBBF9D6C60033CAE3D15B035E7B4A5C1260F833F84C4B37F58706FC
ManifestType: installer
ManifestVersion: 1.12.0
