# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.et
PackageVersion: "157.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win32/et/Firefox%20Setup%20157.0.exe
  InstallerSha256: 9EA3BFDF073EEFD0F5D318FA48EC2A6BBAA7F081CC78DE6863B70F13BFFFDE06
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64/et/Firefox%20Setup%20157.0.exe
  InstallerSha256: 9DE031ADCC01DD8B3E360DB6BB4F182CF702E8C1959C895C4B16B834214F3779
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64-aarch64/et/Firefox%20Setup%20157.0.exe
  InstallerSha256: D1A5932EF0ECC2BEBB4EBACAFBA0D24CAF9D9F969161AEC2CE8CA524EBDC2DCC
ManifestType: installer
ManifestVersion: 1.12.0
