# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Microsoft.SafetyScanner
PackageVersion: 1.459.453.0
InstallerType: portable
Commands:
- safetyscanner
ReleaseDate: 2026-09-28
Installers:
- Architecture: x86
  InstallerUrl: https://definitionupdates.microsoft.com/packages/content/msert.exe?packageType=Scanner&packageVersion=1.459.453.0&arch=x86
  InstallerSha256: 618585C7414B5A5357D8758780CAB8F711E7637753E7094281AE57607BECD952
- Architecture: x64
  InstallerUrl: https://definitionupdates.microsoft.com/packages/content/msert.exe?packageType=Scanner&packageVersion=1.459.453.0&arch=amd64
  InstallerSha256: A4990C81F937E9EECC5D3DFDB62F61A0CCAA45FB0407FEE92F0E011DEC377789
ManifestType: installer
ManifestVersion: 1.12.0
