# Automatically updated by the winget bot at 2026/Sep/28
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: SiberSystems.GoodSync
PackageVersion: 12.11.8.8
MinimumOSVersion: 10.0.0.0
Installers:
- Architecture: x86
  InstallerType: msi
  InstallerUrl: https://www.goodsync.com/download/GoodSync-vsub-Setup.msi
  InstallerSha256: BF88C61B7F6F5091787FD29326D3F89FC29A58463BD258BA7E9D9B5E19B925A1
- Architecture: x86
  InstallerType: nullsoft
  Scope: machine
  InstallerUrl: https://www.goodsync.com/download/GoodSync-vsub-Setup.exe
  InstallerSha256: 6D6B1C6F08768159378FAE382C6326AC92089533664CBD3A6D8C15151E56FB5A
ManifestType: installer
ManifestVersion: 1.28.0
