# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: co2lab.Anchors
PackageVersion: 0.1.237
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: anchors.exe
  PortableCommandAlias: anchors
Commands:
- anchors
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/co2-lab/anchors/releases/download/v0.1.237/anchors_0.1.237_windows_amd64.zip
  InstallerSha256: D31111CB8E1A541D7F4430D22B4C8EFA48867CF77F50C2A5D26D8E5CAFB5847E
- Architecture: arm64
  InstallerUrl: https://github.com/co2-lab/anchors/releases/download/v0.1.237/anchors_0.1.237_windows_arm64.zip
  InstallerSha256: 782F4281BE4AFD8405589551F1CB194909664C82BAB63D190BBB80DA2F8147DE
ManifestType: installer
ManifestVersion: 1.12.0
