# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: HetoAndrade.NoteZap
PackageVersion: 1.9.2907
InstallerType: inno
InstallerLocale: pt-BR
Scope: user
InstallModes:
  - interactive
  - silent
  - silentWithProgress
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /SILENT /SUPPRESSMSGBOXES /NORESTART
UpgradeBehavior: install
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/hetoandrade/hetoandrade.github.io/releases/download/notezap-v1.9.2907/NoteZap_Setup_v1.9.2907.exe
    InstallerSha256: 468F9F2B36CCD7DCF6769E2DF1CF2EC08F9887D757AD69B94D8B2000B6801D6E
    ProductCode: "{F306435F-8861-42C8-B641-E9D80B540E0A}_is1"
    AppsAndFeaturesEntries:
      - DisplayName: "NoteZap versão 1.9.2907"
        Publisher: "Hetoandrade"
        ProductCode: "{F306435F-8861-42C8-B641-E9D80B540E0A}_is1"
ManifestType: installer
ManifestVersion: 1.10.0
