# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Splashtop.SplashtopStreamer.Deployment.MSI
PackageVersion: 3.8.6.1
InstallerLocale: en-US
InstallerType: msi
Scope: machine
InstallerSwitches:
  Upgrade: REINSTALL=ALL REINSTALLMODE=vomus MSIENFORCEUPGRADECOMPONENTRULES=1 CA_UPGRADE=1
UpgradeBehavior: install
ProductCode: '{B7C5EA94-B96A-41F5-BE95-25D78B486678}'
AppsAndFeaturesEntries:
- DisplayName: Splashtop Streamer
  ProductCode: '{B7C5EA94-B96A-41F5-BE95-25D78B486678}'
  UpgradeCode: '{001F085C-058A-480B-AD56-2940B857C38D}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles(x86)%\Splashtop\Splashtop Remote\.'
Installers:
- Architecture: x86
  InstallerUrl: https://download.splashtop.com/csrs/msi/v3.8.6.1/setup.msi
  InstallerSha256: FEAC19F5853BFA1086B845C3AD3D4E6AB4C1A7F61DF545E944331788779C344E
ManifestType: installer
ManifestVersion: 1.12.0
