# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Sourcegraph.Amp
PackageVersion: 0.0.1790467310-ge147a9
InstallerType: portable
Commands:
- amp
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ReleaseDate: 2026-09-27
Installers:
- Architecture: x64
  InstallerUrl: https://static.ampcode.com/cli/0.0.1790467310-ge147a9/amp-windows-x64-baseline.exe
  InstallerSha256: 53013E40AE974C89944C9B682C0D31B7ABDF0388F470A89291F7E29998A337E9
ManifestType: installer
ManifestVersion: 1.12.0
