PackageIdentifier: PrimeBuild.ThreadPilot
PackageVersion: 1.7.6
InstallerType: inno
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/PrimeBuild-pc/ThreadPilot/releases/download/v1.7.6/ThreadPilot_v1.7.6_Setup.exe
    InstallerSha256: ED9508C94918A388A30EA4E9515DFEC8E7EFF0B1D29D4D2ED63E0F3C77EF21E4
ManifestType: installer
ManifestVersion: 1.5.0
