# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: JanProchazka.dbgate
PackageVersion: 7.3.1
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: nullsoft
Scope: user
InstallModes:
- silent
UpgradeBehavior: install
ProductCode: eabf4847-a999-55ba-aa27-eacddccc1540
AppsAndFeaturesEntries:
- DisplayName: DbGate 7.2.5
  ProductCode: eabf4847-a999-55ba-aa27-eacddccc1540
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/dbgate/dbgate/releases/download/v7.3.1/dbgate-7.3.1-win.exe
  InstallerSha256: D2DC2682E5DC509369043EAF0E97730C27A76838BE2040D7F8CB61DB9D0A21C8
- Architecture: x64
  InstallerUrl: https://github.com/dbgate/dbgate/releases/download/v7.3.1/dbgate-7.3.1-win_x64.exe
  InstallerSha256: 796D84DA90557DA45F805A2C6A9DFE5CBCE179BE41A6441041F59E20F5AAE56F
- Architecture: arm64
  InstallerUrl: https://github.com/dbgate/dbgate/releases/download/v7.3.1/dbgate-7.3.1-win_arm64.exe
  InstallerSha256: F9456FE99CD0290FF3A49D163EB5798CCF2451A6AE821C77BB1E6C1963394D8D
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-24
