# Created with the TechyGeeksHome manifest generator
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: TechyGeeksHome.ShortGeek
PackageVersion: 2.0.1
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-09-26
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/techygeekshome/ShortGeek/releases/download/v2.0.1/ShortGeekSetup.exe
  InstallerSha256: 4C257EF378FB5B12327574D477EE01A6D37E6AAF16B07A04EAD0FD0BA6F5F7B6
  ProductCode: '{3F7B2C91-6D48-4A15-9E33-0B7C5A2E81D4}_is1'
ManifestType: installer
ManifestVersion: 1.12.0
