# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: SimonThorpe.Octomon
PackageVersion: 0.11.3
MinimumOSVersion: 10.0.17763.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: octomon.exe
  PortableCommandAlias: octomon
Commands:
- octomon
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/securitypedant/octomon/releases/download/v0.11.3/octomon-x86_64-pc-windows-msvc.zip
  InstallerSha256: BFDFAE0D303713F2B60A3EA3EBDD52D5FFE526E21E2E1D890C443DC64E1F6A4A
- Architecture: arm64
  InstallerUrl: https://github.com/securitypedant/octomon/releases/download/v0.11.3/octomon-aarch64-pc-windows-msvc.zip
  InstallerSha256: 837C85932012346D3D0201CB6C827C47F24169BE319CDF02D7C5EB30721D2B62
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-27
