# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: TrackerSoftware.PDF-XChangePRO
PackageVersion: 11.1.0.0
InstallerType: wix
Scope: machine
UpgradeBehavior: install
Protocols:
- pxce
FileExtensions:
- fdf
- pdf
- pdtex
- pdts
- xces
- xcesession
- xcesessionbk
- xclpack
- xcvault
- xfdf
- xps
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://downloads.pdf-xchange.com/11.1.0.0/ProV11.x86.msi
  InstallerSha256: 2924B8EC600610794625DFB8DB6143FB40F6504DCC02FCE4474E62EA4D266DE0
  ProductCode: '{B4C8B929-0277-4C30-ABCC-11AEC138D465}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{9AC998B9-BD41-46DC-8F08-0DE2A4A1EB4D}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles(x86)%\Tracker Software'
- Architecture: x64
  InstallerUrl: https://downloads.pdf-xchange.com/11.1.0.0/ProV11.x64.msi
  InstallerSha256: 5F1C55D3BAF0185A515AAD5FD615C4EAC4190D7EE724D460A6218386E694D945
  ProductCode: '{6C557704-D189-410C-A0D9-4DADCECD7B39}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{F363AF73-86E7-4782-87FA-F3C14FA4D395}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\Tracker Software'
- Architecture: arm64
  InstallerUrl: https://downloads.pdf-xchange.com/11.1.0.0/ProV11.ARM64.msi
  InstallerSha256: 674E068AE3D37C5420D7994CC27341BAB632A3024BA89C9183218F8EAC579B0A
  ProductCode: '{E1093E5A-A577-49F6-8C0F-D382C4EC15C8}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{6F616659-45F6-4637-84FB-31E8C25753AB}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\Tracker Software'
ManifestType: installer
ManifestVersion: 1.12.0
