# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.uk
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox ESR
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win32/uk/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 4EB7BB499672DAC69B6913668155AD5571706F9B1D9E1E263D243E1448003FA7
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64/uk/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: F4A26D75C46DEDCCBB1485DE213E5B2AEFC4A6AC40C7E199FC9595B177E0F893
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64-aarch64/uk/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 1AD91A5428F19F74046910953F101745A64BC5044BD06C1E70C661E085CC6544
ManifestType: installer
ManifestVersion: 1.12.0
