# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Austin-Patrician.Wordless
PackageVersion: 0.6.2
InstallerType: nullsoft
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
ProductCode: 3fdf0094-b4c7-542a-acec-1821478fc6e1
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/Austin-Patrician/Wordless/releases/download/v0.6.2/Wordless-0.6.2-win-x64.exe
  InstallerSha256: 8F85D73CC8B29273818EFEAE563E58BB11F0D1DA4181FCA9F7DE6A3012D06B82
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/Austin-Patrician/Wordless/releases/download/v0.6.2/Wordless-0.6.2-win-x64.exe
  InstallerSha256: 8F85D73CC8B29273818EFEAE563E58BB11F0D1DA4181FCA9F7DE6A3012D06B82
  InstallerSwitches:
    Custom: /allusers
ManifestType: installer
ManifestVersion: 1.12.0
