PackageIdentifier: ProtagonistLabs.FileLabs
PackageVersion: 1.0.25
InstallerType: inno
Scope: user
ReleaseDate: 2026-09-30
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/limburatorul/file-labs/releases/download/v1.0.25/FileLabs-1.0.25-setup.exe
  InstallerSha256: ACA54088202BCA626CAF0CD0ACEA288304BB0D05CC51DDC3B6800A0853E9AABF
ManifestType: installer
ManifestVersion: 1.6.0
