# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: JYH1878.KimiCodeBar
PackageVersion: 1.10.2
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.EdgeWebView2Runtime
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/JYH1878/KimiCodeBar-Windows/releases/download/v1.10.2/KimiCodeBar_1.10.2_x64-setup.exe
  InstallerSha256: 1FC8D2C808914A2596D6CFFB43F9EC81A90C3938A65B75C9F88FAE39150C2981
  ProductCode: KimiCodeBar
ManifestType: installer
ManifestVersion: 1.12.0
