# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: OpenJS.Electron.44
PackageVersion: 44.5.1
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: electron.exe
  PortableCommandAlias: electron
UpgradeBehavior: install
ReleaseDate: 2026-09-30
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/electron/electron/releases/download/v44.5.1/electron-v44.5.1-win32-x64.zip
  InstallerSha256: 9B382492DCFEE91F8F9E92C91F7972550A1B95D2299CAC72279DAB33A600D7DB
- Architecture: arm64
  InstallerUrl: https://github.com/electron/electron/releases/download/v44.5.1/electron-v44.5.1-win32-arm64.zip
  InstallerSha256: 6BA86D5D5CFDF4CE61D51E2D270EACA464A7F88C143D14C6D9B3F43BB0760E9E
ManifestType: installer
ManifestVersion: 1.12.0
