# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Meltytech.Shotcut
PackageVersion: 26.9.27
InstallerType: inno
UpgradeBehavior: install
FileExtensions:
- mlt
ProductCode: Shotcut_is1
ReleaseDate: 2026-09-28
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/mltframework/shotcut/releases/download/v26.9.27/shotcut-win64-26.9.27.exe
  InstallerSha256: 77E1EE1F713D92BDBAFF23266F416E33CDE3D367F7EF518B1841DDC961D05AF9
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/mltframework/shotcut/releases/download/v26.9.27/shotcut-win64-26.9.27.exe
  InstallerSha256: 77E1EE1F713D92BDBAFF23266F416E33CDE3D367F7EF518B1841DDC961D05AF9
  InstallerSwitches:
    Custom: /ALLUSERS
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/mltframework/shotcut/releases/download/v26.9.27/shotcut-win_ARM-26.9.27.exe
  InstallerSha256: 364EF9BF0B2319C154280137415BF62D332EA1F584656B75F81259C20712A807
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/mltframework/shotcut/releases/download/v26.9.27/shotcut-win_ARM-26.9.27.exe
  InstallerSha256: 364EF9BF0B2319C154280137415BF62D332EA1F584656B75F81259C20712A807
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.12.0
