# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Buildkite.Agent
PackageVersion: 4.0.8
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: buildkite-agent.exe
  PortableCommandAlias: buildkite-agent
Commands:
- buildkite-agent
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/buildkite/agent/releases/download/v4.0.8/buildkite-agent-windows-386-4.0.8.zip
  InstallerSha256: C446E4DC23B11635A97DAD19E46A3500B39EDEC645014A938169ECDCBC9712C3
- Architecture: x64
  InstallerUrl: https://github.com/buildkite/agent/releases/download/v4.0.8/buildkite-agent-windows-amd64-4.0.8.zip
  InstallerSha256: AACE46BB7B6F2124DF7016E714375A5D029895C5BDC91C9A06EC2952C877003C
- Architecture: arm64
  InstallerUrl: https://github.com/buildkite/agent/releases/download/v4.0.8/buildkite-agent-windows-arm64-4.0.8.zip
  InstallerSha256: 0014FC0D7408C31FFAD73C0FD11AAFFF1F5B68A41E3AC2F17CB595D3A220EC09
ManifestType: installer
ManifestVersion: 1.28.0
