# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: CircleCI.CLI
PackageVersion: 1.0.51589
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: circleci.exe
  PortableCommandAlias: circleci
UpgradeBehavior: uninstallPrevious
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/CircleCI-Public/circleci-cli/releases/download/v1.0.51589/circleci-cli_1.0.51589_windows_amd64.zip
  InstallerSha256: C0BF1C8E83959F166ED92B8B86EBBB5C309E8F9CC330F803A4658179317BDB9D
- Architecture: arm64
  InstallerUrl: https://github.com/CircleCI-Public/circleci-cli/releases/download/v1.0.51589/circleci-cli_1.0.51589_windows_arm64.zip
  InstallerSha256: AEE26BB3B6A0675FEFF59D8D7D5FC6D8DFCD414CBA234F0A9210AED91EA5DAE5
ManifestType: installer
ManifestVersion: 1.12.0
