# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: TinyHumansAI.OpenHuman
PackageVersion: 0.64.7
UpgradeBehavior: install
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/tinyhumansai/openhuman/releases/download/v0.64.7/OpenHuman_0.64.7_x64-setup.exe
  InstallerSha256: 0B2C2E7A052D2F6945A825D0A91E3C2A5AB468EE69DCCA817B6E2D73FF9D5B9A
  ProductCode: OpenHuman
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/tinyhumansai/openhuman/releases/download/v0.64.7/OpenHuman_0.64.7_x64_en-US.msi
  InstallerSha256: 24455C853FE1F2781F4FCADEBF790BA3FC83EA48607625B11D6DA0FB57967416
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  ProductCode: '{E44D8759-3963-4DDF-81E1-A7216B4760FD}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{54052255-0CFF-5EA8-82D1-C533E6DE0990}'
ManifestType: installer
ManifestVersion: 1.12.0
