# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: GregorDadera.AIContextBuilder
PackageVersion: 0.5.464.66
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: machine
ElevationRequirement: elevationRequired
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/gregordadera/AICB/releases/download/v0.5.464.66/AIContextBuilder-Setup-0.5.464.66.exe
  InstallerSha256: F2F3F4207908577AE4FABF73A7C3778D402CF667936CD394368774395CFB0099
  InstallerSwitches:
    Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
    SilentWithProgress: /SILENT /SUPPRESSMSGBOXES /NORESTART
ManifestType: installer
ManifestVersion: 1.12.0
