# Created with WinGet Updater using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: StirlingTools.StirlingPDF
PackageVersion: 3.0.1
PackageLocale: en-US
Publisher: Stirling-Software
PublisherUrl: https://www.stirlingpdf.com/
PublisherSupportUrl: https://github.com/Stirling-Tools/Stirling-PDF/issues
PackageName: Stirling-PDF
PackageUrl: https://github.com/Stirling-Tools/Stirling-PDF
License: MIT
LicenseUrl: https://github.com/Stirling-Tools/Stirling-PDF/blob/HEAD/LICENSE
Copyright: Copyright (c) 2025 Stirling PDF Inc.
ShortDescription: A locally hosted one-stop shop for all your PDF needs
Description: Stirling-PDF is a robust, locally hosted web-based PDF manipulation tool using Docker. It enables you to carry out various operations on PDF files, including splitting, merging, converting, reorganizing, adding images, rotating, compressing, and more. This locally hosted web application has evolved to encompass a comprehensive set of features, addressing all your PDF requirements.
Tags:
- docker
- java
- pdf
- pdf-converter
- pdf-editor
- pdf-manipulation
- pdf-merger
- pdf-ocr
- pdf-tools
- pdf-web-apps
- pdfmerger
ReleaseNotes: |-
  Quick hotfixes for the following windows desktop bugs:
  - Double Windows title bar showing
  - temp log files growth
  For all those interested in the big 3.0.0 release and all the cool features we added, check out here
  https://github.com/Stirling-Tools/Stirling-PDF/releases#release-v3.0.0
  What's Changed
  Bug Fixes
  - fix(jpdfium): stop the backend gracefully and reclaim extraction dirs by @balazs-szucs in #8202
  Enhancements
  - Unify tool list and viewer bar icon colours; rename right sidebar header to PDF Tools by @reecebrowne in #8190
  - Fix double title bar on Windows desktop after upgrade by @Frooodle in #8203
  Full Changelog: v3.0.0...v3.0.1
ReleaseNotesUrl: https://github.com/Stirling-Tools/Stirling-PDF/releases/tag/v3.0.1
ManifestType: defaultLocale
ManifestVersion: 1.12.0
