# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: YuanDevLLC.OneXray
PackageVersion: 26.9.5
InstallerLocale: en-US
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /SP- /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /FORCECLOSEAPPLICATIONS
  SilentWithProgress: /SP- /SILENT /SUPPRESSMSGBOXES /NORESTART /FORCECLOSEAPPLICATIONS
UpgradeBehavior: install
ProductCode: 835d7bbd-85bb-4c73-97f8-ce0740f151a7_is1
ReleaseDate: 2026-09-28
AppsAndFeaturesEntries:
- DisplayName: OneXray
  ProductCode: 835d7bbd-85bb-4c73-97f8-ce0740f151a7_is1
InstallationMetadata:
  DefaultInstallLocation: '%LOCALAPPDATA%\Programs\OneXray'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/OneXray/OneXray/releases/download/v26.9.5/OneXray-windows-amd64.exe
  InstallerSha256: CAC437A89029A7642F45727629713CB918CC0B135495E03666645D17AA497B5A
- Architecture: arm64
  InstallerUrl: https://github.com/OneXray/OneXray/releases/download/v26.9.5/OneXray-windows-arm64.exe
  InstallerSha256: FC9B64A11C24D570B2C6D34E2C99B77FBE4B8DC0C72C2332A42A068AEA05C9CD
ManifestType: installer
ManifestVersion: 1.12.0
