# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: EEO.ClassInX
PackageVersion: 6.0.9.1813
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silentWithProgress
InstallerSwitches:
  Silent: /SILENT
  SilentWithProgress: /SILENT
  InstallLocation: /DIR="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- classin
FileExtensions:
- eda
- edb
- edt
- edu
- edv
- epub
ProductCode: ClassIn X
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  InstallerUrl: https://download.eeo.cn/client/classinx_win_install_6.0.9.1813_x64.exe
  InstallerSha256: 742DF3DCE55E8C9383FD8F2F7397D30EBA39E5B1D0082E4CAE177FE93621121A
ManifestType: installer
ManifestVersion: 1.12.0
