# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: FactoryAI.Factory
PackageVersion: 0.185.1
InstallerType: exe
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
UpgradeBehavior: install
Protocols:
- factory-desktop
ProductCode: Factory
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://downloads.factory.ai/factory-desktop/releases/0.185.1/win32/x64/Factory-0.185.1%20Setup.exe
  InstallerSha256: E0E64BA798DCF085A902079482228319A9FDC653B5A0D621C4249CD5E3CD3E9B
ManifestType: installer
ManifestVersion: 1.12.0
