# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Yuanfudao.Yuanfudao
PackageVersion: 7.32.1
InstallerType: nullsoft
Scope: machine
UpgradeBehavior: install
Protocols:
- tutor-electron-student
ProductCode: tutor-electron-student
ReleaseDate: 2026-09-22
Installers:
- Architecture: x86
  InstallerUrl: https://apphub.fbcontent.cn/ape-gallery/app/yuanfudao-student-7.32.1.22936-installer-ia32.exe
  InstallerSha256: 82F418458DD3DEEAD4E8559BB7F434B478804F1E80B4080629D746C98EE02BD6
- Architecture: x64
  InstallerUrl: https://apphub.fbcontent.cn/ape-gallery/app/yuanfudao-student-7.32.1.22941-installer-x64.exe
  InstallerSha256: 584C29486E2554EC98A40B2311378AC8E755FDE68424C62E7D9CAB0A686A9199
ManifestType: installer
ManifestVersion: 1.12.0
