# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: KDE.Minuet
PackageVersion: 26.11.70
InstallerType: nullsoft
UpgradeBehavior: install
ProductCode: minuet
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://cdn.kde.org/ci-builds/education/minuet/master/windows/minuet-master-1366-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: EFBAB4E828D0C4F837C941048AE3647959F0FBA0BE16E39285947C3111226279
  InstallerSwitches:
    Custom: /CurrentUser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://cdn.kde.org/ci-builds/education/minuet/master/windows/minuet-master-1366-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: EFBAB4E828D0C4F837C941048AE3647959F0FBA0BE16E39285947C3111226279
  InstallerSwitches:
    Custom: /AllUsers
ManifestType: installer
ManifestVersion: 1.12.0
