# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.az
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox ESR
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win32/az/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 741D3E89269D0BAA41D9ED567EF2C3A12EE8CBB050B7DB9AC321B1C38F370A94
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64/az/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 4D3720E02D6101F23B9FB2274E4A67F994BA847801C67615FA49C39FE90E2AC0
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64-aarch64/az/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: F89B5886CF6A6B9C5E56D1113715D98A2FD8EB660636831E740B341E030A82B6
ManifestType: installer
ManifestVersion: 1.12.0
