# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: KDE.KTurtle
PackageVersion: 26.11.70
InstallerType: nullsoft
UpgradeBehavior: install
ProductCode: kturtle
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://cdn.kde.org/ci-builds/education/kturtle/master/windows/kturtle-master-1235-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: B65393A84E3D524260658FBA0E24E136246EE668D94EBEB0FA0042888D75BCEB
  InstallerSwitches:
    Custom: /CurrentUser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://cdn.kde.org/ci-builds/education/kturtle/master/windows/kturtle-master-1235-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: B65393A84E3D524260658FBA0E24E136246EE668D94EBEB0FA0042888D75BCEB
  InstallerSwitches:
    Custom: /AllUsers
ManifestType: installer
ManifestVersion: 1.12.0
