# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: vim.vim.nightly
PackageVersion: 9.2.1152
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: nullsoft
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Commands:
- diff
- evim
- gview
- gvim
- gvimdiff
- tee
- view
- vim
- vimdiff
- xxd
ProductCode: Vim (current user)
ReleaseDate: 2026-09-30
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://github.com/vim/vim-win32-installer/releases/download/v9.2.1152/gvim_9.2.1152_x86.exe
  InstallerSha256: 14B7D625331A91F5E761BB61E669641AD34718585E36E84F38082A105BC43AC9
  InstallerSwitches:
    Custom: /currentuser
  AppsAndFeaturesEntries:
  - DisplayName: Vim 9.2 (x86) (current user)
    Publisher: The Vim Project
    ProductCode: Vim (current user)
- Architecture: x86
  Scope: machine
  InstallerUrl: https://github.com/vim/vim-win32-installer/releases/download/v9.2.1152/gvim_9.2.1152_x86.exe
  InstallerSha256: 14B7D625331A91F5E761BB61E669641AD34718585E36E84F38082A105BC43AC9
  InstallerSwitches:
    Custom: /allusers
  AppsAndFeaturesEntries:
  - DisplayName: Vim 9.2 (x86) (current user)
    Publisher: The Vim Project
    ProductCode: Vim (current user)
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/vim/vim-win32-installer/releases/download/v9.2.1152/gvim_9.2.1152_x64.exe
  InstallerSha256: D85B8723E1ACD087883B623E7B295C2800C0BEB2CF1BCFD4D5898643BAF798E8
  InstallerSwitches:
    Custom: /currentuser
  AppsAndFeaturesEntries:
  - DisplayName: Vim 9.2 (x64) (current user)
    Publisher: The Vim Project
    ProductCode: Vim (current user)
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/vim/vim-win32-installer/releases/download/v9.2.1152/gvim_9.2.1152_x64.exe
  InstallerSha256: D85B8723E1ACD087883B623E7B295C2800C0BEB2CF1BCFD4D5898643BAF798E8
  InstallerSwitches:
    Custom: /allusers
  AppsAndFeaturesEntries:
  - DisplayName: Vim 9.2 (x64) (current user)
    Publisher: The Vim Project
    ProductCode: Vim (current user)
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/vim/vim-win32-installer/releases/download/v9.2.1152/gvim_9.2.1152_arm64.exe
  InstallerSha256: 3538C1BCF77D91E0BA35EF400F308788B4FE6B5B341EFB9288FB7E9F07D89320
  InstallerSwitches:
    Custom: /currentuser
  AppsAndFeaturesEntries:
  - DisplayName: Vim 9.2 (ARM64) (current user)
    Publisher: The Vim Project
    ProductCode: Vim (current user)
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/vim/vim-win32-installer/releases/download/v9.2.1152/gvim_9.2.1152_arm64.exe
  InstallerSha256: 3538C1BCF77D91E0BA35EF400F308788B4FE6B5B341EFB9288FB7E9F07D89320
  InstallerSwitches:
    Custom: /allusers
  AppsAndFeaturesEntries:
  - DisplayName: Vim 9.2 (ARM64) (current user)
    Publisher: The Vim Project
    ProductCode: Vim (current user)
ManifestType: installer
ManifestVersion: 1.12.0
