# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: AlbinAlm.Straumr
PackageVersion: 2026.9.29.44
InstallerType: inno
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /SILENT /SUPPRESSMSGBOXES /NORESTART
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/albinalm/straumr/releases/download/v2026.9.29.44/straumr-2026.9.29.44-win-x64-setup.exe
  InstallerSha256: E672F765C2E25177A00047D9B249B9700DE7C96B25D29844A97A23C934A27AF8
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-29
