# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Google.GoogleUpdater
PackageVersion: 156.0.8067.0
InstallerType: exe
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: --install --silent
  SilentWithProgress: --install --silent
  Interactive: --install
  Log: --enable-logging
  Upgrade: --update
UpgradeBehavior: install
ReleaseDate: 2026-09-21
InstallationMetadata:
  Files:
  - RelativeFilePath: updater.exe
    FileSha256: 4B4D6C9CBED8F6F13ECFA9EFCE93538B611259193ED36AD6180F21ABECF54CA3
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://dl.google.com/release2/update2/acafpkgkpj4c5wargfpuzzts4kda_156.0.8067.0/UpdaterSetup.exe
  InstallerSha256: 32D10CE2CA57A6ABFADDB928C28E261B7B191B1FE773105AD807CD59D37A3BE1
  InstallerSwitches:
    Custom: --enterprise
  InstallationMetadata:
    DefaultInstallLocation: '%LOCALAPPDATA%\Google\GoogleUpdater\156.0.8067.0'
- Architecture: x86
  Scope: machine
  InstallerUrl: https://dl.google.com/release2/update2/acafpkgkpj4c5wargfpuzzts4kda_156.0.8067.0/UpdaterSetup.exe
  InstallerSha256: 32D10CE2CA57A6ABFADDB928C28E261B7B191B1FE773105AD807CD59D37A3BE1
  InstallerSwitches:
    Custom: --system --enterprise
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles(x86)%\Google\GoogleUpdater\156.0.8067.0'
ManifestType: installer
ManifestVersion: 1.12.0
