# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Softros.LogonExpert
PackageVersion: "11.4"
InstallerLocale: en-US
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x86
  InstallerUrl: https://download.softros.com/LogonExpertSetup32.msi
  InstallerSha256: F632313B39DF20CE90DAA001B3D76D0AF4FC08BB30B397B36F3DABE8E2727F74
  ProductCode: '{134EA677-032E-4CCD-9063-023AAE892E29}'
  AppsAndFeaturesEntries:
  - ProductCode: '{134EA677-032E-4CCD-9063-023AAE892E29}'
    UpgradeCode: '{D25E1E10-6378-4CAC-B38C-5747CBF4BCB6}'
- Architecture: x64
  InstallerUrl: https://download.softros.com/LogonExpertSetup64.msi
  InstallerSha256: 81DD63D42D176FC10CBC0BC3953EB4AA807143D00BA8CD269FFC82393EB76411
  ProductCode: '{B3235720-6F77-4209-96F3-3C1A4FB46DCD}'
  AppsAndFeaturesEntries:
  - ProductCode: '{B3235720-6F77-4209-96F3-3C1A4FB46DCD}'
    UpgradeCode: '{D25E1E10-6378-4CAC-B38C-5747CBF4BCB6}'
- Architecture: arm64
  InstallerUrl: https://download.softros.com/LogonExpertSetupARM64.msi
  InstallerSha256: 05F0CCD0C9491E263CBD38671B19883797EC87C0E3B909AA1B2FA75533C6F707
  ProductCode: '{A5DC5300-047C-4C5A-AAFE-5268F1F4C7CD}'
  AppsAndFeaturesEntries:
  - ProductCode: '{A5DC5300-047C-4C5A-AAFE-5268F1F4C7CD}'
    UpgradeCode: '{D25E1E10-6378-4CAC-B38C-5747CBF4BCB6}'
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-30
