# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: SteveTheKiller.KillerScan
PackageVersion: 1.7.5
InstallerType: portable
InstallModes:
- silent
InstallerSwitches:
  Custom: /silent
UpgradeBehavior: install
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/SteveTheKiller/KillerScan/releases/download/v1.7.5/KillerScan.exe
  InstallerSha256: 75C65DCB9279CE6051DF981DBAD3C20AB4983CB79646028F96BC4857D71F7371
ManifestType: installer
ManifestVersion: 1.12.0
