# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.cs
PackageVersion: "157.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win32/cs/Firefox%20Setup%20157.0.exe
  InstallerSha256: B4D706FFCCCBD70C0ECABAF3AEE5E9241A66E4300B2795EA875853DCBF70957D
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64/cs/Firefox%20Setup%20157.0.exe
  InstallerSha256: 1E804FAD459B6D071441C3DB77C9A44E0354B68AFA17327B96AFEFB3533338FE
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64-aarch64/cs/Firefox%20Setup%20157.0.exe
  InstallerSha256: 14EE325A156C049040BDD45ADBFF09DFAAAF250BDB027C0E0CF95F3A7B9A2C2D
ManifestType: installer
ManifestVersion: 1.12.0
