# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.ach
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox ESR
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win32/ach/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 142D5667950894329AEE9E00D7D2920A02561EBB0D65248287C22D0F5C4B83C1
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64/ach/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 7A65EBDEDC4CEA5928E11244283CB1B1F5D21F08C8E8FB3B1C58C3FFB483D573
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64-aarch64/ach/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 7C3BBB1673053D72323FFA989303349BF0F9284A02A7640BA9CB11F6D3A6E76F
ManifestType: installer
ManifestVersion: 1.12.0
