# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.bn
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox ESR
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win32/bn/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: B95E69E4F8BE26B5AED3C2BD0C164442F6502EE7CB82715A828AD774CC1D0004
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64/bn/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: D196CDA3114F5251585D4D34C7347F3C7015FEE0152EBE764C92DE0D89DB98F2
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64-aarch64/bn/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 425B76DFE0C0C70DE3D52DD86C30D7A659307AAB6E7E9EAB54137799C81AF3F7
ManifestType: installer
ManifestVersion: 1.12.0
