# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: jeffvli.Feishin
PackageVersion: 1.17.0
PackageLocale: zh-CN
ShortDescription: 现代的自托管音乐播放器
Tags:
- 专辑
- 播放器
- 歌单
- 歌手
- 歌曲
- 音乐
- 音频
ManifestType: locale
ManifestVersion: 1.12.0
