# Created with WinGet Updater using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: pbek.QOwnNotes
PackageVersion: 26.9.14
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: QOwnNotes.exe
  PortableCommandAlias: qownnotes.exe
ReleaseDate: 2026-09-29
Installers:
- Architecture: neutral
  InstallerUrl: https://github.com/pbek/QOwnNotes/releases/download/v26.9.14/QOwnNotes.zip
  InstallerSha256: 08CF57599B32364BC3A6B26C67676E9B924658D6D18A40A007B8ADEB7F687B53
ManifestType: installer
ManifestVersion: 1.12.0
