# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: AprilNEA.OpenLogi
PackageVersion: 0.8.9
InstallerType: wix
UpgradeBehavior: install
ReleaseDate: 2026-09-27
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%/Programs/OpenLogi/bin'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/AprilNEA/OpenLogi/releases/download/v0.8.9/OpenLogi-v0.8.9-windows-x86_64.msi
  InstallerSha256: 740D9DAB4C35E9289FE6647DCB2B8D20D107B52745C111622408E23162D17E07
  ProductCode: '{5EFB6689-5C43-47AD-9353-2AA49B704AC1}'
  AppsAndFeaturesEntries:
  - ProductCode: '{5EFB6689-5C43-47AD-9353-2AA49B704AC1}'
    UpgradeCode: '{981D0C70-179E-4EE8-8F1E-0EB6877EAE94}'
- Architecture: arm64
  InstallerUrl: https://github.com/AprilNEA/OpenLogi/releases/download/v0.8.9/OpenLogi-v0.8.9-windows-arm64.msi
  InstallerSha256: 3D44883A61878126770F23E217633A69FD91D9DC587DD234BC9B9121CB893115
  ProductCode: '{37CCA358-C43A-4A1F-80DB-3AB015977AD9}'
  AppsAndFeaturesEntries:
  - ProductCode: '{37CCA358-C43A-4A1F-80DB-3AB015977AD9}'
    UpgradeCode: '{2A989A66-36FE-4999-ACE2-3E79AE02D12A}'
ManifestType: installer
ManifestVersion: 1.12.0
