# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Brave.Brave.Beta
PackageVersion: 154.1.97.51
InstallerType: exe
ExpectedReturnCodes:
- InstallerReturnCode: -2147219440
  ReturnResponse: cancelledByUser
- InstallerReturnCode: -2147219416
  ReturnResponse: alreadyInstalled
- InstallerReturnCode: -2147218431
  ReturnResponse: invalidParameter
- InstallerReturnCode: -2147024809
  ReturnResponse: invalidParameter
UpgradeBehavior: install
Protocols:
- ftp
- http
- https
- mailto
- tel
FileExtensions:
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: BraveSoftware Brave-Browser
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.97.51/BraveBrowserStandaloneSilentBetaSetup32.exe
  InstallerSha256: 88134A3CA4F89E85F43D03CE3955C0DA0EA93950C5B5DFE732743AB8B33342CB
  InstallModes:
  - silent
- Architecture: x86
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.97.51/BraveBrowserStandaloneBetaSetup32.exe
  InstallerSha256: 28402072E1BB4C791040689CB44D1777DDA114203C7149C220E4BB0EB65C97C8
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.97.51/BraveBrowserStandaloneSilentBetaSetup.exe
  InstallerSha256: 43104A46E35BC202EE901E5A5DAD00A4A8C58A19DF5044CF0DF201B203982483
  InstallModes:
  - silent
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.97.51/BraveBrowserStandaloneBetaSetup.exe
  InstallerSha256: 9599C72928331CF1BC5C3C6D5D367904908C33A1C1EAF0186D61082F356FBCFE
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.97.51/BraveBrowserStandaloneSilentBetaSetupArm64.exe
  InstallerSha256: 79DCA0222FCC3D79A013504763E35E417A5433C3BE505CBC3ADB0E325103F389
  InstallModes:
  - silent
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.97.51/BraveBrowserStandaloneBetaSetupArm64.exe
  InstallerSha256: DCD3099CD48BC18EE4AE77F8E2F34718EB56F796DF4AE09A0A77E982FD3D9D63
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
ManifestType: installer
ManifestVersion: 1.12.0
