# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: xemu-project.xemu
PackageVersion: 0.8.136
ReleaseDate: 2026-06-08
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: xemu.exe
  PortableCommandAlias: xemu
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/xemu-project/xemu/releases/download/v0.8.136/xemu-win-x86_64-release.zip
  InstallerSha256: B25A6C24A2C2C36A0843A153CD9EE59CA6833EF87BDCD855BA0824930E4DDD1D
- Architecture: arm64
  InstallerUrl: https://github.com/xemu-project/xemu/releases/download/v0.8.136/xemu-win-aarch64-release.zip
  InstallerSha256: 4ad9d8f059848b86d2218805c2d133ba79ecafb28e3ab45a13c8381e8bb57688
  AppsAndFeaturesEntries:
  - DisplayName: xemu (ARM64)
ManifestType: installer
ManifestVersion: 1.12.0
