# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: SQLBI.Whiteboard
PackageVersion: 1.7.0
MinimumOSVersion: 10.0.19041.0
InstallerType: wix
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/sql-bi/SQLBI-Whiteboard/releases/download/v1.7.0/SQLBI.Whiteboard.1.7.0.x64.msi
  InstallerSha256: 65B4603C488A1AEC02D0C91B41F82643AADD6E8EBB79038F40B0CECF020FDCFA
  ProductCode: '{09AD7509-9763-4E8A-9DEB-87AE1B9F619B}'
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/sql-bi/SQLBI-Whiteboard/releases/download/v1.7.0/SQLBI.Whiteboard.1.7.0.x64-userinstaller.msi
  InstallerSha256: 7347BF56BB17B40EDC8422B570660BB6AA6B9066152089AF476E059C3331AC7E
  ProductCode: '{2D008D64-7944-49C7-87C9-F821031EE588}'
ManifestType: installer
ManifestVersion: 1.12.0
