# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: demkada.ArgyCode
PackageVersion: 2.8.1
Installers:
  - Architecture: x64
    InstallerType: zip
    InstallerUrl: https://github.com/demkada/argy-code/releases/download/v2.8.1/argy-windows-x64.zip
    InstallerSha256: 03699a758c4a198769cc29a73335cdf9f0960da0cb20a6eccd5f1f8112576723
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: argy.exe
        PortableCommandAlias: argy
ManifestType: installer
ManifestVersion: 1.12.0
