# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: mg-chao.snow-shot
PackageVersion: '1.1.6-beta'
InstallerLocale: en-US
InstallerType: nullsoft
Scope: machine
InstallModes:
  - interactive
  - silent
  - silentWithProgress
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: install
ElevationRequirement: elevationRequired
ProductCode: SnowShot
ReleaseDate: 2026-09-28
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\SnowShot'
AppsAndFeaturesEntries:
  - DisplayName: Snow Shot
    Publisher: Snow Apps
    ProductCode: SnowShot
ExpectedReturnCodes:
  - InstallerReturnCode: 10
    ReturnResponse: packageInUse
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/mg-chao/snow-apps/releases/download/v1.1.6-beta/snow-shot-1.1.6-beta-windows-x64-offline.exe
    InstallerSha256: 023FBD407E25726893EB2EACA6CA8C1C42F851EC7A6D6E37B519B6464C6F9D4B
ManifestType: installer
ManifestVersion: 1.12.0
