# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Perforce.P4V
PackageVersion: 242.63.1
Scope: machine
UpgradeBehavior: install
ReleaseDate: 2026-09-23
Installers:
- Architecture: x64
  InstallerType: wix
  InstallerUrl: https://www.perforce.com/downloads/perforce/r26.3/bin.ntx64/p4vinst64.msi
  InstallerSha256: 81F4338ADA1D9E3501E67A09D9669907AE4E1F5E648B18D26902BE1A63298F05
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
  ProductCode: '{823CB831-35E6-4613-8FF1-EEACCA941CDA}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{70A9FDC7-885B-4D6D-BAFD-CB2D27AB2963}'
- Architecture: x64
  InstallerType: burn
  InstallerUrl: https://www.perforce.com/downloads/perforce/r26.3/bin.ntx64/p4vinst64.exe
  InstallerSha256: 5EA958A4432D1AB4B4C33924E2188C8F5B47F057503DCEB39033C492241269E2
  InstallerSwitches:
    InstallLocation: INSTDIR="<INSTALLPATH>"
  ProductCode: '{e4720099-b569-44b5-8bd6-bd6f4d66033e}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{AE554B2A-CA7C-4DA4-8A4E-BC6085DFACE4}'
ManifestType: installer
ManifestVersion: 1.12.0
