# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: hrzlgnm.zux
PackageVersion: 1.19.2
InstallerLocale: en-US
InstallModes:
- interactive
UpgradeBehavior: install
Commands:
- zux
ReleaseDate: 2026-09-30
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/hrzlgnm/zux/releases/download/v1.19.2/zux_1.19.2_x64-setup.exe
  InstallerSha256: 8B3625A4CC02026C9CF431300DE59611F5D2A8C92943B3014D9239C29BEEBD9F
  ProductCode: zux
  AppsAndFeaturesEntries:
  - Publisher: github
    ProductCode: zux
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\zux'
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/hrzlgnm/zux/releases/download/v1.19.2/zux_1.19.2_x64_en-US.msi
  InstallerSha256: 484E60357232B2E564B3FE51F989C91626D71BC3862917CEBD779D50CA547D36
  ProductCode: '{C6327AE1-A158-4DEE-97E2-6BC91BA70905}'
  AppsAndFeaturesEntries:
  - Publisher: github
    ProductCode: '{C6327AE1-A158-4DEE-97E2-6BC91BA70905}'
    UpgradeCode: '{5815D5F5-1FC0-5793-BA28-8FF79F8636D3}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/zux'
ManifestType: installer
ManifestVersion: 1.12.0
