# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: QPDF.QPDF
PackageVersion: 12.4.2
InstallerLocale: en-US
InstallerType: nullsoft
Scope: machine
ProductCode: qpdf 12.3.2
ReleaseDate: 2026-09-27
InstallationMetadata:
  DefaultInstallLocation: "%ProgramFiles%qpdf 12.4.2"
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/qpdf/qpdf/releases/download/v12.4.2/qpdf-12.4.2-msvc64.exe
  InstallerSha256: 30EB98817A18AE80ECEC4A9E6382BDB87012A6C0C9DE24139AA9E20A8F0FCC6E
ManifestType: installer
ManifestVersion: 1.12.0
