# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: wkjarosz.hdrview
PackageVersion: 3.0.2
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: HDRView.exe
UpgradeBehavior: uninstallPrevious
ReleaseDate: 2026-09-29
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/wkjarosz/hdrview/releases/download/v3.0.2/HDRView-3.0.2-windows-x86_64.zip
  InstallerSha256: 391F914275149CB2BE6FAD45F94D83C87F597E204EF11436C63BA06C28876DD1
ManifestType: installer
ManifestVersion: 1.12.0
