# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: TrackerSoftware.PDF-XChangeLite
PackageVersion: 11.1.0.0
InstallerType: wix
Scope: machine
UpgradeBehavior: install
FileExtensions:
- xcvault
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://downloads.pdf-xchange.com/11.1.0.0/LiteV11.x86.msi
  InstallerSha256: 6FDE00FF3212846FEB29B82F82FDCA375EF48733E6AC2BB7E43A88EE3F445A6D
  ProductCode: '{6375D0E2-AABF-4612-A4A0-BE13E1A8F83F}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{2699F56C-713F-44EA-970D-DCE872E29992}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles(x86)%/Tracker Software'
- Architecture: x64
  InstallerUrl: https://downloads.pdf-xchange.com/11.1.0.0/LiteV11.x64.msi
  InstallerSha256: 7F71391383007D93C23F76B58FD98A8B3637FD1569D26BAEC4B588FF29D501A6
  ProductCode: '{A8C32AA6-466C-4454-8C03-EC0938F1194F}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{CDB43E78-3E0B-432B-8F6E-13FE653DCC34}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/Tracker Software'
- Architecture: arm64
  InstallerUrl: https://downloads.pdf-xchange.com/11.1.0.0/LiteV11.ARM64.msi
  InstallerSha256: AC8B661B9E2EEF5241F7F4B45D60B3A1B99F19B139C3FC873BD5FE9E14B124B9
  ProductCode: '{EE4CA881-BCCB-45FC-9516-15AA34CB7FC8}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{EE55C58D-035A-40C8-8A4E-0E5920354B07}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/Tracker Software'
ManifestType: installer
ManifestVersion: 1.12.0
