# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: KDE.LSkat
PackageVersion: master
InstallerType: nullsoft
UpgradeBehavior: install
ProductCode: lskat
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://cdn.kde.org/ci-builds/games/lskat/master/windows/lskat-master-959-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: B8AB6F120E9A773D2590E82869FBC4EAB35FC991C966BFB9E043EC43A6A47239
  InstallerSwitches:
    Custom: /CurrentUser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://cdn.kde.org/ci-builds/games/lskat/master/windows/lskat-master-959-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: B8AB6F120E9A773D2590E82869FBC4EAB35FC991C966BFB9E043EC43A6A47239
  InstallerSwitches:
    Custom: /AllUsers
ManifestType: installer
ManifestVersion: 1.12.0
