# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.br
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox ESR
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win32/br/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 9A82D3405A82D1E0C835EC3604476DB6402ED631144B2640E1ED043B810FFF43
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64/br/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 47EB4EE310B06652C6F0599528EDE8D770999C0C1566E4232F17B5C44F092E38
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64-aarch64/br/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: B8B1874C597CCEC5476CAF116AA30D1A90FC20338853F3E3E42A3912E8641BCF
ManifestType: installer
ManifestVersion: 1.12.0
