# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: laurentiu021.SysManager
PackageVersion: 1.114.13
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: portable
Commands:
- SysManager
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/laurentiu021/SystemManager/releases/download/v1.114.13/SysManager-v1.114.13.exe
  InstallerSha256: C3F5E3E9E95BEC45BF1B7D040A2E17E5C9AF3894A38363DD442FF6D82B4AF9FA
ManifestType: installer
ManifestVersion: 1.12.0
