# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: NearAI.IronClaw
PackageVersion: 1.4.1
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: APPLICATIONFOLDER="<INSTALLPATH>"
ProductCode: '{53E55A4E-65E1-4A2C-97BD-6179C6492095}'
ReleaseDate: 2026-09-29
AppsAndFeaturesEntries:
- UpgradeCode: '{650712A0-A6B4-4584-829A-03A90CE3D7D9}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/nearai/ironclaw/releases/download/ironclaw-v1.4.1/ironclaw-x86_64-pc-windows-msvc.msi
  InstallerSha256: E688380DFA8EB3DA0ED138C861854368FBB3A1332A324E554C3193E2CEEC0DBB
ManifestType: installer
ManifestVersion: 1.12.0
