# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.my
PackageVersion: "157.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win32/my/Firefox%20Setup%20157.0.exe
  InstallerSha256: CDC40A932365FFF6D022BCC640D29AF8BCCCBBDBA5BC91D769924B5A159E407C
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64/my/Firefox%20Setup%20157.0.exe
  InstallerSha256: 3103063CBB96DA7AE0C335C1E09F7676F3878D35F2BA371992E488D357FAA964
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64-aarch64/my/Firefox%20Setup%20157.0.exe
  InstallerSha256: 0592749763270F8E4FF9D79DC23D05E3B4DFFE0A3B2A02B520CAA65B2E702891
ManifestType: installer
ManifestVersion: 1.12.0
