# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: VovSoft.VovMusicPlayer
PackageVersion: 13.0.0.0
InstallerLocale: en-US
Installers:
- Architecture: x86
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://files.vovsoft.com/vov-music-player.exe
  InstallerSha256: A74A4FEE0E98A9452BC093B224FD811D75A2768A458CC3509B61CAB9110D0CF4
  InstallModes:
  - interactive
  - silent
  - silentWithProgress
  UpgradeBehavior: install
  FileExtensions:
  - AAC
  - AIFF
  - FLAC
  - M4A
  - M4B
  - MIDI
  - MOD
  - MP1
  - MP2
  - MP3
  - MP4
  - MPC
  - OGG
  - OPUS
  - S3M
  - WAV
  - WEBM
  - WMA
  - WV
  ProductCode: Vov Music Player_is1
  AppsAndFeaturesEntries:
  - ProductCode: Vov Music Player_is1
  ElevationRequirement: elevatesSelf
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\VOVSOFT\Vov Music Player'
- Architecture: x86
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: vovmusic.exe
    PortableCommandAlias: vovmusic
  InstallerUrl: https://files.vovsoft.com/vov-music-player-portable.zip
  InstallerSha256: 7B0140D251840D886AC3918D08B3FC31B5F6FE78B8F1FAED7E3212D5747A5D33
  ArchiveBinariesDependOnPath: true
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-28
