# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ByteDance.DoubaoWork
PackageVersion: 2.31.10
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: --command=quiet_install
  SilentWithProgress: --command=quiet_install
  InstallLocation: --target_dir="<INSTALLPATH>"
  Log: --log_dir="<LOGPATH>"
ProductCode: DoubaoWork
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://lf-flow-web-cdn.doubao.com/obj/flow-doubao/doubao_pc/2.31.10/DoubaoWork_installer_2.31.10.exe
  InstallerSha256: 97665E07BBD992AB9D298ECB95D78D3D2CA775D238AD669071370EFAEFEFEE1B
- Architecture: arm64
  InstallerUrl: https://lf-flow-web-cdn.doubao.com/obj/flow-doubao/doubao_pc/2.31.10/DoubaoWork_Arm64_installer_2.31.10.exe
  InstallerSha256: BA9A05863B216D65F12A8206D86BC467F844EC2A34E62722C91F61BD3475C20C
ManifestType: installer
ManifestVersion: 1.12.0
