# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: co2lab.Anchors
PackageVersion: 0.1.213
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: anchors.exe
  PortableCommandAlias: anchors
Commands:
- anchors
ReleaseDate: 2026-09-27
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/co2-lab/anchors/releases/download/v0.1.213/anchors_0.1.213_windows_amd64.zip
  InstallerSha256: 13A855E4B1E8732EF8862D6016910D617AE34681AE55B042D7EFC0B9C8B8C985
- Architecture: arm64
  InstallerUrl: https://github.com/co2-lab/anchors/releases/download/v0.1.213/anchors_0.1.213_windows_arm64.zip
  InstallerSha256: C4DEF9762D00F1EC0DAA987ACE3D71C8E8FB02F6AD8B9B917CF66CB90103EDF4
ManifestType: installer
ManifestVersion: 1.12.0
