# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.zh-CN
PackageVersion: "157.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win32/zh-CN/Firefox%20Setup%20157.0.exe
  InstallerSha256: 8531354231E7892173AE8920F08F0B67D64FBF8343C36C7BB10B5A998ABDEA84
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64/zh-CN/Firefox%20Setup%20157.0.exe
  InstallerSha256: DCDC8305EC97AAB27C04AE04077E5B06E5EA24E2650F4CCA69B31461533783AB
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64-aarch64/zh-CN/Firefox%20Setup%20157.0.exe
  InstallerSha256: 89E7FA9A3A05B907B84CE7F230FA358B74B18DEFBC0318B7D666647B898177EF
ManifestType: installer
ManifestVersion: 1.12.0
