# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: Micronaut.Launch
PackageVersion: 5.2.0
PackageLocale: en-US
Publisher: Micronaut Foundation
PublisherUrl: https://micronaut.io/
PublisherSupportUrl: https://github.com/micronaut-projects/micronaut-starter/issues
PackageName: Micronaut Launch
PackageUrl: https://github.com/micronaut-projects/micronaut-starter
License: Apache-2.0
LicenseUrl: https://github.com/micronaut-projects/micronaut-starter/blob/HEAD/LICENSE
ShortDescription: Micronaut - A modern, JVM-based (Java, Groovy, Kotlin), full-stack framework for building modular and testable microservice and serverless applications
Moniker: micronaut
ReleaseNotes: "## What's Changed\r\n• Refactor by @sdelamo in https://github.com/micronaut-projects/micronaut-starter/pull/3133\r\n• Add Python starter support by @graemerocher in https://github.com/micronaut-projects/micronaut-starter/pull/3130\r\n• Support service discovery features in Python projects by @n0tl3ss in https://github.com/micronaut-projects/micronaut-starter/pull/3136\r\n• Turn off build-machine-dependent AOT optimizations by default by @alvarosanchez in https://github.com/micronaut-projects/micronaut-starter/pull/3138\r\n\r\n\r\n**Full Changelog**：https://github.com/micronaut-projects/micronaut-starter/compare/v5.1.5...v5.2.0"
ReleaseNotesUrl: https://github.com/micronaut-projects/micronaut-starter/releases/tag/v5.2.0
ManifestType: defaultLocale
ManifestVersion: 1.12.0
