# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Microsoft.SafetyScanner
PackageVersion: 1.459.421.0
InstallerType: portable
Commands:
- safetyscanner
ReleaseDate: 2026-09-27
Installers:
- Architecture: x86
  InstallerUrl: https://definitionupdates.microsoft.com/packages/content/msert.exe?packageType=Scanner&packageVersion=1.459.421.0&arch=x86
  InstallerSha256: A3748BFB7AD1B95821B52FD6ED43DC859A71EC8DEDE14BA52E3E256613B97151
- Architecture: x64
  InstallerUrl: https://definitionupdates.microsoft.com/packages/content/msert.exe?packageType=Scanner&packageVersion=1.459.421.0&arch=amd64
  InstallerSha256: C622D41B2E7095EBA46A37A08F1A70B0D231A15AF5E10EC683593B3CBE4702AB
ManifestType: installer
ManifestVersion: 1.12.0
