# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ESET.EndpointSecurity
PackageVersion: 13.1.2036.0
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: APPDIR="<INSTALLPATH>"
FileExtensions:
- esil
- json
ReleaseDate: 2026-09-23
Installers:
- Architecture: x64
  InstallerUrl: https://download.eset.com/com/eset/apps/business/ees/windows/v13/13.1.2036.0/ees_nt64.msi
  InstallerSha256: C2E98D7EFEA5BA8EC04E6BE026657A15EB2C9371D3132B6697100EE4CF8206DB
  ProductCode: '{307277A6-1678-4C33-B5AA-9FF8FAF386DD}'
- Architecture: arm64
  InstallerUrl: https://download.eset.com/com/eset/apps/business/ees/windows/v13/13.1.2036.0/ees_arm64.msi
  InstallerSha256: 93B6A723BC527DB2F0324B7A8CDF2C30AC71A1A0ABE008803073001B02D73523
  ProductCode: '{F0AA03DE-460E-4F62-969F-9A4099442D04}'
ManifestType: installer
ManifestVersion: 1.12.0
