# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Movavi.MovaviVideoSuite
PackageVersion: 27.0.0
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: install
Protocols:
- suiteplatform
FileExtensions:
- 3g2p
- ac3
- adts
- aif
- aifc
- alaw
- amr
- amv
- apc
- ape
- au
- avs
- bik
- bnk
- caf
- cavs
- cda
- cdg
- dav
- dpg
- dts
- dv
- dv1394
- dvr-ms
- ea
- ffm
- film
- film_cpk
- flc
- flh
- fli
- flm
- flt
- flx
- gsd
- gsm
- gxf
- h261
- h263
- h264
- ifo
- ivr
- m1v
- m2a
- m2p
- m2s
- m4b
- m4p
- m4r
- mj2
- mjpg
- mka
- mkm
- ml20
- mlp
- mmf
- mod
- mp+
- mp1
- mpc
- mpeg3
- mtv
- mvi
- mxg
- nc
- nsv
- nut
- nuv
- ogm
- oma
- qcp
- ra
- ram
- rax
- rec
- rmj
- rms
- rmx
- rpl
- rtsp
- rva
- sdp
- shn
- smk
- snd
- swf
- sxa
- thd
- thp
- tod
- trp
- ts
- tta
- tts
- vc-1
- vc1
- vfw
- voc
- vro
- w64
- wmvhd
- wpg
- wtv
- wv
- xa
- xvid
ProductCode: Movavi Suite
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  InstallerUrl: https://dl.movavi.com/releases/vs/win/x86_64/27-0-0/MovaviHubWI.exe
  InstallerSha256: ED4301F19EB462D6CD16B0713BD9F04E78C049C80745F188CB393FEBB24D833B
ManifestType: installer
ManifestVersion: 1.12.0
