# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: rstream.rstream
PackageVersion: 1.32.4
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: bin/rstream.exe
    PortableCommandAlias: rstream
Installers:
  - Architecture: x64
    InstallerUrl: https://rstream.io/api/packages/cmuiwu7fu001o04l822ycxydm/download
    InstallerSha256: b3a3f15a43cc4ac3c8e3a26b54aaa1708baccf1751f0cc927392f23be2f29f25
  - Architecture: arm64
    InstallerUrl: https://rstream.io/api/packages/cmuiwu15w001n04l81pvgpi9j/download
    InstallerSha256: 4b6efa25e7520c3381f08b6dca8aecfae1f49e75c8f58622362a62a91e83f927
ManifestType: installer
ManifestVersion: 1.10.0
