# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Multica.MulticaCLI
PackageVersion: 0.6.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: multica.exe
Commands:
- multica
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/multica-ai/multica/releases/download/v0.6.0/multica-cli-0.6.0-windows-amd64.zip
  InstallerSha256: 292CC4D2210CE40AF05653336B5A6CC6D5C927CD1E0D389C205CC8DCA2AB6338
- Architecture: arm64
  InstallerUrl: https://github.com/multica-ai/multica/releases/download/v0.6.0/multica-cli-0.6.0-windows-arm64.zip
  InstallerSha256: C87439A2BE4870C7F42C0E0FEA80CC0268502DF9023F25C2F660456F617B94AA
ManifestType: installer
ManifestVersion: 1.12.0
