# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: KDE.Kolf
PackageVersion: master
InstallerType: nullsoft
UpgradeBehavior: install
ProductCode: kolf
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://cdn.kde.org/ci-builds/games/kolf/master/windows/kolf-master-1073-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: 36433D5D8BBE26BAB44D0B7CA58AAD37DEC243CA2BA8736D466024D18C48FE05
  InstallerSwitches:
    Custom: /CurrentUser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://cdn.kde.org/ci-builds/games/kolf/master/windows/kolf-master-1073-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: 36433D5D8BBE26BAB44D0B7CA58AAD37DEC243CA2BA8736D466024D18C48FE05
  InstallerSwitches:
    Custom: /AllUsers
ManifestType: installer
ManifestVersion: 1.12.0
