# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Astronomer.Astro
PackageVersion: 1.46.0
InstallerLocale: en-US
InstallerType: portable
UpgradeBehavior: install
Commands:
- astro
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Podman.CLI
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/astronomer/astro-cli/releases/download/v1.46.0/astro_1.46.0_windows_amd64.exe
  InstallerSha256: 213D86A60BACE05B25C589B8B4DFE7404C236126A72278250E11052A5E6772FB
- Architecture: arm64
  InstallerUrl: https://github.com/astronomer/astro-cli/releases/download/v1.46.0/astro_1.46.0_windows_arm64.exe
  InstallerSha256: AB0593DD99D5BD782F6BECCF2EDED11CA748B894FB4D744762D4F9CC85E12DBD
ManifestType: installer
ManifestVersion: 1.12.0
