# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: Elinesoft.XTester
PackageVersion: 1.0.0-alpha.3
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.19041.0
InstallerType: inno
Scope: user
UpgradeBehavior: uninstallPrevious
InstallerSwitches:
  Custom: /MERGETASKS="!runcode"
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/79231232393/XTester-releases/releases/download/v1.0.0-alpha.3/XTester-Studio-1.0.0-alpha.3-windows-x64-setup.exe
  InstallerSha256: E2C67CA88F177846451E7328A61CDAD25FE96A70C95DD4016F8764575F32A317
  ProductCode: '{26171DA4-14EE-48C4-9B48-4E2166FCB806}_is1'
  AppsAndFeaturesEntries:
  - DisplayName: XTester Studio (User)
    Publisher: Elinesoft
    ProductCode: '{26171DA4-14EE-48C4-9B48-4E2166FCB806}_is1'
ManifestType: installer
ManifestVersion: 1.12.0
