# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.el
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox ESR
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win32/el/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: EBADEC73372F0C05DF280B75F2F3A9E79E75ADA235A0EA5710A601172289105C
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64/el/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 1A7F045B11BF7CA8882F328EB06864B9AE0316D514A038CA4B5B30CA18800679
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64-aarch64/el/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 7784C870B98427795BFBF6DEEA433B3FC105DF72D075402A6A141BA9024249FB
ManifestType: installer
ManifestVersion: 1.12.0
