# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: Martchus.syncthingctl
PackageVersion: 2.1.7
InstallerType: zip
NestedInstallerType: portable
UpgradeBehavior: uninstallPrevious
ReleaseDate: 2026-09-27
Installers:
- Architecture: x86
  NestedInstallerFiles:
  - RelativeFilePath: syncthingctl-qt5.exe
  InstallerUrl: https://github.com/Martchus/syncthingtray/releases/download/v2.1.7/syncthingctl-qt5-2.1.7-i686-w64-mingw32.exe.zip
  InstallerSha256: 1D1775E4A0A5019A8915EAA9BA787D190FAA3846DE8FD2CB80D997433A267A39
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: syncthingctl.exe
  InstallerUrl: https://github.com/Martchus/syncthingtray/releases/download/v2.1.7/syncthingctl-2.1.7-x86_64-w64-mingw32.exe.zip
  InstallerSha256: 8E14A161676371E10343DF7065706E077730DEADD6E00B58E4295584A869358C
ManifestType: installer
ManifestVersion: 1.12.0
