# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: blakazulu.Findra
PackageVersion: 0.8.0
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Custom: /INSTALLSOURCE=winget
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/blakazulu/findra/releases/download/v0.8.0/findra-setup-x64.exe
  InstallerSha256: 1D0DDB852EB23245A3A817B4304B69BE411FD08076D646536A4A2CE54EE714CD
- Architecture: arm64
  InstallerUrl: https://github.com/blakazulu/findra/releases/download/v0.8.0/findra-setup-arm64.exe
  InstallerSha256: C3C46C10E861BEE0E6A6031A58239053E5934022A6E536F4D8ECFE8CE4582470
ManifestType: installer
ManifestVersion: 1.6.0
