# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: co2lab.Anchors
PackageVersion: 0.1.204
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: anchors.exe
  PortableCommandAlias: anchors
Commands:
- anchors
ReleaseDate: 2026-09-27
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/co2-lab/anchors/releases/download/v0.1.204/anchors_0.1.204_windows_amd64.zip
  InstallerSha256: DE07DD601B974CD0C2D473542305AAC863640F00CB06C0E4CEEC850E26E04B78
- Architecture: arm64
  InstallerUrl: https://github.com/co2-lab/anchors/releases/download/v0.1.204/anchors_0.1.204_windows_arm64.zip
  InstallerSha256: 7707D72C2FFCBAF2C988760337030595A0E5997DB055804BCF87433FBA7836D6
ManifestType: installer
ManifestVersion: 1.12.0
