# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: JustArchiNET.ArchiSteamFarm
PackageVersion: 6.3.9.6
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: ArchiSteamFarm.exe
UpgradeBehavior: install
ReleaseDate: 2026-08-23
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/JustArchiNET/ArchiSteamFarm/releases/download/6.3.9.6/ASF-win-x64.zip
  InstallerSha256: 3050EC9CC5330EED0ED6D0AE22239850F006C800515B518E8A3CAE9FC4184B01
- Architecture: arm64
  InstallerUrl: https://github.com/JustArchiNET/ArchiSteamFarm/releases/download/6.3.9.6/ASF-win-arm64.zip
  InstallerSha256: c33078f75b425d1583e363033d7240eacd61b76bf32d1c17ea12c80e25c110df
ManifestType: installer
ManifestVersion: 1.12.0
