# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: SuperGness.Codey
PackageVersion: 1.2.3
InstallerType: nullsoft
Scope: user
ProductCode: Codey
ReleaseDate: 2026-09-29
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Programs\Codey'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/SuperGness/codey/releases/download/v1.2.3/Codey-1.2.3-windows-x64-setup.exe
  InstallerSha256: 1E5A4D325DBAB0B5A2B2E18580111E0C68E1ED85B7D7AD2A321DB7809267E538
ManifestType: installer
ManifestVersion: 1.12.0
