# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.trs
PackageVersion: "157.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win32/trs/Firefox%20Setup%20157.0.exe
  InstallerSha256: 7699D37057F9F38F226DE6E1EDCDCB99A939FEFCDC5BD8ED76A87B42D6CF5F49
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64/trs/Firefox%20Setup%20157.0.exe
  InstallerSha256: CF3E71F9CCC98F31E630436EB2941817BDFF22B10E1C95038F152DE496527256
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64-aarch64/trs/Firefox%20Setup%20157.0.exe
  InstallerSha256: 866049CC5A1A2E6B14AE3BDBDA66CFF4249ACC93B0811C962930F29BC4C65E70
ManifestType: installer
ManifestVersion: 1.12.0
