# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.sv-SE
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox ESR
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win32/sv-SE/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 07811F9EBB708E1D8170FCD8E4E8A857BD8FAE38FB2D43AFA27DB20367AED7AE
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64/sv-SE/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 2083E4793CB7255AB33BC5E886D7AA1F5A1A9D9AA5FBA3C8C63AB601748DAB49
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64-aarch64/sv-SE/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 644DDEADF1C5C8D1277049D6228170FF964A2D48AD09D78FDF6BE8D8FCB96F96
ManifestType: installer
ManifestVersion: 1.12.0
