# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: deanxv.DoneHub
PackageVersion: 1.23.22
InstallerType: portable
Commands:
- done-hub
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/deanxv/done-hub/releases/download/v1.23.22/done-hub.exe
  InstallerSha256: 5682A73B0F4EFE3DFBFA5E35734BDD621EDC66FA38B0DAE1A7007910251688BB
ManifestType: installer
ManifestVersion: 1.12.0
