# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Atlassian.ServiceManagementLTS
PackageVersion: 11.3.11
InstallerType: exe
InstallerSwitches:
  Silent: -q
  SilentWithProgress: -q -console
Installers:
- Architecture: x64
  InstallerUrl: https://www.atlassian.com/software/jira/downloads/binary/atlassian-servicedesk-11.3.11-x64.exe
  InstallerSha256: 139DD8FDB180837DD054CA248049F261E99D8418D688BDF418563FDE3B9FD2B9
ManifestType: installer
ManifestVersion: 1.12.0
