# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Microsoft.SafetyScanner
PackageVersion: 1.459.484.0
InstallerType: portable
Commands:
- safetyscanner
ReleaseDate: 2026-09-30
Installers:
- Architecture: x86
  InstallerUrl: https://definitionupdates.microsoft.com/packages/content/msert.exe?packageType=Scanner&packageVersion=1.459.484.0&arch=x86
  InstallerSha256: 3FD4EAF3EA552B823B74C1505890CD1DD32C55BB7DAD2D075B5B0CC9ED06BF3F
- Architecture: x64
  InstallerUrl: https://definitionupdates.microsoft.com/packages/content/msert.exe?packageType=Scanner&packageVersion=1.459.484.0&arch=amd64
  InstallerSha256: EEC97860DBBF152EB6C5BA5A5AAB5FBCCDC22ED342BBA83F5346B7F563734784
ManifestType: installer
ManifestVersion: 1.28.0
