# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json
PackageIdentifier: Eumenes.HOSMeeting
PackageVersion: 0.4.9
InstallerLocale: en-US
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://dl.eumenes.ai/downloads/EumenesHOSMeeting-Setup-0.4.9.exe
  InstallerSha256: 93C3B99CC2DACDCEE3110AD574D4B81722A2BBD05F2CCAF5DD7B8ED6D85ACAD1
ManifestType: installer
ManifestVersion: 1.9.0
