# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ptweezy.cronstable
PackageVersion: 1.2.60
InstallerType: burn
Scope: machine
UpgradeBehavior: install
Commands:
- cronstable
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ptweezy/cronstable/releases/download/1.2.60/cronstable-windows-amd64-setup.exe
  InstallerSha256: 7245C8AD61A8115A1FBD8FA500C51AD9CF5C5ACE8AA7592978FD9F71D5D14C30
  ProductCode: '{98635E48-42FF-4D6C-B5F1-2CC7DAB64E5D}'
  AppsAndFeaturesEntries:
  - DisplayName: cronstable
    Publisher: cronstable
    DisplayVersion: 1.2.60
    ProductCode: '{98635E48-42FF-4D6C-B5F1-2CC7DAB64E5D}'
    UpgradeCode: '{E8D4C05B-5ED5-4850-826D-8BA6163E4F8A}'
    InstallerType: burn
  - DisplayName: cronstable
    Publisher: cronstable
    DisplayVersion: 1.2.60
    ProductCode: '{6C56F758-6516-499E-92F8-6B3F6F39E584}'
    UpgradeCode: '{B995CBA8-16CD-48F1-A13B-C4C4B927E7BE}'
    InstallerType: msi
- Architecture: arm64
  InstallerUrl: https://github.com/ptweezy/cronstable/releases/download/1.2.60/cronstable-windows-arm64-setup.exe
  InstallerSha256: 0424ECEB04CFACC5C5536D18A3D3445B6D6CD1913CD9B96FDA78AFF53780C5C8
  ProductCode: '{F3D501F1-6315-4859-8E73-B30F22E2C859}'
  AppsAndFeaturesEntries:
  - DisplayName: cronstable
    Publisher: cronstable
    DisplayVersion: 1.2.60
    ProductCode: '{F3D501F1-6315-4859-8E73-B30F22E2C859}'
    UpgradeCode: '{E8D4C05B-5ED5-4850-826D-8BA6163E4F8A}'
    InstallerType: burn
  - DisplayName: cronstable
    Publisher: cronstable
    DisplayVersion: 1.2.60
    ProductCode: '{F5E6E825-AAC2-4610-A0F4-086B8A617CB9}'
    UpgradeCode: '{B995CBA8-16CD-48F1-A13B-C4C4B927E7BE}'
    InstallerType: msi
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-30
