# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: DevProxy.DevProxy.Beta
PackageVersion: 4.0.0-beta.4
InstallerType: inno
Installers:
 - InstallerUrl: https://github.com/dotnet/dev-proxy/releases/download/v4.0.0-beta.4/dev-proxy-installer-win-x64-v4.0.0-beta.4.exe
   Architecture: x64
   InstallerSha256: 39dabc6f4404ecaa0d889b7a95c121ede957c454968308c33cf4228387ba2623
ManifestType: installer
ManifestVersion: 1.28.0
