# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: OakwoodCommons.kvx
PackageVersion: 0.17.0
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: kvx.exe
  PortableCommandAlias: kvx
UpgradeBehavior: uninstallPrevious
ReleaseDate: 2026-09-29
Installers:
- Architecture: arm64
  InstallerUrl: https://github.com/oakwood-commons/kvx/releases/download/v0.17.0/kvx_0.17.0_Windows_arm64.zip
  InstallerSha256: 28690F9C8B0C4D04FB65740F5DFBEC88A67530346613B46C64566D9EEBB3CC31
- Architecture: x64
  InstallerUrl: https://github.com/oakwood-commons/kvx/releases/download/v0.17.0/kvx_0.17.0_Windows_x86_64.zip
  InstallerSha256: 5FDFD33FD385CA4558B34E4800517CBD99D07CFEEBFA272262D6B19177AA75EC
ManifestType: installer
ManifestVersion: 1.12.0
