# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: kcl-lang.kcl
PackageVersion: 0.13.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: kcl.exe
UpgradeBehavior: install
ReleaseDate: 2026-09-26
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/kcl-lang/cli/releases/download/v0.13.0/kcl-v0.13.0-windows-amd64.zip
  InstallerSha256: 5D9F1AE5536511C98DB4F5DAA83BE9DE7005D05B694270A4209A2BB8D9B883EB
- Architecture: arm64
  InstallerUrl: https://github.com/kcl-lang/cli/releases/download/v0.13.0/kcl-v0.13.0-windows-arm64.zip
  InstallerSha256: 7909DC9CC139F12F566531E0350A5555D862264602CEB55D245F1EE9C17A329D
ManifestType: installer
ManifestVersion: 1.12.0
