# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.vi
PackageVersion: "157.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win32/vi/Firefox%20Setup%20157.0.exe
  InstallerSha256: 3B0DA0D2BDDEF707399BF952414091A1CD65CB695D632C639A710A507EE705B0
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64/vi/Firefox%20Setup%20157.0.exe
  InstallerSha256: 0FCE65414136BC8BCBA35D1BAD3F318A2401848F681FAEE18F9F0D8AD4508363
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64-aarch64/vi/Firefox%20Setup%20157.0.exe
  InstallerSha256: 4CDC5A3B8E807022B406166EDD4E6273321DBB8D4AA1E146FF1BA00CCABF536F
ManifestType: installer
ManifestVersion: 1.12.0
