# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ChangeXbc.WorkBuddySwitch
PackageVersion: 0.1.55
InstallerType: nullsoft
Scope: user
ProductCode: workbuddy-switch
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/changexbc/workbuddy-switch/releases/download/v0.1.55/workbuddy-switch_0.1.55_x64-setup.exe
  InstallerSha256: 615A35B56A04C45B2A264BABDA78E33692DCA68E5F78CC489FD931ED91F36A7C
ManifestType: installer
ManifestVersion: 1.12.0
