# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.trs
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox ESR
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win32/trs/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: E3E7649A00881E188E7B53A682E1A25D01B8F8AE3DCDEC2310AE6A6054B3253B
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64/trs/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 484EC9EA0FC7FEB412A02D9F998F15DC808139F86A5942810F989858BC998C60
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64-aarch64/trs/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: B0FDD405B898235E0E19EC0C00021D3BB6FAE4092C61D8092B13F2ABFD0ABF69
ManifestType: installer
ManifestVersion: 1.12.0
