# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Microsoft.SafetyScanner
PackageVersion: 1.459.424.0
InstallerType: portable
Commands:
- safetyscanner
ReleaseDate: 2026-09-27
Installers:
- Architecture: x86
  InstallerUrl: https://definitionupdates.microsoft.com/packages/content/msert.exe?packageType=Scanner&packageVersion=1.459.424.0&arch=x86
  InstallerSha256: 7150E00841BEA39CA36286A9C28CD5B8EFCC553563965B9EE786D6BB2C4F387C
- Architecture: x64
  InstallerUrl: https://definitionupdates.microsoft.com/packages/content/msert.exe?packageType=Scanner&packageVersion=1.459.424.0&arch=amd64
  InstallerSha256: EB6E3D316DE1332D25F48E307DBFB16043B3BFC89D67EEB6D4570D9899DB606F
ManifestType: installer
ManifestVersion: 1.12.0
