# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.pt-BR
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox ESR
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win32/pt-BR/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 0469576010AD8E0A6EB2D2049E2466B24B0555E01A821A4FCF3537270868512E
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64/pt-BR/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 5DC650C833E1DADDE1B9AADD63923343403520FF227F11C93891047B5BD7DA65
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64-aarch64/pt-BR/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 5063191618F6C502E43A5628FC2070093990E2F18BDD85E211F4F8F52A3D657D
ManifestType: installer
ManifestVersion: 1.12.0
