# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.et
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox ESR
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win32/et/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: D70A25FFB0623A16AEC9A093AEEDB3D6A7CC3E8198770653BBA70F472E1853D6
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64/et/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: F873297AE08D4EB94F7C3260856C5308DAD8B7BC59A2629B296E5E56D3ECDFA9
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.4.0esr/win64-aarch64/et/Firefox%20Setup%20153.4.0esr.exe
  InstallerSha256: 76D4D1606CB423FB782D563F047B44750A8B894776FC5B183DB221D77A16590F
ManifestType: installer
ManifestVersion: 1.12.0
