# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Toolport.Toolport
PackageVersion: 1.23.0
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
ProductCode: Toolport
AppsAndFeaturesEntries:
- DisplayName: Toolport
  Publisher: tsout
  ProductCode: Toolport
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/btsouth/toolport/releases/download/v1.23.0/Toolport_1.23.0_x64-setup.exe
  InstallerSha256: 5A89EAFC7B0FB1D65F45D264968011CA371A30D92C95E446A274352293D1FA66
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-27
