# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: KDE.KFourInLine
PackageVersion: master
InstallerType: nullsoft
UpgradeBehavior: install
ProductCode: kfourinline
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://cdn.kde.org/ci-builds/games/kfourinline/master/windows/kfourinline-master-977-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: 7290EDACF05A2189C50096C2EDA30C9D87C106E72B393313FDB944B5FB14464E
  InstallerSwitches:
    Custom: /CurrentUser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://cdn.kde.org/ci-builds/games/kfourinline/master/windows/kfourinline-master-977-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: 7290EDACF05A2189C50096C2EDA30C9D87C106E72B393313FDB944B5FB14464E
  InstallerSwitches:
    Custom: /AllUsers
ManifestType: installer
ManifestVersion: 1.12.0
