# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: VirusTotal.YARA-X
PackageVersion: 1.21.0
PackageLocale: en-US
Publisher: VirusTotal
PublisherUrl: https://github.com/VirusTotal
PublisherSupportUrl: https://github.com/VirusTotal/yara-x/issues
PackageName: YARA-X
PackageUrl: https://github.com/VirusTotal/yara-x
License: BSD-3-Clause
LicenseUrl: https://github.com/VirusTotal/yara-x/blob/HEAD/LICENSE
ShortDescription: YARA-X is a re-incarnation of YARA, a pattern matching tool designed with malware researchers in mind. This new incarnation intends to be faster, safer and more user-friendly than its predecessor.
ReleaseNotes: |-
  • Add `Scanner.set_module_output` to Python bindings (#744).
  • Add debug command for showing atoms (#748).
  • Allow reading scan lists from stdin (#753).
  • Performance improvements (#747, #750, #755, #756, #758, #775, #781, #782)
  • Add support for more ELF machine types in `elf` module (23a75aa).
  • BUGFIX：make yara-x-py's module features actually work (#766).
  • BUGFIX：allow passing `pathlib.Path` to `add_include_dir` in the Python API (b846b3b).
  • BUGFIX：reduce memory usage in parser (#761).
  • BUGFIX：exclude non-matching files in NDJSON output (61a2dc2).

  Contributors：@CfirTsabari, @matt-acsc, @king-tero
ReleaseNotesUrl: https://github.com/VirusTotal/yara-x/releases/tag/v1.21.0
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/VirusTotal/yara-x/wiki
ManifestType: defaultLocale
ManifestVersion: 1.12.0
